/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mdsql.ui;

import com.mdsql.ui.listener.DlgExcepcionListener;
import com.mdsql.utils.MDSQLConstants;
import com.mdval.ui.utils.DialogSupport;
import com.mdval.ui.utils.FrameSupport;
import java.awt.event.ActionListener;
import java.util.Map;
import javax.swing.JButton;
import javax.swing.JTextArea;

/**
 *
 * @author federico
 */
public class DlgExcepcion extends DialogSupport {

    /**
     * Creates new form DlgErrores
     *
     * @param parent
     * @param modal
     */
    public DlgExcepcion(FrameSupport parent, Boolean modal) {
        super(parent, modal);
    }

    /**
     * Creates new form DlgErrores
     *
     * @param parent
     * @param modal
     * @param params
     */
    public DlgExcepcion(FrameSupport parent, Boolean modal, Map<String, Object> params) {
        super(parent, modal, params);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblMotivoExcepcion = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtMotivoExcepcion = new javax.swing.JTextArea();
        jPanel3 = new javax.swing.JPanel();
        btnAceptar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(223, 159));

        jPanel1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        lblMotivoExcepcion.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblMotivoExcepcion.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblMotivoExcepcion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/info.png"))); // NOI18N
        lblMotivoExcepcion.setText("Motivo de la excepción");
        lblMotivoExcepcion.setIconTextGap(10);
        jPanel1.add(lblMotivoExcepcion);

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_START);

        jPanel2.setLayout(new java.awt.BorderLayout());

        txtMotivoExcepcion.setColumns(20);
        txtMotivoExcepcion.setLineWrap(true);
        txtMotivoExcepcion.setRows(5);
        jScrollPane1.setViewportView(txtMotivoExcepcion);

        jPanel2.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);

        jPanel3.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        btnAceptar.setText("ACEPTAR");
        jPanel3.add(btnAceptar);

        btnCancelar.setText("CANCELAR");
        jPanel3.add(btnCancelar);

        getContentPane().add(jPanel3, java.awt.BorderLayout.PAGE_END);

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblMotivoExcepcion;
    private javax.swing.JTextArea txtMotivoExcepcion;
    // End of variables declaration//GEN-END:variables

    @Override
    protected void initEvents() {
        ActionListener actionListener = new DlgExcepcionListener(this);

        btnAceptar.addActionListener(actionListener);
        btnCancelar.addActionListener(actionListener);
    }

    @Override
    protected void setupLiterals() {
        lblMotivoExcepcion.setText(literales.getLiteral("lblMotivoExcepcion"));
        btnAceptar.setText(literales.getLiteral("btnAceptar"));
        btnCancelar.setText(literales.getLiteral("btnCancelar"));
    }

    @Override
    protected void initModels() {
    }

    @Override
    protected void initialState() {
    }

    @Override
    protected void setupComponents() {
        initComponents();
    }

    public JTextArea getTxtMotivoExcepcion() {
        return txtMotivoExcepcion;
    }

    public void setTxtMotivoExcepcion(JTextArea txtMotivoExcepcion) {
        this.txtMotivoExcepcion = txtMotivoExcepcion;
    }

    public JButton getBtnAceptar() {
        return btnAceptar;
    }

    public JButton getBtnCancelar() {
        return btnCancelar;
    }
    
    
}
