/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mdsql.ui;

import com.mdsql.bussiness.entities.Session;
import java.awt.event.WindowListener;
import java.io.File;
import javax.swing.ListSelectionModel;
import javax.swing.event.ListSelectionListener;
import javax.swing.undo.UndoManager;
import org.apache.commons.lang3.StringUtils;

import com.mdsql.ui.listener.EditorEventHandler;
import com.mdsql.ui.listener.FramePrincipalActionListener;
import com.mdsql.ui.listener.window.FramePrincipalWindowListener;
import com.mdsql.ui.listener.tables.FramePrincipalFicherosReentranteTableListener;
import com.mdsql.ui.listener.tables.ListaObjetosTableListener;
import com.mdsql.ui.menu.MainMenuBar;
import com.mdsql.ui.model.FicherosReentranteTableModel;
import com.mdsql.ui.model.FramePrincipalTypesTableModel;
import com.mdsql.ui.model.cabeceras.TablaFicherosReentranteCabecera;
import com.mdsql.ui.model.cabeceras.TablaTypesCabecera;
import com.mdsql.ui.utils.MDSQLUIHelper;
import com.mdsql.utils.MDSQLAppHelper;
import com.mdsql.utils.MDSQLConstants;
import com.mdsql.utils.MDSQLConstants.Procesado;
import com.mdval.ui.model.DefaultTableModel;
import com.mdval.ui.model.cabeceras.Cabecera;
import com.mdval.ui.utils.FrameSupport;
import java.awt.event.FocusListener;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JInternalFrame;
import javax.swing.JPanel;
import javax.swing.JTabbedPane;
import javax.swing.JTable;
import javax.swing.JTextArea;

import lombok.Getter;
import lombok.Setter;

/**
 *
 * @author federico
 */
public class FramePrincipal extends FrameSupport {

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        btnLoadScript = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JToolBar.Separator();
        btnLoadReentrante = new javax.swing.JButton();
        btnComentarioReentrante = new javax.swing.JButton();
        jSeparator6 = new javax.swing.JToolBar.Separator();
        btnCargarScriptObjetos = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JToolBar.Separator();
        btnProcesarScript = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        btnExecute = new javax.swing.JButton();
        btnEntregarProcesado = new javax.swing.JButton();
        btnLimpiarScripts = new javax.swing.JButton();
        btnLimpiarSesion = new javax.swing.JButton();
        btnCerrarPeticion = new javax.swing.JButton();
        jSeparator4 = new javax.swing.JToolBar.Separator();
        btnProcesadoEnCurso = new javax.swing.JButton();
        btnRefrescarFichero = new javax.swing.JButton();
        btnInformacionModelo = new javax.swing.JButton();
        jSeparator5 = new javax.swing.JToolBar.Separator();
        btnUndo = new javax.swing.JButton();
        btnRedo = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JToolBar.Separator();
        btnCopy = new javax.swing.JButton();
        btnCut = new javax.swing.JButton();
        btnPaste = new javax.swing.JButton();
        splitPane = new javax.swing.JSplitPane();
        panelIzquierda = new javax.swing.JPanel();
        panelScript = new javax.swing.JPanel();
        frmSQLScript = new javax.swing.JInternalFrame();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtSQLCode = new javax.swing.JTextArea();
        panelScriptReentrante = new javax.swing.JPanel();
        frmSQLCambio = new javax.swing.JInternalFrame();
        jScrollPane17 = new javax.swing.JScrollPane();
        txtSQLCambio = new javax.swing.JTextArea();
        frmSQLCreacion = new javax.swing.JInternalFrame();
        jScrollPane15 = new javax.swing.JScrollPane();
        txtSQLCreacion = new javax.swing.JTextArea();
        frmSQLComentarios = new javax.swing.JInternalFrame();
        jScrollPane16 = new javax.swing.JScrollPane();
        txtSQLComentarios = new javax.swing.JTextArea();
        panelDerecha = new javax.swing.JPanel();
        tabPanel = new javax.swing.JTabbedPane();
        panelVigente = new javax.swing.JPanel();
        ifrmSQLModificado = new javax.swing.JInternalFrame();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtSQLModificado = new javax.swing.JTextArea();
        ifrmPDC = new javax.swing.JInternalFrame();
        jScrollPane4 = new javax.swing.JScrollPane();
        txtPDC = new javax.swing.JTextArea();
        ifrmLanzaSQLModificado = new javax.swing.JInternalFrame();
        jScrollPane5 = new javax.swing.JScrollPane();
        txtLanzaSQLModificado = new javax.swing.JTextArea();
        ifrmLanzaPDC = new javax.swing.JInternalFrame();
        jScrollPane6 = new javax.swing.JScrollPane();
        txtLanzaPDC = new javax.swing.JTextArea();
        panelHistorico = new javax.swing.JPanel();
        ifrmSQLH = new javax.swing.JInternalFrame();
        jScrollPane7 = new javax.swing.JScrollPane();
        txtSQLH = new javax.swing.JTextArea();
        ifrmPDCH = new javax.swing.JInternalFrame();
        jScrollPane8 = new javax.swing.JScrollPane();
        txtPDCH = new javax.swing.JTextArea();
        ifrmLanzaSQLH = new javax.swing.JInternalFrame();
        jScrollPane9 = new javax.swing.JScrollPane();
        txtLanzaSQLH = new javax.swing.JTextArea();
        ifrmLanzaPDCH = new javax.swing.JInternalFrame();
        jScrollPane10 = new javax.swing.JScrollPane();
        txtLanzaPDCH = new javax.swing.JTextArea();
        panelTypes = new javax.swing.JPanel();
        ifrmListaObjetos = new javax.swing.JInternalFrame();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblListaObjetos = new javax.swing.JTable();
        ifrmTYS = new javax.swing.JInternalFrame();
        jScrollPane12 = new javax.swing.JScrollPane();
        txtScriptTYS = new javax.swing.JTextArea();
        ifrmTYB = new javax.swing.JInternalFrame();
        jScrollPane13 = new javax.swing.JScrollPane();
        txtScriptTYB = new javax.swing.JTextArea();
        ifrmLanzador = new javax.swing.JInternalFrame();
        jScrollPane11 = new javax.swing.JScrollPane();
        txtScriptLanza = new javax.swing.JTextArea();
        internalFramePDC = new javax.swing.JInternalFrame();
        jScrollPane14 = new javax.swing.JScrollPane();
        txtScriptPDC = new javax.swing.JTextArea();
        panelReentrante = new javax.swing.JPanel();
        pnlFicherosReentrante = new javax.swing.JPanel();
        ifrmFicherosReentrante = new javax.swing.JInternalFrame();
        scpFicherosReentrante = new javax.swing.JScrollPane();
        tblFicherosReentrante = new javax.swing.JTable();
        ifrmReentranteLanza = new javax.swing.JInternalFrame();
        scpReentranteLanza = new javax.swing.JScrollPane();
        txtReentranteLanza = new javax.swing.JTextArea();
        ifrmReentranteFichero = new javax.swing.JInternalFrame();
        scpReentranteFichero = new javax.swing.JScrollPane();
        txtReentranteFichero = new javax.swing.JTextArea();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jToolBar1.setRollover(true);
        jToolBar1.setMargin(new java.awt.Insets(3, 3, 3, 3));

        btnLoadScript.setIcon(new javax.swing.ImageIcon(getClass().getResource("/script.png"))); // NOI18N
        btnLoadScript.setToolTipText("Cargar script");
        btnLoadScript.setFocusable(false);
        btnLoadScript.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnLoadScript.setMaximumSize(new java.awt.Dimension(60, 60));
        btnLoadScript.setMinimumSize(new java.awt.Dimension(60, 60));
        btnLoadScript.setPreferredSize(new java.awt.Dimension(60, 60));
        btnLoadScript.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(btnLoadScript);
        jToolBar1.add(jSeparator1);

        btnLoadReentrante.setIcon(new javax.swing.ImageIcon(getClass().getResource("/reentrante.png"))); // NOI18N
        btnLoadReentrante.setToolTipText("Cargar Reentrante");
        btnLoadReentrante.setFocusable(false);
        btnLoadReentrante.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnLoadReentrante.setMaximumSize(new java.awt.Dimension(60, 60));
        btnLoadReentrante.setMinimumSize(new java.awt.Dimension(60, 60));
        btnLoadReentrante.setPreferredSize(new java.awt.Dimension(60, 60));
        btnLoadReentrante.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(btnLoadReentrante);

        btnComentarioReentrante.setIcon(new javax.swing.ImageIcon(getClass().getResource("/comentarios.png"))); // NOI18N
        btnComentarioReentrante.setToolTipText("Comentarios Reentrante");
        btnComentarioReentrante.setFocusable(false);
        btnComentarioReentrante.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnComentarioReentrante.setMaximumSize(new java.awt.Dimension(60, 60));
        btnComentarioReentrante.setMinimumSize(new java.awt.Dimension(60, 60));
        btnComentarioReentrante.setPreferredSize(new java.awt.Dimension(60, 60));
        btnComentarioReentrante.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(btnComentarioReentrante);
        jToolBar1.add(jSeparator6);

        btnCargarScriptObjetos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/folder.png"))); // NOI18N
        btnCargarScriptObjetos.setText("TYPE");
        btnCargarScriptObjetos.setToolTipText("Cargar script Objetos");
        btnCargarScriptObjetos.setFocusable(false);
        btnCargarScriptObjetos.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCargarScriptObjetos.setMaximumSize(new java.awt.Dimension(60, 60));
        btnCargarScriptObjetos.setMinimumSize(new java.awt.Dimension(60, 60));
        btnCargarScriptObjetos.setPreferredSize(new java.awt.Dimension(60, 60));
        btnCargarScriptObjetos.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(btnCargarScriptObjetos);
        jToolBar1.add(jSeparator2);

        btnProcesarScript.setIcon(new javax.swing.ImageIcon(getClass().getResource("/play.png"))); // NOI18N
        btnProcesarScript.setToolTipText("Procesar script");
        btnProcesarScript.setFocusable(false);
        btnProcesarScript.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnProcesarScript.setMaximumSize(new java.awt.Dimension(60, 60));
        btnProcesarScript.setMinimumSize(new java.awt.Dimension(60, 60));
        btnProcesarScript.setPreferredSize(new java.awt.Dimension(60, 60));
        btnProcesarScript.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(btnProcesarScript);

        btnSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/floppy-disk.png"))); // NOI18N
        btnSave.setToolTipText("Guardar archivo");
        btnSave.setFocusable(false);
        btnSave.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnSave.setMaximumSize(new java.awt.Dimension(60, 60));
        btnSave.setMinimumSize(new java.awt.Dimension(60, 60));
        btnSave.setPreferredSize(new java.awt.Dimension(60, 60));
        btnSave.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(btnSave);

        btnExecute.setIcon(new javax.swing.ImageIcon(getClass().getResource("/checking.png"))); // NOI18N
        btnExecute.setToolTipText("Ejecutar script");
        btnExecute.setFocusable(false);
        btnExecute.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnExecute.setMaximumSize(new java.awt.Dimension(60, 60));
        btnExecute.setMinimumSize(new java.awt.Dimension(60, 60));
        btnExecute.setPreferredSize(new java.awt.Dimension(60, 60));
        btnExecute.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(btnExecute);

        btnEntregarProcesado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/execution.png"))); // NOI18N
        btnEntregarProcesado.setToolTipText("Entregar procesado");
        btnEntregarProcesado.setFocusable(false);
        btnEntregarProcesado.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnEntregarProcesado.setMaximumSize(new java.awt.Dimension(60, 60));
        btnEntregarProcesado.setMinimumSize(new java.awt.Dimension(60, 60));
        btnEntregarProcesado.setPreferredSize(new java.awt.Dimension(60, 60));
        btnEntregarProcesado.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(btnEntregarProcesado);

        btnLimpiarScripts.setIcon(new javax.swing.ImageIcon(getClass().getResource("/clean.png"))); // NOI18N
        btnLimpiarScripts.setToolTipText("Limpar scripts");
        btnLimpiarScripts.setFocusable(false);
        btnLimpiarScripts.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnLimpiarScripts.setMaximumSize(new java.awt.Dimension(60, 60));
        btnLimpiarScripts.setMinimumSize(new java.awt.Dimension(60, 60));
        btnLimpiarScripts.setPreferredSize(new java.awt.Dimension(60, 60));
        btnLimpiarScripts.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(btnLimpiarScripts);

        btnLimpiarSesion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/trash.png"))); // NOI18N
        btnLimpiarSesion.setToolTipText("Limpiar sesión");
        btnLimpiarSesion.setFocusable(false);
        btnLimpiarSesion.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnLimpiarSesion.setMaximumSize(new java.awt.Dimension(60, 60));
        btnLimpiarSesion.setMinimumSize(new java.awt.Dimension(60, 60));
        btnLimpiarSesion.setPreferredSize(new java.awt.Dimension(60, 60));
        btnLimpiarSesion.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(btnLimpiarSesion);

        btnCerrarPeticion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/candado.png"))); // NOI18N
        btnCerrarPeticion.setFocusable(false);
        btnCerrarPeticion.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCerrarPeticion.setMaximumSize(new java.awt.Dimension(60, 60));
        btnCerrarPeticion.setMinimumSize(new java.awt.Dimension(60, 60));
        btnCerrarPeticion.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(btnCerrarPeticion);
        jToolBar1.add(jSeparator4);

        btnProcesadoEnCurso.setIcon(new javax.swing.ImageIcon(getClass().getResource("/info.png"))); // NOI18N
        btnProcesadoEnCurso.setToolTipText("Procesado en curso");
        btnProcesadoEnCurso.setFocusable(false);
        btnProcesadoEnCurso.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnProcesadoEnCurso.setMaximumSize(new java.awt.Dimension(60, 60));
        btnProcesadoEnCurso.setMinimumSize(new java.awt.Dimension(60, 60));
        btnProcesadoEnCurso.setPreferredSize(new java.awt.Dimension(60, 60));
        btnProcesadoEnCurso.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(btnProcesadoEnCurso);

        btnRefrescarFichero.setIcon(new javax.swing.ImageIcon(getClass().getResource("/file.png"))); // NOI18N
        btnRefrescarFichero.setToolTipText("Refrescar fichero");
        btnRefrescarFichero.setFocusable(false);
        btnRefrescarFichero.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnRefrescarFichero.setMaximumSize(new java.awt.Dimension(60, 60));
        btnRefrescarFichero.setMinimumSize(new java.awt.Dimension(60, 60));
        btnRefrescarFichero.setPreferredSize(new java.awt.Dimension(60, 60));
        btnRefrescarFichero.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(btnRefrescarFichero);

        btnInformacionModelo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/information.png"))); // NOI18N
        btnInformacionModelo.setToolTipText("Información del modelo");
        btnInformacionModelo.setFocusable(false);
        btnInformacionModelo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnInformacionModelo.setMaximumSize(new java.awt.Dimension(60, 60));
        btnInformacionModelo.setMinimumSize(new java.awt.Dimension(60, 60));
        btnInformacionModelo.setPreferredSize(new java.awt.Dimension(60, 60));
        btnInformacionModelo.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(btnInformacionModelo);
        jToolBar1.add(jSeparator5);

        btnUndo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/undo.png"))); // NOI18N
        btnUndo.setToolTipText("Deshacer");
        btnUndo.setFocusable(false);
        btnUndo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnUndo.setMaximumSize(new java.awt.Dimension(60, 60));
        btnUndo.setMinimumSize(new java.awt.Dimension(60, 60));
        btnUndo.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(btnUndo);

        btnRedo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/redo.png"))); // NOI18N
        btnRedo.setToolTipText("Rehacer");
        btnRedo.setFocusable(false);
        btnRedo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnRedo.setMaximumSize(new java.awt.Dimension(60, 60));
        btnRedo.setMinimumSize(new java.awt.Dimension(60, 60));
        btnRedo.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(btnRedo);
        jToolBar1.add(jSeparator3);

        btnCopy.setIcon(new javax.swing.ImageIcon(getClass().getResource("/copy.png"))); // NOI18N
        btnCopy.setToolTipText("Copiar");
        btnCopy.setFocusable(false);
        btnCopy.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCopy.setMaximumSize(new java.awt.Dimension(60, 60));
        btnCopy.setMinimumSize(new java.awt.Dimension(60, 60));
        btnCopy.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(btnCopy);

        btnCut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cut.png"))); // NOI18N
        btnCut.setToolTipText("Cortar");
        btnCut.setFocusable(false);
        btnCut.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCut.setMaximumSize(new java.awt.Dimension(60, 60));
        btnCut.setMinimumSize(new java.awt.Dimension(60, 60));
        btnCut.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(btnCut);

        btnPaste.setIcon(new javax.swing.ImageIcon(getClass().getResource("/paste.png"))); // NOI18N
        btnPaste.setToolTipText("Pegar");
        btnPaste.setFocusable(false);
        btnPaste.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnPaste.setMaximumSize(new java.awt.Dimension(60, 60));
        btnPaste.setMinimumSize(new java.awt.Dimension(60, 60));
        btnPaste.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(btnPaste);

        getContentPane().add(jToolBar1, java.awt.BorderLayout.PAGE_START);

        panelIzquierda.setLayout(new java.awt.CardLayout());

        panelScript.setLayout(new java.awt.BorderLayout());

        frmSQLScript.setToolTipText("");
        frmSQLScript.setVisible(true);

        txtSQLCode.setColumns(20);
        txtSQLCode.setRows(5);
        jScrollPane1.setViewportView(txtSQLCode);

        frmSQLScript.getContentPane().add(jScrollPane1, java.awt.BorderLayout.CENTER);

        panelScript.add(frmSQLScript, java.awt.BorderLayout.CENTER);

        panelIzquierda.add(panelScript, "card2");

        panelScriptReentrante.setLayout(new java.awt.GridLayout(3, 1));

        frmSQLCambio.setTitle("Uno");
        frmSQLCambio.setVisible(true);

        txtSQLCambio.setColumns(20);
        txtSQLCambio.setRows(5);
        jScrollPane17.setViewportView(txtSQLCambio);

        frmSQLCambio.getContentPane().add(jScrollPane17, java.awt.BorderLayout.CENTER);

        panelScriptReentrante.add(frmSQLCambio);

        frmSQLCreacion.setTitle("Dos");
        frmSQLCreacion.setVisible(true);

        txtSQLCreacion.setColumns(20);
        txtSQLCreacion.setRows(5);
        jScrollPane15.setViewportView(txtSQLCreacion);

        frmSQLCreacion.getContentPane().add(jScrollPane15, java.awt.BorderLayout.CENTER);

        panelScriptReentrante.add(frmSQLCreacion);

        frmSQLComentarios.setTitle("Tres");
        frmSQLComentarios.setToolTipText("");
        frmSQLComentarios.setVisible(true);

        txtSQLComentarios.setColumns(20);
        txtSQLComentarios.setRows(5);
        jScrollPane16.setViewportView(txtSQLComentarios);

        frmSQLComentarios.getContentPane().add(jScrollPane16, java.awt.BorderLayout.CENTER);

        panelScriptReentrante.add(frmSQLComentarios);

        panelIzquierda.add(panelScriptReentrante, "card3");

        splitPane.setLeftComponent(panelIzquierda);

        panelDerecha.setLayout(new javax.swing.BoxLayout(panelDerecha, javax.swing.BoxLayout.LINE_AXIS));

        panelVigente.setLayout(new java.awt.GridLayout(2, 2));

        ifrmSQLModificado.setVisible(true);

        txtSQLModificado.setEditable(false);
        txtSQLModificado.setColumns(20);
        txtSQLModificado.setRows(5);
        jScrollPane3.setViewportView(txtSQLModificado);

        ifrmSQLModificado.getContentPane().add(jScrollPane3, java.awt.BorderLayout.CENTER);

        panelVigente.add(ifrmSQLModificado);

        ifrmPDC.setVisible(true);

        txtPDC.setEditable(false);
        txtPDC.setColumns(20);
        txtPDC.setRows(5);
        jScrollPane4.setViewportView(txtPDC);

        ifrmPDC.getContentPane().add(jScrollPane4, java.awt.BorderLayout.CENTER);

        panelVigente.add(ifrmPDC);

        ifrmLanzaSQLModificado.setVisible(true);

        txtLanzaSQLModificado.setEditable(false);
        txtLanzaSQLModificado.setColumns(20);
        txtLanzaSQLModificado.setRows(5);
        jScrollPane5.setViewportView(txtLanzaSQLModificado);

        ifrmLanzaSQLModificado.getContentPane().add(jScrollPane5, java.awt.BorderLayout.CENTER);

        panelVigente.add(ifrmLanzaSQLModificado);

        ifrmLanzaPDC.setVisible(true);

        txtLanzaPDC.setEditable(false);
        txtLanzaPDC.setColumns(20);
        txtLanzaPDC.setRows(5);
        jScrollPane6.setViewportView(txtLanzaPDC);

        ifrmLanzaPDC.getContentPane().add(jScrollPane6, java.awt.BorderLayout.CENTER);

        panelVigente.add(ifrmLanzaPDC);

        tabPanel.addTab("Vigente", panelVigente);

        panelHistorico.setLayout(new java.awt.GridLayout(2, 2));

        ifrmSQLH.setVisible(true);

        txtSQLH.setEditable(false);
        txtSQLH.setColumns(20);
        txtSQLH.setRows(5);
        jScrollPane7.setViewportView(txtSQLH);

        ifrmSQLH.getContentPane().add(jScrollPane7, java.awt.BorderLayout.CENTER);

        panelHistorico.add(ifrmSQLH);

        ifrmPDCH.setVisible(true);

        txtPDCH.setEditable(false);
        txtPDCH.setColumns(20);
        txtPDCH.setRows(5);
        jScrollPane8.setViewportView(txtPDCH);

        ifrmPDCH.getContentPane().add(jScrollPane8, java.awt.BorderLayout.CENTER);

        panelHistorico.add(ifrmPDCH);

        ifrmLanzaSQLH.setVisible(true);

        txtLanzaSQLH.setEditable(false);
        txtLanzaSQLH.setColumns(20);
        txtLanzaSQLH.setRows(5);
        jScrollPane9.setViewportView(txtLanzaSQLH);

        ifrmLanzaSQLH.getContentPane().add(jScrollPane9, java.awt.BorderLayout.CENTER);

        panelHistorico.add(ifrmLanzaSQLH);

        ifrmLanzaPDCH.setVisible(true);

        txtLanzaPDCH.setEditable(false);
        txtLanzaPDCH.setColumns(20);
        txtLanzaPDCH.setRows(5);
        jScrollPane10.setViewportView(txtLanzaPDCH);

        ifrmLanzaPDCH.getContentPane().add(jScrollPane10, java.awt.BorderLayout.CENTER);

        panelHistorico.add(ifrmLanzaPDCH);

        tabPanel.addTab("Histórico", panelHistorico);

        ifrmListaObjetos.setVisible(true);

        tblListaObjetos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Orden", "Objeto"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tblListaObjetos);

        ifrmListaObjetos.getContentPane().add(jScrollPane2, java.awt.BorderLayout.CENTER);

        ifrmTYS.setVisible(true);

        txtScriptTYS.setEditable(false);
        txtScriptTYS.setColumns(20);
        txtScriptTYS.setRows(5);
        jScrollPane12.setViewportView(txtScriptTYS);

        ifrmTYS.getContentPane().add(jScrollPane12, java.awt.BorderLayout.CENTER);

        ifrmTYB.setVisible(true);

        txtScriptTYB.setEditable(false);
        txtScriptTYB.setColumns(20);
        txtScriptTYB.setRows(5);
        jScrollPane13.setViewportView(txtScriptTYB);

        ifrmTYB.getContentPane().add(jScrollPane13, java.awt.BorderLayout.CENTER);

        ifrmLanzador.setVisible(true);

        txtScriptLanza.setEditable(false);
        txtScriptLanza.setColumns(20);
        txtScriptLanza.setRows(5);
        jScrollPane11.setViewportView(txtScriptLanza);

        ifrmLanzador.getContentPane().add(jScrollPane11, java.awt.BorderLayout.CENTER);

        internalFramePDC.setVisible(true);

        txtScriptPDC.setEditable(false);
        txtScriptPDC.setColumns(20);
        txtScriptPDC.setRows(5);
        jScrollPane14.setViewportView(txtScriptPDC);

        internalFramePDC.getContentPane().add(jScrollPane14, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout panelTypesLayout = new javax.swing.GroupLayout(panelTypes);
        panelTypes.setLayout(panelTypesLayout);
        panelTypesLayout.setHorizontalGroup(
            panelTypesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTypesLayout.createSequentialGroup()
                .addGroup(panelTypesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ifrmListaObjetos, javax.swing.GroupLayout.DEFAULT_SIZE, 993, Short.MAX_VALUE)
                    .addComponent(ifrmLanzador))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelTypesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ifrmTYB)
                    .addComponent(ifrmTYS, javax.swing.GroupLayout.DEFAULT_SIZE, 1083, Short.MAX_VALUE)
                    .addComponent(internalFramePDC)))
        );
        panelTypesLayout.setVerticalGroup(
            panelTypesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTypesLayout.createSequentialGroup()
                .addComponent(ifrmTYS)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ifrmTYB)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(internalFramePDC))
            .addGroup(panelTypesLayout.createSequentialGroup()
                .addComponent(ifrmListaObjetos, javax.swing.GroupLayout.DEFAULT_SIZE, 304, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ifrmLanzador, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE))
        );

        tabPanel.addTab("Types", panelTypes);

        panelReentrante.setLayout(new java.awt.GridLayout(1, 2));

        pnlFicherosReentrante.setLayout(new java.awt.GridLayout(2, 1));

        ifrmFicherosReentrante.setVisible(true);

        tblFicherosReentrante.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Orden", "Fichero"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        scpFicherosReentrante.setViewportView(tblFicherosReentrante);

        ifrmFicherosReentrante.getContentPane().add(scpFicherosReentrante, java.awt.BorderLayout.PAGE_START);

        pnlFicherosReentrante.add(ifrmFicherosReentrante);

        ifrmReentranteLanza.setVisible(true);

        txtReentranteLanza.setEditable(false);
        txtReentranteLanza.setColumns(20);
        txtReentranteLanza.setRows(5);
        scpReentranteLanza.setViewportView(txtReentranteLanza);

        ifrmReentranteLanza.getContentPane().add(scpReentranteLanza, java.awt.BorderLayout.CENTER);

        pnlFicherosReentrante.add(ifrmReentranteLanza);

        panelReentrante.add(pnlFicherosReentrante);

        ifrmReentranteFichero.setVisible(true);

        txtReentranteFichero.setEditable(false);
        txtReentranteFichero.setColumns(20);
        txtReentranteFichero.setRows(5);
        scpReentranteFichero.setViewportView(txtReentranteFichero);

        ifrmReentranteFichero.getContentPane().add(scpReentranteFichero, java.awt.BorderLayout.CENTER);

        panelReentrante.add(ifrmReentranteFichero);

        tabPanel.addTab("Reentrante", panelReentrante);

        panelDerecha.add(tabPanel);

        splitPane.setRightComponent(panelDerecha);

        getContentPane().add(splitPane, java.awt.BorderLayout.CENTER);

        jMenu1.setText("Permisos");

        jMenuItem1.setText("Permisos generales");
        jMenu1.add(jMenuItem1);

        jMenu3.setText("Permisos personalizados");

        jMenuItem2.setText("Consulta de permisos");
        jMenu3.add(jMenuItem2);

        jMenuItem3.setText("Mantenimiento de permisos personalizados por modelo");
        jMenu3.add(jMenuItem3);

        jMenuItem4.setText("Generar permisos personalizados");
        jMenu3.add(jMenuItem4);

        jMenu1.add(jMenu3);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Variables");

        jMenuItem5.setText("Variables");
        jMenu2.add(jMenuItem5);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCargarScriptObjetos;
    private javax.swing.JButton btnCerrarPeticion;
    private javax.swing.JButton btnComentarioReentrante;
    private javax.swing.JButton btnCopy;
    private javax.swing.JButton btnCut;
    private javax.swing.JButton btnEntregarProcesado;
    private javax.swing.JButton btnExecute;
    private javax.swing.JButton btnInformacionModelo;
    private javax.swing.JButton btnLimpiarScripts;
    private javax.swing.JButton btnLimpiarSesion;
    private javax.swing.JButton btnLoadReentrante;
    private javax.swing.JButton btnLoadScript;
    private javax.swing.JButton btnPaste;
    private javax.swing.JButton btnProcesadoEnCurso;
    private javax.swing.JButton btnProcesarScript;
    private javax.swing.JButton btnRedo;
    private javax.swing.JButton btnRefrescarFichero;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnUndo;
    private javax.swing.JInternalFrame frmSQLCambio;
    private javax.swing.JInternalFrame frmSQLComentarios;
    private javax.swing.JInternalFrame frmSQLCreacion;
    private javax.swing.JInternalFrame frmSQLScript;
    private javax.swing.JInternalFrame ifrmFicherosReentrante;
    private javax.swing.JInternalFrame ifrmLanzaPDC;
    private javax.swing.JInternalFrame ifrmLanzaPDCH;
    private javax.swing.JInternalFrame ifrmLanzaSQLH;
    private javax.swing.JInternalFrame ifrmLanzaSQLModificado;
    private javax.swing.JInternalFrame ifrmLanzador;
    private javax.swing.JInternalFrame ifrmListaObjetos;
    private javax.swing.JInternalFrame ifrmPDC;
    private javax.swing.JInternalFrame ifrmPDCH;
    private javax.swing.JInternalFrame ifrmReentranteFichero;
    private javax.swing.JInternalFrame ifrmReentranteLanza;
    private javax.swing.JInternalFrame ifrmSQLH;
    private javax.swing.JInternalFrame ifrmSQLModificado;
    private javax.swing.JInternalFrame ifrmTYB;
    private javax.swing.JInternalFrame ifrmTYS;
    private javax.swing.JInternalFrame internalFramePDC;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane11;
    private javax.swing.JScrollPane jScrollPane12;
    private javax.swing.JScrollPane jScrollPane13;
    private javax.swing.JScrollPane jScrollPane14;
    private javax.swing.JScrollPane jScrollPane15;
    private javax.swing.JScrollPane jScrollPane16;
    private javax.swing.JScrollPane jScrollPane17;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JToolBar.Separator jSeparator1;
    private javax.swing.JToolBar.Separator jSeparator2;
    private javax.swing.JToolBar.Separator jSeparator3;
    private javax.swing.JToolBar.Separator jSeparator4;
    private javax.swing.JToolBar.Separator jSeparator5;
    private javax.swing.JToolBar.Separator jSeparator6;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JPanel panelDerecha;
    private javax.swing.JPanel panelHistorico;
    private javax.swing.JPanel panelIzquierda;
    private javax.swing.JPanel panelReentrante;
    private javax.swing.JPanel panelScript;
    private javax.swing.JPanel panelScriptReentrante;
    private javax.swing.JPanel panelTypes;
    private javax.swing.JPanel panelVigente;
    private javax.swing.JPanel pnlFicherosReentrante;
    private javax.swing.JScrollPane scpFicherosReentrante;
    private javax.swing.JScrollPane scpReentranteFichero;
    private javax.swing.JScrollPane scpReentranteLanza;
    private javax.swing.JSplitPane splitPane;
    private javax.swing.JTabbedPane tabPanel;
    private javax.swing.JTable tblFicherosReentrante;
    private javax.swing.JTable tblListaObjetos;
    private javax.swing.JTextArea txtLanzaPDC;
    private javax.swing.JTextArea txtLanzaPDCH;
    private javax.swing.JTextArea txtLanzaSQLH;
    private javax.swing.JTextArea txtLanzaSQLModificado;
    private javax.swing.JTextArea txtPDC;
    private javax.swing.JTextArea txtPDCH;
    private javax.swing.JTextArea txtReentranteFichero;
    private javax.swing.JTextArea txtReentranteLanza;
    private javax.swing.JTextArea txtSQLCambio;
    private javax.swing.JTextArea txtSQLCode;
    private javax.swing.JTextArea txtSQLComentarios;
    private javax.swing.JTextArea txtSQLCreacion;
    private javax.swing.JTextArea txtSQLH;
    private javax.swing.JTextArea txtSQLModificado;
    private javax.swing.JTextArea txtScriptLanza;
    private javax.swing.JTextArea txtScriptPDC;
    private javax.swing.JTextArea txtScriptTYB;
    private javax.swing.JTextArea txtScriptTYS;
    // End of variables declaration//GEN-END:variables
    @Getter
    @Setter
    private Procesado procesado;

    @Getter
    @Setter
    private Boolean hasChanged = Boolean.FALSE; // el estado del documento actual, no modificado por defecto

    @Getter
    private UndoManager undoManager; // instancia de UndoManager (administrador de edición)

    @Getter
    private EditorEventHandler editorEventHandler;

    @Getter
    @Setter
    private ArrayList<File> currentFiles;

    @Getter
    @Setter
    private com.mdsql.bussiness.entities.Type typeSeleccionado;

    @Getter
    FramePrincipalActionListener actionListener;

    @Override
    protected void setupComponents() {
        initComponents();
    }

    @Override
    protected void initMenuBar() {
        menuBar = new MainMenuBar(this);
    }

    @Override
    protected void initEvents() {
        actionListener = new FramePrincipalActionListener(this);
        WindowListener windowListener = new FramePrincipalWindowListener(this);
        editorEventHandler = new EditorEventHandler(this);

        addWindowListener(windowListener);
        addOnLoadListener(actionListener);

        btnLoadScript.setActionCommand(MDSQLConstants.FRAME_PRINCIPAL_LOAD_SCRIPT);
        btnLoadReentrante.setActionCommand(MDSQLConstants.FRAME_PRINCIPAL_LOAD_REENTRANTE);
        btnComentarioReentrante.setActionCommand(MDSQLConstants.FRAME_PRINCIPAL_COMENTARIO_REENTRANTE);

        btnCargarScriptObjetos.setActionCommand(MDSQLConstants.FRAME_PRINCIPAL_CARGAR_SCRIPT_OBJETOS);
        btnProcesarScript.setActionCommand(MDSQLConstants.FRAME_PRINCIPAL_PROCESAR_SCRIPT);
        btnSave.setActionCommand(MDSQLConstants.FRAME_PRINCIPAL_SAVE);
        btnExecute.setActionCommand(MDSQLConstants.FRAME_PRINCIPAL_EXECUTE);
        btnEntregarProcesado.setActionCommand(MDSQLConstants.FRAME_PRINCIPAL_ENTREGAR_PROCESADO);
        btnLimpiarScripts.setActionCommand(MDSQLConstants.FRAME_PRINCIPAL_LIMPIAR_SCRIPT);
        btnLimpiarSesion.setActionCommand(MDSQLConstants.FRAME_PRINCIPAL_LIMPIAR_SESION);
        btnProcesadoEnCurso.setActionCommand(MDSQLConstants.FRAME_PRINCIPAL_PROCESADO_CURSO);
        btnRefrescarFichero.setActionCommand(MDSQLConstants.FRAME_PRINCIPAL_REFRESCAR_FICHERO);
        btnInformacionModelo.setActionCommand(MDSQLConstants.FRAME_PRINCIPAL_INFORMACION_MODELO);
        btnCerrarPeticion.setActionCommand(MDSQLConstants.FRAME_PRINCIPAL_BTN_CERRAR);
        btnUndo.setActionCommand(MDSQLConstants.FRAME_PRINCIPAL_BTN_UNDO);
        btnRedo.setActionCommand(MDSQLConstants.FRAME_PRINCIPAL_BTN_REDO);
        btnCut.setActionCommand(MDSQLConstants.FRAME_PRINCIPAL_BTN_CUT);
        btnCopy.setActionCommand(MDSQLConstants.FRAME_PRINCIPAL_BTN_COPY);
        btnPaste.setActionCommand(MDSQLConstants.FRAME_PRINCIPAL_BTN_PASTE);

        btnLoadScript.addActionListener(actionListener);
        btnLoadReentrante.addActionListener(actionListener);
        btnComentarioReentrante.addActionListener(actionListener);
        btnCargarScriptObjetos.addActionListener(actionListener);
        btnProcesarScript.addActionListener(actionListener);
        btnSave.addActionListener(actionListener);
        btnExecute.addActionListener(actionListener);
        btnEntregarProcesado.addActionListener(actionListener);
        btnLimpiarScripts.addActionListener(actionListener);
        btnLimpiarSesion.addActionListener(actionListener);
        btnUndo.addActionListener(actionListener);
        btnRedo.addActionListener(actionListener);
        btnCut.addActionListener(actionListener);
        btnCopy.addActionListener(actionListener);
        btnPaste.addActionListener(actionListener);
        btnProcesadoEnCurso.addActionListener(actionListener);
        btnRefrescarFichero.addActionListener(actionListener);
        btnInformacionModelo.addActionListener(actionListener);
        btnCerrarPeticion.addActionListener(actionListener);

        //Al seleccionar un elemento en la lista de scripts de TYPE
        ListSelectionListener listSelectionListener; 
        listSelectionListener = new ListaObjetosTableListener(this);        
        ListSelectionModel rowSM = tblListaObjetos.getSelectionModel();
        rowSM.addListSelectionListener(listSelectionListener);

        //Al seleccionar un elemento en la lista de scripts de Reentrantes
        FramePrincipalFicherosReentranteTableListener listSelectionListenerReentrante;
        listSelectionListenerReentrante = new FramePrincipalFicherosReentranteTableListener(this);
        ListSelectionModel rowSMReentrante = tblFicherosReentrante.getSelectionModel();
        rowSMReentrante.addListSelectionListener(listSelectionListenerReentrante);

        initTxtSQLEditor(actionListener, txtSQLCode);
        initTxtSQLEditor(actionListener, txtSQLCambio);
        initTxtSQLEditor(actionListener, txtSQLCreacion);
        initTxtSQLEditor(actionListener, txtSQLComentarios);
    }

    private void initTxtSQLEditor(FocusListener listener, JTextArea txtArea) {
        // Manejador de eventos del editor
        txtArea.getDocument().addUndoableEditListener(editorEventHandler);
        txtArea.getDocument().putProperty("owner", txtArea);

        /*  // remueve las posibles combinaciones de teclas asociadas por defecto con el
        // JTextArea
        txtArea.getInputMap().put(KeyStroke.getKeyStroke(KeyEvent.VK_X, ActionEvent.CTRL_MASK), "none"); // remueve
        // CTRL + X
        // ("Cortar")
        txtArea.getInputMap().put(KeyStroke.getKeyStroke(KeyEvent.VK_C, ActionEvent.CTRL_MASK), "none"); // remueve
        // CTRL + C
        // ("Copiar")
        txtArea.getInputMap().put(KeyStroke.getKeyStroke(KeyEvent.VK_V, ActionEvent.CTRL_MASK), "none"); // remueve*/
        // CTRL + V
        // ("Pegar")
        txtArea.addFocusListener(listener);
    }

    @Override
    protected void initModels() {
        Cabecera cabecera = new TablaTypesCabecera();
        FramePrincipalTypesTableModel framePrincipalTypesTableModel = new FramePrincipalTypesTableModel(cabecera);
        MDSQLUIHelper.setTableModelRenderer(tblListaObjetos, framePrincipalTypesTableModel, null);
        //
        Cabecera cabeceraReentrante = new TablaFicherosReentranteCabecera();
        FicherosReentranteTableModel ficherosReentranteTableModel = new FicherosReentranteTableModel(cabeceraReentrante);
        MDSQLUIHelper.setTableModelRenderer(tblFicherosReentrante, ficherosReentranteTableModel, null);
    }

    @Override
    protected void setupLiterals() {
        Session session = (Session) MDSQLAppHelper.getGlobalProperty(MDSQLConstants.SESSION);
        String bbdd = MDSQLAppHelper.getDatabaseName();
        String version = "Versión " + MDSQLConstants.VERSION;
        setTitle("MDSQL [" + session.getCodUsr() + "] - " + bbdd + " (" + version + ")");

        btnLoadScript.setIcon(new ImageIcon(getClass().getResource("/script.png"))); // NOI18N
        btnLoadScript.setToolTipText("Cargar script");
        btnLoadReentrante.setIcon(new ImageIcon(getClass().getResource("/reentrante.png"))); // NOI18N
        btnLoadReentrante.setToolTipText("Cargar script reentrante");

        btnComentarioReentrante.setIcon(new ImageIcon(getClass().getResource("/comentarios.png"))); // NOI18N
        btnComentarioReentrante.setToolTipText("Comentarios reentrante");

        btnCargarScriptObjetos.setIcon(new ImageIcon(getClass().getResource("/folder.png"))); // NOI18N
        btnCargarScriptObjetos.setText("TYPE");
        btnCargarScriptObjetos.setToolTipText("Cargar script Objetos");
        btnProcesarScript.setIcon(new ImageIcon(getClass().getResource("/play.png"))); // NOI18N
        btnProcesarScript.setToolTipText("Procesar script");
        btnSave.setIcon(new ImageIcon(getClass().getResource("/floppy-disk.png"))); // NOI18N
        btnSave.setToolTipText("Guardar archivo");
        btnExecute.setIcon(new ImageIcon(getClass().getResource("/checking.png"))); // NOI18N
        btnExecute.setToolTipText("Ejecutar script");
        btnEntregarProcesado.setIcon(new ImageIcon(getClass().getResource("/execution.png"))); // NOI18N
        btnEntregarProcesado.setToolTipText("Entregar procesado");
        btnLimpiarScripts.setIcon(new ImageIcon(getClass().getResource("/clean.png"))); // NOI18N
        btnLimpiarScripts.setToolTipText("Limpiar scripts");
        btnLimpiarSesion.setIcon(new ImageIcon(getClass().getResource("/trash.png"))); // NOI18N
        btnLimpiarSesion.setToolTipText("Limpiar sesión");
        btnProcesadoEnCurso.setIcon(new ImageIcon(getClass().getResource("/info.png"))); // NOI18N
        btnProcesadoEnCurso.setToolTipText("Procesado en curso");
        btnRefrescarFichero.setIcon(new ImageIcon(getClass().getResource("/file.png"))); // NOI18N
        btnRefrescarFichero.setToolTipText("Refrescar fichero");
        btnInformacionModelo.setIcon(new ImageIcon(getClass().getResource("/information.png"))); // NOI18N
        btnInformacionModelo.setToolTipText("Información del modelo");

        btnUndo.setIcon(new ImageIcon(getClass().getResource("/undo.png"))); // NOI18N
        btnRedo.setIcon(new ImageIcon(getClass().getResource("/redo.png"))); // NOI18N
        btnCopy.setIcon(new ImageIcon(getClass().getResource("/copy.png"))); // NOI18N
        btnCut.setIcon(new ImageIcon(getClass().getResource("/cut.png"))); // NOI18N
        btnPaste.setIcon(new ImageIcon(getClass().getResource("/paste.png"))); // NOI18N
        btnUndo.setToolTipText("Deshacer");
        btnRedo.setToolTipText("Rehacer");
        btnCopy.setToolTipText("Copiar");
        btnCut.setToolTipText("Cortar");
        btnPaste.setToolTipText("Pegar");
    }

    /**
     * Actualiza el estado de las opciones "Deshacer" y "Rehacer".
     */
    public void updateEditionControls() {
        // averigua si se pueden deshacer los cambios en el documento actual
        boolean canUndo = undoManager.canUndo();
        // averigua si se pueden rehacer los cambios en el documento actual
        boolean canRedo = undoManager.canRedo();

        // activa o desactiva las opciones en la barra de herramientas
        btnUndo.setEnabled(canUndo);
        btnRedo.setEnabled(canRedo);
    }

    public void resetFrames() {
        /*** Limpiar los títulos de los frames ***/
        //Pestaña Vigente
        ifrmSQLModificado.setTitle(StringUtils.EMPTY);
        ifrmPDC.setTitle(StringUtils.EMPTY);
        ifrmLanzaSQLModificado.setTitle(StringUtils.EMPTY);
        ifrmLanzaPDC.setTitle(StringUtils.EMPTY);
        // Pestaña Histórico
        ifrmSQLH.setTitle(StringUtils.EMPTY);
        ifrmLanzaSQLH.setTitle(StringUtils.EMPTY);
        ifrmPDCH.setTitle(StringUtils.EMPTY);
        ifrmLanzaPDCH.setTitle(StringUtils.EMPTY);
        //Pestaña Type
        ifrmListaObjetos.setTitle(StringUtils.EMPTY);
        ifrmLanzador.setTitle(StringUtils.EMPTY);
        ifrmTYB.setTitle(StringUtils.EMPTY);
        ifrmTYS.setTitle(StringUtils.EMPTY);
        internalFramePDC.setTitle(StringUtils.EMPTY);
        //Pestaña reentrantes

        /*** Limpiar contenido de los textos ***/
        //Pestaña Vigente
        ifrmFicherosReentrante.setTitle(StringUtils.EMPTY);
        ifrmReentranteLanza.setTitle(StringUtils.EMPTY);
        ifrmReentranteFichero.setTitle(StringUtils.EMPTY);
        // Pestaña Histórico
        txtSQLModificado.setText(StringUtils.EMPTY);
        txtPDC.setText(StringUtils.EMPTY);
        txtLanzaSQLModificado.setText(StringUtils.EMPTY);
        txtLanzaPDC.setText(StringUtils.EMPTY);

        txtSQLH.setText(StringUtils.EMPTY);
        txtLanzaSQLH.setText(StringUtils.EMPTY);
        txtPDCH.setText(StringUtils.EMPTY);
        txtLanzaPDCH.setText(StringUtils.EMPTY);
        //Pestaña Type
        txtScriptTYB.setText(StringUtils.EMPTY);
        txtScriptTYS.setText(StringUtils.EMPTY);
        txtScriptPDC.setText(StringUtils.EMPTY);
        txtScriptLanza.setText(StringUtils.EMPTY);
        //Pestaña reentrantes
        txtReentranteLanza.setText(StringUtils.EMPTY);
        txtReentranteFichero.setText(StringUtils.EMPTY);
        
        /** Limpiar contenido de las tablas **/
        //Pestaña Type
        ((FramePrincipalTypesTableModel) tblListaObjetos.getModel()).clearData();
        //Pestaña reentrantes
        //((ficherosReentranteTableModel))tblFicherosReentrante.getModel()).clearData();
        ((DefaultTableModel) tblFicherosReentrante.getModel()).clearData();
    }

    /**
     *
     */
    public void disableTabs() {
        tabPanel.setEnabledAt(0, Boolean.FALSE);
        tabPanel.setEnabledAt(1, Boolean.FALSE);
        tabPanel.setEnabledAt(2, Boolean.FALSE);
        tabPanel.setEnabledAt(3, Boolean.FALSE);
    }

    /**
     *
     */
    public void disableEditionButtons() {
        btnUndo.setEnabled(Boolean.FALSE);
        btnRedo.setEnabled(Boolean.FALSE);
    }

    public JTabbedPane getTabPanel() {
        return tabPanel;
    }

    public JTable getTblFicherosReentrante() {
        return tblFicherosReentrante;
    }

    public JTable getTblListaObjetos() {
        return tblListaObjetos;
    }

    public JInternalFrame getIfrmLanzador() {
        return ifrmLanzador;
    }

    public JTextArea getTxtSQLCode() {
        return txtSQLCode;
    }

    public JTextArea getTxtScriptLanza() {
        return txtScriptLanza;
    }

    public JTextArea getTxtScriptPDC() {
        return txtScriptPDC;
    }

    public JTextArea getTxtScriptTYB() {
        return txtScriptTYB;
    }

    public JTextArea getTxtScriptTYS() {
        return txtScriptTYS;
    }

    public JInternalFrame getFrmSQLScript() {
        return frmSQLScript;
    }

    public JInternalFrame getFrmSQLCambio() {
        return frmSQLCambio;
    }

    public JInternalFrame getFrmSQLComentarios() {
        return frmSQLComentarios;
    }

    public JInternalFrame getFrmSQLCreacion() {
        return frmSQLCreacion;
    }

    public JInternalFrame getIfrmLanzaPDC() {
        return ifrmLanzaPDC;
    }

    public JInternalFrame getIfrmLanzaPDCH() {
        return ifrmLanzaPDCH;
    }

    public JInternalFrame getIfrmLanzaSQLH() {
        return ifrmLanzaSQLH;
    }

    public JInternalFrame getIfrmLanzaSQLModificado() {
        return ifrmLanzaSQLModificado;
    }

    public JInternalFrame getIfrmFicherosReentrante() {
        return ifrmFicherosReentrante;
    }

    public JInternalFrame getIfrmListaObjetos() {
        return ifrmListaObjetos;
    }

    public JButton getBtnCargarScriptObjetos() {
        return btnCargarScriptObjetos;
    }

    public JButton getBtnCopy() {
        return btnCopy;
    }

    public JButton getBtnCut() {
        return btnCut;
    }

    public JButton getBtnEntregarProcesado() {
        return btnEntregarProcesado;
    }

    public JButton getBtnExecute() {
        return btnExecute;
    }

    public JButton getBtnInformacionModelo() {
        return btnInformacionModelo;
    }

    public JButton getBtnLimpiarScripts() {
        return btnLimpiarScripts;
    }

    public JButton getBtnLimpiarSesion() {
        return btnLimpiarSesion;
    }

    public JButton getBtnLoadReentrante() {
        return btnLoadReentrante;
    }

    public JButton getBtnLoadScript() {
        return btnLoadScript;
    }

    public JButton getBtnPaste() {
        return btnPaste;
    }

    public JButton getBtnProcesadoEnCurso() {
        return btnProcesadoEnCurso;
    }

    public JButton getBtnProcesarScript() {
        return btnProcesarScript;
    }

    public JButton getBtnRedo() {
        return btnRedo;
    }

    public JButton getBtnRefrescarFichero() {
        return btnRefrescarFichero;
    }

    public JButton getBtnCerrarPeticion() {
        return btnCerrarPeticion;
    }

    public JButton getBtnSave() {
        return btnSave;
    }

    public JButton getBtnUndo() {
        return btnUndo;
    }

    public JPanel getPanelHistorico() {
        return panelHistorico;
    }

    public JPanel getPanelIzquierda() {
        return panelIzquierda;
    }

    public JPanel getPanelReentrante() {
        return panelReentrante;
    }

    public JPanel getPanelScript() {
        return panelScript;
    }

    public JPanel getPanelScriptReentrante() {
        return panelScriptReentrante;
    }

    public JInternalFrame getIfrmPDC() {
        return ifrmPDC;
    }

    public JInternalFrame getIfrmPDCH() {
        return ifrmPDCH;
    }

    public JInternalFrame getIfrmSQLH() {
        return ifrmSQLH;
    }

    public JInternalFrame getIfrmSQLModificado() {
        return ifrmSQLModificado;
    }

    public JTextArea getTxtLanzaPDC() {
        return txtLanzaPDC;
    }

    public JTextArea getTxtLanzaSQLModificado() {
        return txtLanzaSQLModificado;
    }

    public JTextArea getTxtPDC() {
        return txtPDC;
    }

    public JTextArea getTxtLanzaPDCH() {
        return txtLanzaPDCH;
    }

    public JTextArea getTxtLanzaSQLH() {
        return txtLanzaSQLH;
    }

    public JTextArea getTxtPDCH() {
        return txtPDCH;
    }

    public JTextArea getTxtSQLCreacion() {
        return txtSQLCreacion;
    }

    public JTextArea getTxtSQLComentarios() {
        return txtSQLComentarios;
    }

    public JTextArea getTxtSQLCambio() {
        return txtSQLCambio;
    }

    public JTextArea getTxtSQLH() {
        return txtSQLH;
    }

    public JTextArea getTxtSQLModificado() {
        return txtSQLModificado;
    }

    public JInternalFrame getIfrmTYB() {
        return ifrmTYB;
    }

    public JInternalFrame getIfrmTYS() {
        return ifrmTYS;
    }

    public JInternalFrame getInternalFramePDC() {
        return internalFramePDC;
    }

    public JInternalFrame getIfrmReentranteLanza() {
        return ifrmReentranteLanza;
    }

    public JTextArea getTxtReentranteLanza() {
        return txtReentranteLanza;
    }

    public JInternalFrame getIfrmReentranteFichero() {
        return ifrmReentranteFichero;
    }

    public JTextArea getTxtReentranteFichero() {
        return txtReentranteFichero;
    }

    public File getCurrentFile() {
        if (currentFiles == null || currentFiles.isEmpty()) {
            return null;
        }
        return currentFiles.get(0);
    }

    public void setCurrentFile(File file) {
        if (currentFiles == null) {
            currentFiles = new ArrayList();
        }
        currentFiles.add(file);
    }

    public JButton getBtnComentarioReentrante() {
        return btnComentarioReentrante;
    }

    @Override
    protected void initialState() {
        undoManager = new UndoManager(); // construye una instancia de UndoManager
        undoManager.setLimit(50); // le asigna un límite al buffer de ediciones

        disableEditionButtons();

        txtSQLCode.setEditable(Boolean.FALSE);
        txtSQLCode.setEnabled(Boolean.FALSE);
        // Ponemos la linea divisoria como 15% del ancho total
        splitPane.setDividerLocation(0.15);

        txtScriptLanza.setEditable(Boolean.FALSE);

    }

}
