/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mdsql.ui;

import java.util.Map;

import javax.swing.ListSelectionModel;
import javax.swing.event.ListSelectionListener;

import org.apache.commons.lang3.StringUtils;

import com.mdsql.bussiness.entities.Modelo;
import com.mdsql.bussiness.entities.Session;
import com.mdsql.ui.adapter.DoubleClickMouseAdapter;
import com.mdsql.ui.listener.PantallaSeleccionModelosListener;
import com.mdsql.ui.listener.tables.PantallaSeleccionModelosTableListener;
import com.mdsql.ui.model.SeleccionModelosTableModel;
import com.mdsql.ui.model.cabeceras.TablaModelosCabecera;
import com.mdsql.ui.utils.MDSQLUIHelper;
import com.mdsql.utils.MDSQLAppHelper;
import com.mdsql.utils.MDSQLConstants;
import com.mdval.ui.model.cabeceras.Cabecera;
import com.mdval.ui.utils.DialogSupport;
import com.mdval.ui.utils.FrameSupport;
import javax.swing.JButton;
import javax.swing.JTable;
import javax.swing.JTextField;

import lombok.Getter;
import lombok.Setter;

public class PantallaSeleccionModelos extends DialogSupport {

    @Getter
    @Setter
    private Modelo seleccionado;
    // End of variables declaration                   

    @Getter
    private PantallaSeleccionModelosListener pantallaSeleccionModelosListener;

    public PantallaSeleccionModelos(FrameSupport parent, Boolean modal) {
        super(parent, modal);
    }

    public PantallaSeleccionModelos(FrameSupport parent, Boolean modal, Map<String, Object> params) {
        super(parent, modal, params);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtCodModelo = new javax.swing.JTextField();
        txtNombreModelo = new javax.swing.JTextField();
        txtCodSubmodelo = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblModelos = new javax.swing.JTable();
        btnSeleccionar = new javax.swing.JButton();
        panelLogo = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        btnPermisosGenerales = new javax.swing.JButton();
        btnPermisosPorObjeto = new javax.swing.JButton();
        btnPermisosPorColumna = new javax.swing.JButton();
        btnVariables = new javax.swing.JButton();
        btnNotas = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1350, 500));
        setPreferredSize(new java.awt.Dimension(1400, 500));

        jLabel3.setText("Cod. modelo");

        jLabel4.setText("Nombre modelo");

        jLabel5.setText("Cod. submodelo");

        txtCodModelo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodModeloActionPerformed(evt);
            }
        });

        txtNombreModelo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreModeloActionPerformed(evt);
            }
        });

        txtCodSubmodelo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodSubmodeloActionPerformed(evt);
            }
        });

        btnBuscar.setText("BUSCAR");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        tblModelos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "CódigoX", "Descripción", "Esquema", "BBDD", "Carpeta", "Capa USROWN", "Grenera Variables", "GRANT ALL", "GRANT PUBLIC", "Inhabilitado", "Observaciones", "Entrega PDC"
            }
        ));
        jScrollPane2.setViewportView(tblModelos);

        btnSeleccionar.setText("SELECCIONAR");

        panelLogo.setPreferredSize(new java.awt.Dimension(286, 63));

        javax.swing.GroupLayout panelLogoLayout = new javax.swing.GroupLayout(panelLogo);
        panelLogo.setLayout(panelLogoLayout);
        panelLogoLayout.setHorizontalGroup(
            panelLogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 286, Short.MAX_VALUE)
        );
        panelLogoLayout.setVerticalGroup(
            panelLogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 63, Short.MAX_VALUE)
        );

        lblTitulo.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblTitulo.setText("Modelos");

        btnPermisosGenerales.setText("PERMISOS GENERALES");
        btnPermisosGenerales.setEnabled(false);

        btnPermisosPorObjeto.setText("PERMISOS POR OBJETO");
        btnPermisosPorObjeto.setEnabled(false);

        btnPermisosPorColumna.setText("PERMISOS POR COLUMNA");
        btnPermisosPorColumna.setEnabled(false);

        btnVariables.setText("VARIABLES");
        btnVariables.setEnabled(false);

        btnNotas.setText("NOTAS");
        btnNotas.setEnabled(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(panelLogo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblTitulo))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtCodModelo, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtNombreModelo, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtCodSubmodelo, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnBuscar)
                        .addGap(398, 398, 398))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(btnNotas)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnVariables)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnPermisosPorColumna)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnPermisosPorObjeto)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnPermisosGenerales)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnSeleccionar, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblTitulo, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelLogo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNombreModelo, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3)
                    .addComponent(txtCodModelo, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(txtCodSubmodelo, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 333, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSeleccionar)
                    .addComponent(btnPermisosGenerales)
                    .addComponent(btnPermisosPorObjeto)
                    .addComponent(btnPermisosPorColumna)
                    .addComponent(btnVariables)
                    .addComponent(btnNotas))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtCodModeloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodModeloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodModeloActionPerformed

    private void txtNombreModeloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreModeloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreModeloActionPerformed

    private void txtCodSubmodeloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodSubmodeloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodSubmodeloActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBuscarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnNotas;
    private javax.swing.JButton btnPermisosGenerales;
    private javax.swing.JButton btnPermisosPorColumna;
    private javax.swing.JButton btnPermisosPorObjeto;
    private javax.swing.JButton btnSeleccionar;
    private javax.swing.JButton btnVariables;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JPanel panelLogo;
    private javax.swing.JTable tblModelos;
    private javax.swing.JTextField txtCodModelo;
    private javax.swing.JTextField txtCodSubmodelo;
    private javax.swing.JTextField txtNombreModelo;
    // End of variables declaration//GEN-END:variables

    @Override
    protected void setupComponents() {
        initComponents();
    }

    @Override
    protected void initEvents() {
        pantallaSeleccionModelosListener = new PantallaSeleccionModelosListener(this);
        ListSelectionListener listSelectionListener = new PantallaSeleccionModelosTableListener(this);

        btnBuscar.setActionCommand(MDSQLConstants.PANTALLA_SELECCION_MODELOS_BTN_BUSCAR);
        btnNotas.setActionCommand(MDSQLConstants.PANTALLA_SELECCION_MODELOS_BTN_NOTAS);
        btnPermisosGenerales.setActionCommand(MDSQLConstants.PANTALLA_SELECCION_MODELOS_BTN_PERMISOS_GENERALES);
        btnPermisosPorColumna.setActionCommand(MDSQLConstants.PANTALLA_SELECCION_MODELOS_BTN_PERMISOS_POR_COLUMNA);
        btnPermisosPorObjeto.setActionCommand(MDSQLConstants.PANTALLA_SELECCION_MODELOS_BTN_PERMISOS_POR_OBJETO);
        btnSeleccionar.setActionCommand(MDSQLConstants.PANTALLA_SELECCION_MODELOS_BTN_SELECCIONAR);
        btnVariables.setActionCommand(MDSQLConstants.PANTALLA_SELECCION_MODELOS_BTN_VARIABLES);

        btnBuscar.addActionListener(pantallaSeleccionModelosListener);
        btnNotas.addActionListener(pantallaSeleccionModelosListener);
        btnPermisosGenerales.addActionListener(pantallaSeleccionModelosListener);
        btnPermisosPorColumna.addActionListener(pantallaSeleccionModelosListener);
        btnPermisosPorObjeto.addActionListener(pantallaSeleccionModelosListener);
        btnSeleccionar.addActionListener(pantallaSeleccionModelosListener);
        btnVariables.addActionListener(pantallaSeleccionModelosListener);

        this.addOnLoadListener(pantallaSeleccionModelosListener);

        ListSelectionModel rowSM = tblModelos.getSelectionModel();
        rowSM.addListSelectionListener(listSelectionListener);
        
        // Tratamiendo doble click
        DoubleClickMouseAdapter doubleClickMouseAdapter = new DoubleClickMouseAdapter();
        doubleClickMouseAdapter.setListener(pantallaSeleccionModelosListener);
        tblModelos.addMouseListener(doubleClickMouseAdapter);
    }

    @Override
    protected void initModels() {
        Cabecera cabecera = new TablaModelosCabecera();
        SeleccionModelosTableModel seleccionModelosTableModel = new SeleccionModelosTableModel(cabecera);
        MDSQLUIHelper.setTableModel(tblModelos, seleccionModelosTableModel);
    }    

    @Override
    protected void initialState() {
        btnSeleccionar.setEnabled(Boolean.FALSE);
        // Los botones adicionales estarán deshabilitados por defecto
        btnNotas.setEnabled(Boolean.FALSE);
        btnPermisosGenerales.setEnabled(Boolean.FALSE);
        btnPermisosPorColumna.setEnabled(Boolean.FALSE);
        btnPermisosPorObjeto.setEnabled(Boolean.FALSE);
        btnSeleccionar.setEnabled(Boolean.FALSE);
        btnVariables.setEnabled(Boolean.FALSE);
    }

    @Override
    protected void setupLiterals() {
        setTitle(literales.getLiteral("PantallaSeleccionModelos.titulo"));

        lblTitulo.setText(literales.getLiteral("PantallaSeleccionModelos.lblTitulo"));
        jLabel3.setText(literales.getLiteral("PantallaSeleccionModelos.label3"));
        jLabel4.setText(literales.getLiteral("PantallaSeleccionModelos.label4"));
        jLabel5.setText(literales.getLiteral("PantallaSeleccionModelos.label5"));
        btnBuscar.setText(literales.getLiteral("PantallaSeleccionModelos.buscar"));
        btnNotas.setText(literales.getLiteral("PantallaSeleccionModelos.notas"));
        btnPermisosGenerales.setText(literales.getLiteral("PantallaSeleccionModelos.permisosGenerales"));
        btnPermisosPorColumna.setText(literales.getLiteral("PantallaSeleccionModelos.permisosColumna"));
        btnPermisosPorObjeto.setText(literales.getLiteral("PantallaSeleccionModelos.permisosObjeto"));
        btnSeleccionar.setText(literales.getLiteral("PantallaSeleccionModelos.seleccionar"));
        btnVariables.setText(literales.getLiteral("PantallaSeleccionModelos.variables"));
    }

    public JTable getTblModelos() {
        return tblModelos;
    }

    public JTextField getTxtCodModelo() {
        return txtCodModelo;
    }

    public JTextField getTxtCodSubmodelo() {
        return txtCodSubmodelo;
    }

    public JTextField getTxtNombreModelo() {
        return txtNombreModelo;
    }

    public JButton getBtnNotas() {
        return btnNotas;
    }

    public JButton getBtnPermisosGenerales() {
        return btnPermisosGenerales;
    }

    public JButton getBtnSeleccionar() {
        return btnSeleccionar;
    }

    public JButton getBtnVariables() {
        return btnVariables;
    }

    public JButton getBtnPermisosPorColumna() {
        return btnPermisosPorColumna;
    }

    public JButton getBtnPermisosPorObjeto() {
        return btnPermisosPorObjeto;
    }
}
