/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mdsql.ui;

import java.awt.event.ItemListener;
import java.util.List;
import java.util.Map;
import javax.swing.JButton;
import javax.swing.JCheckBox;
import javax.swing.JComboBox;
import javax.swing.JTextArea;
import javax.swing.JTextField;
import javax.swing.JTable;
import javax.swing.ListSelectionModel;
import javax.swing.event.ListSelectionListener;

import com.mdsql.bussiness.entities.Aviso;
import com.mdsql.bussiness.entities.BBDD;
import com.mdsql.bussiness.entities.Proceso;
import com.mdsql.bussiness.entities.SubProyecto;
import com.mdsql.bussiness.entities.TextoLinea;
import com.mdsql.ui.listener.PantallaProcesarScriptActionListener;
import com.mdsql.ui.listener.combo.ProcesarScriptBBDDItemListener;
import com.mdsql.ui.listener.combo.SubproyectoItemListener;
import com.mdsql.ui.listener.tables.AvisosTableListener;
import com.mdsql.ui.listener.tables.UltimasPeticionesTableListener;
import com.mdsql.ui.model.BBDDComboBoxModel;
import com.mdsql.ui.model.ProcesarScriptNotaTableModel;
import com.mdsql.ui.model.ProcesarScriptUltimasPeticionesTableModel;
import com.mdsql.ui.model.SubProyectoComboBoxModel;
import com.mdsql.ui.model.cabeceras.TablaNotasCabecera;
import com.mdsql.ui.model.cabeceras.TablaUltimasPeticionesCabecera;
import com.mdsql.ui.renderer.CmbBBDDRenderer;
import com.mdsql.ui.renderer.NivelAvisosTableCellRenderer;
import com.mdsql.ui.renderer.CmbSubProyectoRenderer;
import com.mdsql.ui.utils.DialogSupportModeloPermiso;
import com.mdsql.ui.utils.MDSQLUIHelper;
import com.mdsql.utils.MDSQLConstants.Procesado;
import com.mdval.ui.model.cabeceras.Cabecera;
import com.mdval.ui.utils.FrameSupport;

import lombok.Getter;
import lombok.Setter;

/**
 *
 * @author federico
 */
public class PantallaProcesarScript extends DialogSupportModeloPermiso implements PantallaProcesar {

    /**
     * @param parent
     * @param modal
     */
    public PantallaProcesarScript(FrameSupport parent, Boolean modal) {
        super(parent, modal);
    }

    /**
     * Creates new form
     *
     * @param parent
     * @param modal
     * @param params
     */
    public PantallaProcesarScript(FrameSupport parent, Boolean modal, Map<String, Object> params) {
        super(parent, modal, params);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblModeloProyecto = new javax.swing.JLabel();
        txtModeloProyecto = new javax.swing.JTextField();
        btnModeloProyecto = new javax.swing.JButton();
        lblSubModelo = new javax.swing.JLabel();
        cmbSubModelo = new javax.swing.JComboBox<SubProyecto>();
        lblPeticion = new javax.swing.JLabel();
        txtPeticion = new javax.swing.JTextField();
        lblSolicitadaPor = new javax.swing.JLabel();
        txtSolicitadaPor = new javax.swing.JTextField();
        lblEsquema = new javax.swing.JLabel();
        txtEsquema = new javax.swing.JTextField();
        lblBBDD = new javax.swing.JLabel();
        cmbBBDD = new javax.swing.JComboBox<>();
        lblGenerarHistorico = new javax.swing.JLabel();
        chkGenerarHistorico = new javax.swing.JCheckBox();
        lblBBDDHistorico = new javax.swing.JLabel();
        txtBBDDHistorico = new javax.swing.JTextField();
        lblEsquemaHistorico = new javax.swing.JLabel();
        txtEsquemaHistorico = new javax.swing.JTextField();
        lblDemanda = new javax.swing.JLabel();
        txtDemanda = new javax.swing.JTextField();
        lblDescripcion = new javax.swing.JLabel();
        scrollPaneDescripcion = new javax.swing.JScrollPane();
        txtDescripcion = new javax.swing.JTextArea();
        lblNombreTabla = new javax.swing.JLabel();
        txtNombreTabla = new javax.swing.JTextField();
        lblTipoOperacion = new javax.swing.JLabel();
        txtTipoOperacion = new javax.swing.JTextField();
        btnRecuperarUltimoProcesado = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        lblNotasAvisos = new javax.swing.JLabel();
        scrollPaneTblNotas = new javax.swing.JScrollPane();
        tblNotas = new javax.swing.JTable();
        lblDescripcionAviso = new javax.swing.JLabel();
        scpDescripcionAviso = new javax.swing.JScrollPane();
        txtDescripcionAviso = new javax.swing.JTextArea();
        lblUltimasPeticiones = new javax.swing.JLabel();
        scrollPaneTblUltimasPeticiones = new javax.swing.JScrollPane();
        tblUltimasPeticiones = new javax.swing.JTable();
        btnParametros = new javax.swing.JButton();
        btnVerProcesado = new javax.swing.JButton();
        btnProcesar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1105, 729));

        lblModeloProyecto.setText("Modelo o proyecto");

        btnModeloProyecto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/loupe.png"))); // NOI18N

        lblSubModelo.setText("Submodelo");

        cmbSubModelo.setModel(new SubProyectoComboBoxModel());

        lblPeticion.setText("Petición");

        lblSolicitadaPor.setText("Solicitada por");

        lblEsquema.setText("Esquema");

        txtEsquema.setEditable(false);

        lblBBDD.setText("BBDD");

        cmbBBDD.setModel(new BBDDComboBoxModel());

        lblGenerarHistorico.setText("Generar histórico");

        chkGenerarHistorico.setEnabled(false);

        lblBBDDHistorico.setText("BBDD histórico");

        txtBBDDHistorico.setEditable(false);

        lblEsquemaHistorico.setText("Esquema histórico");

        txtEsquemaHistorico.setEditable(false);

        lblDemanda.setText("Demanda");

        lblDescripcion.setText("Descripción");

        txtDescripcion.setColumns(20);
        txtDescripcion.setRows(5);
        scrollPaneDescripcion.setViewportView(txtDescripcion);

        lblNombreTabla.setText("Nombre Tabla");

        txtNombreTabla.setEditable(false);

        lblTipoOperacion.setText("Tipo de Operación");

        txtTipoOperacion.setEditable(false);

        btnRecuperarUltimoProcesado.setText("Recuperar último procesado");

        btnLimpiar.setText("Limpiar");

        lblNotasAvisos.setText("Notas / avisos");

        tblNotas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        scrollPaneTblNotas.setViewportView(tblNotas);

        lblDescripcionAviso.setText("Descripción Aviso");

        txtDescripcionAviso.setEditable(false);
        txtDescripcionAviso.setColumns(20);
        txtDescripcionAviso.setRows(5);
        scpDescripcionAviso.setViewportView(txtDescripcionAviso);

        lblUltimasPeticiones.setText("Últimas peticiones");

        tblUltimasPeticiones.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        scrollPaneTblUltimasPeticiones.setViewportView(tblUltimasPeticiones);

        btnParametros.setText("Parámetros");

        btnVerProcesado.setText("Ver procesado");

        btnProcesar.setText("Procesar");

        btnCancelar.setText("Cancelar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(13, 13, 13)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(lblBBDD)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(lblModeloProyecto)
                                                    .addComponent(lblSubModelo, javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(lblPeticion, javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(lblSolicitadaPor, javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(lblEsquema, javax.swing.GroupLayout.Alignment.TRAILING))))
                                        .addComponent(lblEsquemaHistorico, javax.swing.GroupLayout.Alignment.TRAILING))
                                    .addComponent(lblGenerarHistorico, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblBBDDHistorico, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblDescripcion, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblDemanda, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblNombreTabla, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblTipoOperacion, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(cmbSubModelo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cmbBBDD, 0, 214, Short.MAX_VALUE)
                                    .addComponent(chkGenerarHistorico)
                                    .addComponent(txtPeticion)
                                    .addComponent(txtSolicitadaPor)
                                    .addComponent(txtEsquema)
                                    .addComponent(txtBBDDHistorico)
                                    .addComponent(txtEsquemaHistorico)
                                    .addComponent(scrollPaneDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txtModeloProyecto, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnModeloProyecto, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(txtDemanda)
                                    .addComponent(txtNombreTabla)
                                    .addComponent(txtTipoOperacion))
                                .addGap(39, 39, 39))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(btnRecuperarUltimoProcesado)
                                .addGap(54, 54, 54)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(scrollPaneTblNotas)
                            .addComponent(scrollPaneTblUltimasPeticiones)
                            .addComponent(scpDescripcionAviso)
                            .addComponent(lblNotasAvisos)
                            .addComponent(lblDescripcionAviso)
                            .addComponent(lblUltimasPeticiones)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(205, 205, 205)
                        .addComponent(btnLimpiar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 330, Short.MAX_VALUE)
                        .addComponent(btnParametros, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnVerProcesado)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnProcesar, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnModeloProyecto, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtModeloProyecto, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblModeloProyecto, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblNotasAvisos, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblSubModelo, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmbSubModelo, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtPeticion, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblPeticion, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtSolicitadaPor, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblSolicitadaPor, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblEsquema, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtEsquema, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cmbBBDD, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblBBDD, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(chkGenerarHistorico, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblGenerarHistorico, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtBBDDHistorico, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblBBDDHistorico, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtEsquemaHistorico, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblEsquemaHistorico, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(scrollPaneTblNotas, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblDescripcionAviso, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(scpDescripcionAviso, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblUltimasPeticiones, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(scrollPaneTblUltimasPeticiones, javax.swing.GroupLayout.DEFAULT_SIZE, 301, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnProcesar, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnVerProcesado, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnParametros, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtDemanda, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblDemanda, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(scrollPaneDescripcion)
                            .addComponent(lblDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblNombreTabla, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNombreTabla, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblTipoOperacion, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTipoOperacion, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnRecuperarUltimoProcesado, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnModeloProyecto;
    private javax.swing.JButton btnParametros;
    private javax.swing.JButton btnProcesar;
    private javax.swing.JButton btnRecuperarUltimoProcesado;
    private javax.swing.JButton btnVerProcesado;
    private javax.swing.JCheckBox chkGenerarHistorico;
    private javax.swing.JComboBox<BBDD> cmbBBDD;
    private javax.swing.JComboBox<SubProyecto> cmbSubModelo;
    private javax.swing.JLabel lblBBDD;
    private javax.swing.JLabel lblBBDDHistorico;
    private javax.swing.JLabel lblDemanda;
    private javax.swing.JLabel lblDescripcion;
    private javax.swing.JLabel lblDescripcionAviso;
    private javax.swing.JLabel lblEsquema;
    private javax.swing.JLabel lblEsquemaHistorico;
    private javax.swing.JLabel lblGenerarHistorico;
    private javax.swing.JLabel lblModeloProyecto;
    private javax.swing.JLabel lblNombreTabla;
    private javax.swing.JLabel lblNotasAvisos;
    private javax.swing.JLabel lblPeticion;
    private javax.swing.JLabel lblSolicitadaPor;
    private javax.swing.JLabel lblSubModelo;
    private javax.swing.JLabel lblTipoOperacion;
    private javax.swing.JLabel lblUltimasPeticiones;
    private javax.swing.JScrollPane scpDescripcionAviso;
    private javax.swing.JScrollPane scrollPaneDescripcion;
    private javax.swing.JScrollPane scrollPaneTblNotas;
    private javax.swing.JScrollPane scrollPaneTblUltimasPeticiones;
    private javax.swing.JTable tblNotas;
    private javax.swing.JTable tblUltimasPeticiones;
    private javax.swing.JTextField txtBBDDHistorico;
    private javax.swing.JTextField txtDemanda;
    private javax.swing.JTextArea txtDescripcion;
    private javax.swing.JTextArea txtDescripcionAviso;
    private javax.swing.JTextField txtEsquema;
    private javax.swing.JTextField txtEsquemaHistorico;
    private javax.swing.JTextField txtModeloProyecto;
    private javax.swing.JTextField txtNombreTabla;
    private javax.swing.JTextField txtPeticion;
    private javax.swing.JTextField txtSolicitadaPor;
    private javax.swing.JTextField txtTipoOperacion;
    // End of variables declaration//GEN-END:variables

    @Getter
    @Setter
    private Aviso avisoSeleccionado;

    @Getter
    @Setter
    private Proceso procesoSeleccionado;

    @Getter
    @Setter
    private Procesado procesado;

    @Getter
    @Setter
    private List<TextoLinea> script;

    @Getter
    private PantallaProcesarScriptActionListener pantallaProcesarScriptActionListener;

    @Getter
    @Setter
    private List<BBDD> bbdds;

    public JButton getBtnProcesar() {
        return btnProcesar;
    }

    public JCheckBox getChkGenerarHistorico() {
        return chkGenerarHistorico;
    }

    public JComboBox<BBDD> getCmbBBDD() {
        return cmbBBDD;
    }

    public JComboBox<SubProyecto> getCmbSubmodelo() {
        return cmbSubModelo;
    }

    @Override
    public JTextField getTxtPeticion() {
        return txtPeticion;
    }

    public JTextField getTxtSolicitadaPor() {
        return txtSolicitadaPor;
    }

    public JTextField getTxtBBDDHistorico() {
        return txtBBDDHistorico;
    }

    public JTextField getTxtDemanda() {
        return txtDemanda;
    }

    public JTextArea getTxtDescripcion() {
        return txtDescripcion;
    }

    public JTextField getTxtEsquema() {
        return txtEsquema;
    }

    public JTextField getTxtEsquemaHistorico() {
        return txtEsquemaHistorico;
    }

    public JTable getTblNotas() {
        return tblNotas;
    }

    @Override
    public JButton getBtnLimpiar() {
        return btnLimpiar;
    }

    @Override
    protected void setupComponents() {
        initComponents();
    }

    @Override
    protected void initEvents() {
        pantallaProcesarScriptActionListener = new PantallaProcesarScriptActionListener(this);
        ListSelectionListener avisosSelectionListener = new AvisosTableListener(this);
        ListSelectionListener ultimasPeticionesSelectionListener = new UltimasPeticionesTableListener(this);
        ItemListener bbddItemListener = new ProcesarScriptBBDDItemListener(this);
        ItemListener subproyectoItemListener = new SubproyectoItemListener(this);

        btnModeloProyecto.addActionListener(pantallaProcesarScriptActionListener);
        btnCancelar.addActionListener(pantallaProcesarScriptActionListener);
        btnProcesar.addActionListener(pantallaProcesarScriptActionListener);
        btnLimpiar.addActionListener(pantallaProcesarScriptActionListener);
        btnVerProcesado.addActionListener(pantallaProcesarScriptActionListener);
        btnRecuperarUltimoProcesado.addActionListener(pantallaProcesarScriptActionListener);
        btnParametros.addActionListener(pantallaProcesarScriptActionListener);

        ListSelectionModel avisosRowSM = tblNotas.getSelectionModel();
        avisosRowSM.addListSelectionListener(avisosSelectionListener);

        ListSelectionModel ultimasPeticionesRowSM = tblUltimasPeticiones.getSelectionModel();
        ultimasPeticionesRowSM.addListSelectionListener(ultimasPeticionesSelectionListener);

        cmbBBDD.addItemListener(bbddItemListener);
        cmbSubModelo.addItemListener(subproyectoItemListener);

        tblNotas.getSelectionModel().addListSelectionListener(pantallaProcesarScriptActionListener);

        addOnLoadListener(pantallaProcesarScriptActionListener);
    }

    @SuppressWarnings("unchecked")
    @Override
    protected void initModels() {
        cmbSubModelo.setRenderer(new CmbSubProyectoRenderer());
        cmbBBDD.setRenderer(new CmbBBDDRenderer());

        Cabecera cabeceraNotas = new TablaNotasCabecera();
        MDSQLUIHelper.setTableModelRenderer(tblNotas, new ProcesarScriptNotaTableModel(cabeceraNotas), null);
        tblNotas.setDefaultRenderer(String.class, new NivelAvisosTableCellRenderer());

        Cabecera cabeceraUltimasPeticiones = new TablaUltimasPeticionesCabecera();
        MDSQLUIHelper.setTableModelRenderer(tblUltimasPeticiones, new ProcesarScriptUltimasPeticionesTableModel(cabeceraUltimasPeticiones), null);
    }

    @SuppressWarnings("unchecked")
    @Override
    protected void initialState() {
        chkGenerarHistorico.setEnabled(false);
        //Campos se solo lectura pero se puede copiar y pegar su contenido
        MDSQLUIHelper.setReadOnlyText(txtEsquema);
        MDSQLUIHelper.setReadOnlyText(txtEsquemaHistorico);
        MDSQLUIHelper.setReadOnlyText(txtBBDDHistorico);
        MDSQLUIHelper.setReadOnlyText(txtDescripcionAviso);
        MDSQLUIHelper.setReadOnlyText(txtNombreTabla);
        MDSQLUIHelper.setReadOnlyText(txtTipoOperacion);
    }

    @Override
    protected void setupLiterals() {
        setTitulo();
        setTexto(lblModeloProyecto, "lblModeloProyecto");
        setTexto(lblSubModelo, "lblSubModelo");
        setTexto(lblPeticion, "lblPeticion");
        setTexto(lblSolicitadaPor, "lblSolicitadaPor");
        setTexto(lblEsquema, "lblEsquema");
        setTexto(lblBBDD, "lblBBDD");
        setTexto(lblGenerarHistorico, "chkGenerarHistorico");
        setTexto(lblBBDDHistorico, "lblBBDDHistorico");
        setTexto(lblEsquemaHistorico, "lblEsquemaHistorico");
        setTexto(lblDescripcion, "lblDescripcion");
        setTexto(btnLimpiar, "btnLimpiar");
        setTexto(lblNotasAvisos, "lblNotasAvisos");
        setTexto(lblUltimasPeticiones, "lblUltimasPeticiones");
        setTexto(lblDemanda, "lblDemanda");
        setTexto(btnVerProcesado, "btnVerProcesado");
        setTexto(btnProcesar, "btnProcesar");
        setTexto(btnCancelar, "btnCancelar");
        setTexto(btnRecuperarUltimoProcesado, "btnRecuperarUltimoProcesado");
        setTexto(lblNombreTabla, "lblNombreTabla");
        setTexto(lblTipoOperacion, "lblTipoOperacion");
        setTexto(lblDescripcionAviso, "lblDescripcionAviso");
        setTexto(btnParametros, "btnParametros");
    }

    @Override
    public JTable getTblUltimasPeticiones() {
        return tblUltimasPeticiones;
    }

    @Override
    public JButton getBtnVerProcesado() {
        return btnVerProcesado;
    }

    @Override
    public JTextField getTxtModeloProyecto() {
        return txtModeloProyecto;
    }

    @Override
    public JButton getBtnCancelar() {
        return btnCancelar;
    }

    @Override
    public JButton getBtnModeloProyecto() {
        return btnModeloProyecto;
    }

    @Override
    public JComboBox<SubProyecto> getCmbSubModelo() {
        return cmbSubModelo;
    }

    public JButton getBtnRecuperarUltimoProcesado() {
        return btnRecuperarUltimoProcesado;
    }

    public JTextArea getTxtDescripcionAviso() {
        return txtDescripcionAviso;
    }

    public JTextField getTxtNombreTabla() {
        return txtNombreTabla;
    }

    public JTextField getTxtTipoOperacion() {
        return txtTipoOperacion;
    }

    public JButton getBtnParametros() {
        return btnParametros;
    }

}
