/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mdsql.ui;

import com.mdsql.ui.listener.PantallaSeleccionScriptReentranteListener;
import com.mdsql.ui.model.ParametroScriptReentranteTableModel;
import com.mdsql.ui.utils.MDSQLUIHelper;
import com.mdval.ui.utils.DialogSupport;
import com.mdval.ui.utils.FrameSupport;
import com.mdsql.bussiness.entities.CodigoDescripcion;
import com.mdsql.bussiness.entities.Session;
import com.mdsql.ui.model.cabeceras.TablaParametroScriptReentranteCabecera;
import com.mdsql.ui.renderer.CmbStringRenderer;
import com.mdsql.ui.renderer.ParametroScriptReentranteTableCellRenderer;
import com.mdsql.utils.MDSQLAppHelper;
import com.mdsql.utils.MDSQLConstants;
import com.mdval.ui.model.cabeceras.Cabecera;
import java.util.Map;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JTable;
import javax.swing.JTextArea;
import javax.swing.JTextField;

/**
 *
 * @author Luis-Enrique.Varona
 */
public class PantallaSeleccionScriptReentrante extends DialogSupport {

    // End of variables declaration                   
    public PantallaSeleccionScriptReentrante(FrameSupport parent, Boolean modal) {
        super(parent, modal);
    }

    public PantallaSeleccionScriptReentrante(FrameSupport parent, Boolean modal, Map<String, Object> params) {
        super(parent, modal, params);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblScriptCambio = new javax.swing.JLabel();
        btnScriptCambio = new javax.swing.JButton();
        txtScriptCambio = new javax.swing.JTextField();
        lblScriptCreacion = new javax.swing.JLabel();
        btnScriptCreacion = new javax.swing.JButton();
        txtScriptCreacion = new javax.swing.JTextField();
        lblScriptComentarios = new javax.swing.JLabel();
        btnScriptComentarios = new javax.swing.JButton();
        txtScriptComentarios = new javax.swing.JTextField();
        lblRutaSalida = new javax.swing.JLabel();
        btnRutaSalida = new javax.swing.JButton();
        txtRutaSalida = new javax.swing.JTextField();
        lblTipoOperacion = new javax.swing.JLabel();
        cmbTipoOperacion = new javax.swing.JComboBox<>();
        scpDescripcion = new javax.swing.JScrollPane();
        txtDescripcion = new javax.swing.JTextArea();
        lblNombreTabla = new javax.swing.JLabel();
        txtNombreTabla = new javax.swing.JTextField();
        scMantenimientoParametro = new javax.swing.JScrollPane();
        tblMantenimientoParametro = new javax.swing.JTable();
        lblAyuda = new javax.swing.JLabel();
        scpAyuda = new javax.swing.JScrollPane();
        txtAyuda = new javax.swing.JTextArea();
        btnLimpiar = new javax.swing.JButton();
        btnAceptar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Selección de script reentrante");

        lblScriptCambio.setText("Script de cambio");

        btnScriptCambio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/folder-open.png"))); // NOI18N

        txtScriptCambio.setEditable(false);

        lblScriptCreacion.setText("Script creación");

        btnScriptCreacion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/folder-open.png"))); // NOI18N

        txtScriptCreacion.setEditable(false);

        lblScriptComentarios.setText("Script comentarios");

        btnScriptComentarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/folder-open.png"))); // NOI18N

        txtScriptComentarios.setEditable(false);

        lblRutaSalida.setText("Ruta salida");

        btnRutaSalida.setIcon(new javax.swing.ImageIcon(getClass().getResource("/folder-open.png"))); // NOI18N

        txtRutaSalida.setEditable(false);

        lblTipoOperacion.setText("Tipo de operación");

        scpDescripcion.setEnabled(false);

        txtDescripcion.setEditable(false);
        txtDescripcion.setColumns(20);
        txtDescripcion.setRows(5);
        scpDescripcion.setViewportView(txtDescripcion);

        lblNombreTabla.setText("Nombre tabla");

        tblMantenimientoParametro.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Parámetro", "Valor"
            }
        ));
        tblMantenimientoParametro.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        scMantenimientoParametro.setViewportView(tblMantenimientoParametro);

        lblAyuda.setText("Ayuda");

        txtAyuda.setEditable(false);
        txtAyuda.setBackground(getBackground());
        txtAyuda.setColumns(20);
        txtAyuda.setRows(5);
        scpAyuda.setViewportView(txtAyuda);

        btnLimpiar.setText("Aceptar");

        btnAceptar.setText("Aceptar");

        btnCancelar.setText("Cancelar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblAyuda)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(scMantenimientoParametro)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(lblRutaSalida, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnRutaSalida, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtRutaSalida))
                            .addComponent(scpAyuda, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(lblScriptComentarios, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(lblScriptCreacion, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(lblScriptCambio, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(btnScriptCambio, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(btnScriptCreacion, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(btnScriptComentarios, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addComponent(lblNombreTabla, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblTipoOperacion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(6, 6, 6)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(scpDescripcion)
                                    .addComponent(txtScriptCreacion)
                                    .addComponent(txtScriptCambio)
                                    .addComponent(cmbTipoOperacion, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtNombreTabla)
                                    .addComponent(txtScriptComentarios)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 282, Short.MAX_VALUE)
                                .addComponent(btnLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(313, 313, 313)))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtScriptCambio, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnScriptCambio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblScriptCambio, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtScriptCreacion, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnScriptCreacion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblScriptCreacion, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtScriptComentarios, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnScriptComentarios, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblScriptComentarios, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtRutaSalida, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRutaSalida, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblRutaSalida, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cmbTipoOperacion, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTipoOperacion, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scpDescripcion, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombreTabla, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNombreTabla, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(scMantenimientoParametro, javax.swing.GroupLayout.DEFAULT_SIZE, 205, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblAyuda, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scpAyuda, javax.swing.GroupLayout.DEFAULT_SIZE, 274, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnRutaSalida;
    private javax.swing.JButton btnScriptCambio;
    private javax.swing.JButton btnScriptComentarios;
    private javax.swing.JButton btnScriptCreacion;
    private javax.swing.JComboBox<CodigoDescripcion> cmbTipoOperacion;
    private javax.swing.JLabel lblAyuda;
    private javax.swing.JLabel lblNombreTabla;
    private javax.swing.JLabel lblRutaSalida;
    private javax.swing.JLabel lblScriptCambio;
    private javax.swing.JLabel lblScriptComentarios;
    private javax.swing.JLabel lblScriptCreacion;
    private javax.swing.JLabel lblTipoOperacion;
    private javax.swing.JScrollPane scMantenimientoParametro;
    private javax.swing.JScrollPane scpAyuda;
    private javax.swing.JScrollPane scpDescripcion;
    private javax.swing.JTable tblMantenimientoParametro;
    private javax.swing.JTextArea txtAyuda;
    private javax.swing.JTextArea txtDescripcion;
    private javax.swing.JTextField txtNombreTabla;
    private javax.swing.JTextField txtRutaSalida;
    private javax.swing.JTextField txtScriptCambio;
    private javax.swing.JTextField txtScriptComentarios;
    private javax.swing.JTextField txtScriptCreacion;
    // End of variables declaration//GEN-END:variables

    @Override
    protected void setupComponents() {
        initComponents();
    }

    @Override
    protected void initEvents() {
        cmbTipoOperacion.setRenderer(new CmbStringRenderer());

        PantallaSeleccionScriptReentranteListener actionListener = new PantallaSeleccionScriptReentranteListener(this);

        btnLimpiar.addActionListener(actionListener);
        btnCancelar.addActionListener(actionListener);
        btnAceptar.addActionListener(actionListener);
        btnScriptCambio.addActionListener(actionListener);
        btnScriptComentarios.addActionListener(actionListener);
        btnScriptCreacion.addActionListener(actionListener);
        btnRutaSalida.addActionListener(actionListener);
        cmbTipoOperacion.addItemListener(actionListener);
        tblMantenimientoParametro.getSelectionModel().addListSelectionListener(actionListener);
        this.addOnLoadListener(actionListener);
    }

    @Override
    protected void setupLiterals() {
        setTitulo();
        setTexto(lblScriptCambio,"lblScriptCambio");
        setTexto(lblScriptCreacion,"lblScriptCreacion");
        setTexto(lblScriptComentarios,"lblScriptComentarios");
        setTexto(lblRutaSalida,"lblRutaSalida");
        setTexto(lblTipoOperacion,"lblTipoOperacion");
        setTexto(lblNombreTabla,"lblNombreTabla");
        setTexto(lblAyuda,"lblAyuda");
        setTexto(btnLimpiar,"btnLimpiar");
        setTexto(btnAceptar,"btnAceptar");
        setTexto(btnCancelar,"btnCancelar");
    }

    @Override
    protected void initModels() {
        Session session = (Session) MDSQLAppHelper.getGlobalProperty(MDSQLConstants.SESSION);
        boolean isEditableValue = session.getProceso() == null;
        Cabecera cabecera = new TablaParametroScriptReentranteCabecera();
        ParametroScriptReentranteTableModel tableModel = new ParametroScriptReentranteTableModel(cabecera, isEditableValue);
        ParametroScriptReentranteTableCellRenderer cellRenderer = new ParametroScriptReentranteTableCellRenderer(isEditableValue);
        MDSQLUIHelper.setTableModelRenderer(tblMantenimientoParametro, tableModel, cellRenderer);
    }

    @Override
    protected void initialState() {
        MDSQLUIHelper.setReadOnlyText(txtDescripcion);
    }

    public JTextField getTxtScriptCambio() {
        return txtScriptCambio;
    }

    public JTextField getTxtScriptComentarios() {
        return txtScriptComentarios;
    }

    public JTextField getTxtScriptCreacion() {
        return txtScriptCreacion;
    }

    public JTable getTblMantenimientoParametro() {
        return tblMantenimientoParametro;
    }

    public JComboBox<CodigoDescripcion> getCmbTipoOperacion() {
        return cmbTipoOperacion;
    }

    public JTextField getTxtNombreTabla() {
        return txtNombreTabla;
    }
    
    public JTextArea getTxtAyuda() {
        return txtAyuda;
    }

    public JTextArea getTxtDescripcion() {
        return txtDescripcion;
    }

    public JButton getBtnAceptar() {
        return btnAceptar;
    }

    public JButton getBtnCancelar() {
        return btnCancelar;
    }

    public JButton getBtnScriptCambio() {
        return btnScriptCambio;
    }

    public JButton getBtnScriptComentarios() {
        return btnScriptComentarios;
    }

    public JButton getBtnScriptCreacion() {
        return btnScriptCreacion;
    }

    public JButton getBtnRutaSalida() {
        return btnRutaSalida;
    }

    public JTextField getTxtRutaSalida() {
        return txtRutaSalida;
    }

    public JButton getBtnLimpiar() {
        return btnLimpiar;
    }
    
}
