/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mdsql.ui;

import com.mdsql.bussiness.entities.Proceso;
import com.mdsql.bussiness.entities.SubProyecto;
import com.mdsql.ui.listener.PantallaConsultaPeticionesListener;
import com.mdsql.ui.listener.tables.PantallaConsultaPeticionesTableListener;
import com.mdsql.ui.model.ConsultaPeticionesTableModel;
import com.mdsql.ui.model.SiNoOpcionalComboBoxModel;
import com.mdsql.ui.model.SubProyectoComboBoxModel;
import com.mdsql.ui.model.cabeceras.TablaConsultaPeticionesCabecera;
import com.mdsql.ui.renderer.CmbStringRenderer;
import com.mdsql.ui.utils.DialogSupportModelo;
import com.mdsql.ui.utils.MDSQLUIHelper;
import com.mdval.ui.model.cabeceras.Cabecera;
import com.mdval.ui.utils.FrameSupport;
import java.util.Map;
import javax.swing.JButton;
import javax.swing.JCheckBox;
import javax.swing.JComboBox;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.ListSelectionModel;
import javax.swing.event.ListSelectionListener;
import lombok.Getter;
import lombok.Setter;

/**
 *
 * @author LVARONA
 */
public class PantallaConsultaPeticiones extends DialogSupportModelo {

    @Getter
    @Setter
    private Proceso seleccionado;

    private PantallaConsultaPeticionesListener pantallaConsultaPeticionesListener;

    public PantallaConsultaPeticiones(FrameSupport parent, Boolean modal) {
        super(parent, modal);
    }

    public PantallaConsultaPeticiones(FrameSupport parent, Boolean modal, Map<String, Object> params) {
        super(parent, modal, params);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblModeloProyecto = new javax.swing.JLabel();
        txtModeloProyecto = new javax.swing.JTextField();
        btnModeloProyecto = new javax.swing.JButton();
        lblSubModelo = new javax.swing.JLabel();
        cmbSubModelo = new javax.swing.JComboBox<SubProyecto>();
        chkGenerado = new javax.swing.JCheckBox();
        chkEjecutado = new javax.swing.JCheckBox();
        chkCerrado = new javax.swing.JCheckBox();
        lblPeticion = new javax.swing.JLabel();
        txtPeticion = new javax.swing.JTextField();
        lblUsuario = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JTextField();
        lblProcesado = new javax.swing.JLabel();
        txtProcesado = new javax.swing.JTextField();
        chkEnEjecucion = new javax.swing.JCheckBox();
        chkRechazado = new javax.swing.JCheckBox();
        chkIncidencia = new javax.swing.JCheckBox();
        lblSolicitadaPor = new javax.swing.JLabel();
        txtSolicitadaPor = new javax.swing.JTextField();
        lblDesde = new javax.swing.JLabel();
        txtDesde = new javax.swing.JTextField();
        lblHasta = new javax.swing.JLabel();
        txtHasta = new javax.swing.JTextField();
        lblConErrores = new javax.swing.JLabel();
        cmbConErrores = new javax.swing.JComboBox<>();
        chkError = new javax.swing.JCheckBox();
        chkEntregado = new javax.swing.JCheckBox();
        chkExcluido = new javax.swing.JCheckBox();
        btnLimpiar = new javax.swing.JButton();
        btnBuscar = new javax.swing.JButton();
        scpPeticiones = new javax.swing.JScrollPane();
        tblPeticiones = new javax.swing.JTable();
        btnExcluir = new javax.swing.JButton();
        btnEntregar = new javax.swing.JButton();
        btnRechazar = new javax.swing.JButton();
        btnIncidencia = new javax.swing.JButton();
        btnCargarProcesado = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lblModeloProyecto.setText("Modelo o Proyecto");

        btnModeloProyecto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/loupe.png"))); // NOI18N

        lblSubModelo.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblSubModelo.setText("Submodelo");

        cmbSubModelo.setModel(new SubProyectoComboBoxModel());

        chkGenerado.setText("Generado");

        chkEjecutado.setText("Ejecutado");

        chkCerrado.setText("Cerrado");

        lblPeticion.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblPeticion.setText("Peticion");

        lblUsuario.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblUsuario.setText("Usuario");

        lblProcesado.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblProcesado.setText("Procesado");

        chkEnEjecucion.setText("En ejecución");

        chkRechazado.setText("Rechazado");

        chkIncidencia.setText("Incidencia");

        lblSolicitadaPor.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblSolicitadaPor.setText("Solicitada por");
        lblSolicitadaPor.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        lblDesde.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblDesde.setText("Desde");

        lblHasta.setText("Hasta");

        lblConErrores.setText("Con errores");

        cmbConErrores.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sí", "No" }));

        chkError.setText("Error");

        chkEntregado.setText("Entregado");

        chkExcluido.setText("Excluido");

        btnLimpiar.setText("Limpiar");

        btnBuscar.setText("Buscar");

        tblPeticiones.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Petición", "Estado", "Fecha", "Modelo", "Submodelo", "Solicitado", "Descripción", "Procesado", "Usuario"
            }
        ));
        scpPeticiones.setViewportView(tblPeticiones);

        btnExcluir.setText("Excluir");

        btnEntregar.setText("Entregar");

        btnRechazar.setText("Rechazar");

        btnIncidencia.setText("Incidencia");

        btnCargarProcesado.setText("Cargar Procesado");

        btnCancelar.setText("CANCELAR");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(scpPeticiones, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(457, 457, 457)
                            .addComponent(btnExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(btnEntregar, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(btnRechazar, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(btnIncidencia, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(btnCargarProcesado, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(0, 7, Short.MAX_VALUE))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblSolicitadaPor, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblModeloProyecto, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblPeticion, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtPeticion, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtSolicitadaPor, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(txtModeloProyecto, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(btnModeloProyecto, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGap(100, 100, 100)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                            .addComponent(lblUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(txtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(lblDesde, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(txtDesde, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGap(27, 27, 27)
                                    .addComponent(lblHasta, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(txtHasta, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(lblConErrores, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(cmbConErrores, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(lblProcesado, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(txtProcesado, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(lblSubModelo, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(cmbSubModelo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGap(100, 100, 100)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(chkGenerado, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(chkEnEjecucion, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(chkError, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(39, 39, 39)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(chkEntregado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(chkRechazado, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                                .addComponent(chkEjecutado, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE))
                            .addGap(39, 39, 39)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(chkCerrado, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(chkIncidencia, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(chkExcluido, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(7, 7, 7))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(btnModeloProyecto, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(txtModeloProyecto, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lblModeloProyecto)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(chkGenerado, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(chkEjecutado, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(chkCerrado, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(txtPeticion, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lblUsuario)
                                        .addComponent(txtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(chkEnEjecucion, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(chkRechazado, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(chkIncidencia, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(lblPeticion)))
                            .addComponent(txtProcesado, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtSolicitadaPor, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblSolicitadaPor)
                                .addComponent(lblDesde)
                                .addComponent(txtDesde, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lblHasta)
                                .addComponent(txtHasta, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblConErrores)
                                .addComponent(cmbConErrores, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(chkError, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(chkEntregado, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(chkExcluido, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblSubModelo)
                            .addComponent(cmbSubModelo, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(lblProcesado)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(scpPeticiones, javax.swing.GroupLayout.DEFAULT_SIZE, 467, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCargarProcesado, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEntregar, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRechazar, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnIncidencia, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnCargarProcesado;
    private javax.swing.JButton btnEntregar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnIncidencia;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnModeloProyecto;
    private javax.swing.JButton btnRechazar;
    private javax.swing.JCheckBox chkCerrado;
    private javax.swing.JCheckBox chkEjecutado;
    private javax.swing.JCheckBox chkEnEjecucion;
    private javax.swing.JCheckBox chkEntregado;
    private javax.swing.JCheckBox chkError;
    private javax.swing.JCheckBox chkExcluido;
    private javax.swing.JCheckBox chkGenerado;
    private javax.swing.JCheckBox chkIncidencia;
    private javax.swing.JCheckBox chkRechazado;
    private javax.swing.JComboBox<String> cmbConErrores;
    private javax.swing.JComboBox<SubProyecto> cmbSubModelo;
    private javax.swing.JLabel lblConErrores;
    private javax.swing.JLabel lblDesde;
    private javax.swing.JLabel lblHasta;
    private javax.swing.JLabel lblModeloProyecto;
    private javax.swing.JLabel lblPeticion;
    private javax.swing.JLabel lblProcesado;
    private javax.swing.JLabel lblSolicitadaPor;
    private javax.swing.JLabel lblSubModelo;
    private javax.swing.JLabel lblUsuario;
    private javax.swing.JScrollPane scpPeticiones;
    private javax.swing.JTable tblPeticiones;
    private javax.swing.JTextField txtDesde;
    private javax.swing.JTextField txtHasta;
    private javax.swing.JTextField txtModeloProyecto;
    private javax.swing.JTextField txtPeticion;
    private javax.swing.JTextField txtProcesado;
    private javax.swing.JTextField txtSolicitadaPor;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables

    @Override
    protected void initEvents() {
        pantallaConsultaPeticionesListener = new PantallaConsultaPeticionesListener(this);
        ListSelectionListener listSelectionListener = new PantallaConsultaPeticionesTableListener(this);

        btnBuscar.addActionListener(pantallaConsultaPeticionesListener);
        btnCargarProcesado.addActionListener(pantallaConsultaPeticionesListener);
        btnCancelar.addActionListener(pantallaConsultaPeticionesListener);

        btnExcluir.addActionListener(pantallaConsultaPeticionesListener);
        btnEntregar.addActionListener(pantallaConsultaPeticionesListener);
        btnRechazar.addActionListener(pantallaConsultaPeticionesListener);
        btnIncidencia.addActionListener(pantallaConsultaPeticionesListener);
        btnLimpiar.addActionListener(pantallaConsultaPeticionesListener);
        btnModeloProyecto.addActionListener(pantallaConsultaPeticionesListener);

        ListSelectionModel rowSM = tblPeticiones.getSelectionModel();
        rowSM.addListSelectionListener(listSelectionListener);
        
        addOnLoadListener(pantallaConsultaPeticionesListener);
    }

    @Override
    protected void initModels() {
        Cabecera cabecera = new TablaConsultaPeticionesCabecera();
        MDSQLUIHelper.setTableModelRenderer(tblPeticiones, new ConsultaPeticionesTableModel(cabecera), null);

        cmbConErrores.setModel(new SiNoOpcionalComboBoxModel());
        cmbConErrores.setRenderer(new CmbStringRenderer());
    }

    @Override
    protected void initialState() {
        //Los botones se deshabilitan en el Listener
        cmbConErrores.setSelectedIndex(0); // Todos
    }

    @Override
    protected void setupLiterals() {
        setTitulo();

        setTexto(lblModeloProyecto, "lblModeloProyecto");
        setTexto(lblSubModelo, "lblSubModelo");
        setTexto(lblPeticion, "lblPeticion");
        setTexto(lblSolicitadaPor, "lblSolicitadaPor");
        setTexto(lblUsuario, "lblUsuario");
        setTexto(lblDesde, "lblDesde");
        setTexto(lblHasta, "lblHasta");
        setTexto(btnBuscar, "btnBuscar");
        setTexto(btnLimpiar, "btnLimpiar");
        setTexto(btnCargarProcesado, "btnCargarProcesado");
        setTexto(btnCancelar, "btnCancelar");

        setTexto(chkGenerado, "chkGenerado");
        setTexto(chkEjecutado, "chkEjecutado");
        setTexto(chkCerrado, "chkCerrado");
        setTexto(chkEnEjecucion, "chkEnEjecucion");
        setTexto(chkRechazado, "chkRechazado");
        setTexto(chkIncidencia, "chkIncidencia");
        setTexto(lblConErrores, "lblConErrores");
        setTexto(chkError, "chkError");
        setTexto(chkEntregado, "chkEntregado");
        setTexto(chkExcluido, "chkExcluido");
        setTexto(btnExcluir, "btnExcluir");
        setTexto(btnEntregar, "btnEntregar");
        setTexto(btnRechazar, "btnRechazar");
        setTexto(btnIncidencia, "btnIncidencia");
    }

    @Override
    protected void setupComponents() {
        initComponents();
    }

    public JButton getBtnBuscar() {
        return btnBuscar;
    }

    @Override
    public JButton getBtnCancelar() {
        return btnCancelar;
    }

    public JButton getBtnCargarProcesado() {
        return btnCargarProcesado;
    }

    public JButton getBtnEntregar() {
        return btnEntregar;
    }

    public JButton getBtnExcluir() {
        return btnExcluir;
    }

    public JButton getBtnIncidencia() {
        return btnIncidencia;
    }

    @Override
    public JButton getBtnModeloProyecto() {
        return btnModeloProyecto;
    }

    public JButton getBtnRechazar() {
        return btnRechazar;
    }

    public JCheckBox getChkCerrado() {
        return chkCerrado;
    }

    public JCheckBox getChkEjecutado() {
        return chkEjecutado;
    }

    public JCheckBox getChkEnEjecucion() {
        return chkEnEjecucion;
    }

    public JCheckBox getChkEntregado() {
        return chkEntregado;
    }

    public JCheckBox getChkError() {
        return chkError;
    }

    public JCheckBox getChkExcluido() {
        return chkExcluido;
    }

    public JCheckBox getChkGenerado() {
        return chkGenerado;
    }

    public JCheckBox getChkIncidencia() {
        return chkIncidencia;
    }

    public JCheckBox getChkRechazado() {
        return chkRechazado;
    }

    public JComboBox<String> getCmbConErrores() {
        return cmbConErrores;
    }

    @Override
    public JComboBox<SubProyecto> getCmbSubModelo() {
        return cmbSubModelo;
    }

    public JTable getTblPeticiones() {
        return tblPeticiones;
    }

    public JTextField getTxtDesde() {
        return txtDesde;
    }

    public JTextField getTxtHasta() {
        return txtHasta;
    }

    @Override
    public JTextField getTxtModeloProyecto() {
        return txtModeloProyecto;
    }

    public JTextField getTxtPeticion() {
        return txtPeticion;
    }

    public JTextField getTxtProcesado() {
        return txtProcesado;
    }

    public JTextField getTxtSolicitadaPor() {
        return txtSolicitadaPor;
    }

    public JTextField getTxtUsuario() {
        return txtUsuario;
    }

    @Override
    public JButton getBtnLimpiar() {
        return btnLimpiar;
    }

}
