package com.mdsql.ui;

import com.mdsql.ui.listener.PantallaScriptComentariosListener;
import com.mdsql.ui.model.ComentarioReentranteTableModel;
import com.mdsql.ui.model.cabeceras.TablaComentarioReentranteCabecera;
import com.mdsql.ui.renderer.ComentarioReentranteTableCellRenderer;
import com.mdsql.ui.utils.MDSQLUIHelper;
import com.mdval.ui.model.cabeceras.Cabecera;
import com.mdval.ui.utils.DialogSupport;
import com.mdval.ui.utils.FrameSupport;
import java.util.Map;
import javax.swing.JButton;
import javax.swing.JTable;
import javax.swing.JTextField;

/**
 *
 * @author LVARONA
 */
public class PantallaScriptComentarios extends DialogSupport {

    public PantallaScriptComentarios(FrameSupport parent, Boolean modal) {
        super(parent, modal);
    }

    public PantallaScriptComentarios(FrameSupport parent, Boolean modal, Map<String, Object> params) {
        super(parent, modal, params);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblCSV = new javax.swing.JLabel();
        btnCSV = new javax.swing.JButton();
        txtCSV = new javax.swing.JTextField();
        lblTabla = new javax.swing.JLabel();
        txtTabla = new javax.swing.JTextField();
        lblCastellano = new javax.swing.JLabel();
        txtCastellano = new javax.swing.JTextField();
        lblIngles = new javax.swing.JLabel();
        txtIngles = new javax.swing.JTextField();
        btnLimpiar = new javax.swing.JButton();
        btnProcesar = new javax.swing.JButton();
        lblAyuda = new javax.swing.JLabel();
        scpComentario = new javax.swing.JScrollPane();
        tblComentario = new javax.swing.JTable();
        btnPersonalizar = new javax.swing.JButton();
        btnUtilizarGenerico = new javax.swing.JButton();
        btnGenerar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lblCSV.setText("CSV");

        btnCSV.setIcon(new javax.swing.ImageIcon(getClass().getResource("/folder-open.png"))); // NOI18N
        btnCSV.setMaximumSize(new java.awt.Dimension(49, 25));
        btnCSV.setMinimumSize(new java.awt.Dimension(49, 25));

        txtCSV.setEditable(false);

        lblTabla.setText("Tabla");

        lblCastellano.setText("Castellano");

        lblIngles.setText("Inglés");

        btnLimpiar.setText("Limpiar");

        btnProcesar.setLabel("Procesar");

        lblAyuda.setText("OK - El comentario en la plantilla coincide con el genérico, NOK - El comentario en la plantilla NO coincide con el genérico,  NEW - No existe comentario genérico para el campo. Se creará como genérico, PER - Comentario Personalizado");

        tblComentario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Campo", "Idioma", "Tipo", "RDO", "Plantilla", "Definición Genérica"
            }
        ));
        scpComentario.setViewportView(tblComentario);

        btnPersonalizar.setText("Personalizar");

        btnUtilizarGenerico.setText("Utilizar Genérico");

        btnGenerar.setText("GENERAR");

        btnCancelar.setText("CANCELAR");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblCSV)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCSV, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCSV)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblTabla)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtTabla))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblCastellano, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblIngles, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtIngles)
                            .addComponent(txtCastellano)))
                    .addComponent(lblAyuda, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(scpComentario))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(188, Short.MAX_VALUE)
                .addComponent(btnPersonalizar, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55)
                .addComponent(btnUtilizarGenerico, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55)
                .addComponent(btnGenerar, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55)
                .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(334, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(btnProcesar, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblCSV, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnCSV, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtCSV, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblTabla, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtTabla, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCastellano, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCastellano, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblIngles, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtIngles, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnProcesar, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblAyuda, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(scpComentario, javax.swing.GroupLayout.DEFAULT_SIZE, 371, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnPersonalizar, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnUtilizarGenerico, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGenerar, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCSV;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnGenerar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnPersonalizar;
    private javax.swing.JButton btnProcesar;
    private javax.swing.JButton btnUtilizarGenerico;
    private javax.swing.JLabel lblAyuda;
    private javax.swing.JLabel lblCSV;
    private javax.swing.JLabel lblCastellano;
    private javax.swing.JLabel lblIngles;
    private javax.swing.JLabel lblTabla;
    private javax.swing.JScrollPane scpComentario;
    private javax.swing.JTable tblComentario;
    private javax.swing.JTextField txtCSV;
    private javax.swing.JTextField txtCastellano;
    private javax.swing.JTextField txtIngles;
    private javax.swing.JTextField txtTabla;
    // End of variables declaration//GEN-END:variables

    @Override
    protected void setupComponents() {
        initComponents();
    }

    @Override
    protected void initEvents() {
        PantallaScriptComentariosListener localListener = new PantallaScriptComentariosListener(this);
        btnCSV.addActionListener(localListener);
        btnLimpiar.addActionListener(localListener);
        btnProcesar.addActionListener(localListener);
        btnPersonalizar.addActionListener(localListener);
        btnUtilizarGenerico.addActionListener(localListener);
        btnGenerar.addActionListener(localListener);
        btnCancelar.addActionListener(localListener);
        tblComentario.getSelectionModel().addListSelectionListener(localListener);
    }

    @Override
    protected void setupLiterals() {
        setTitulo();
        setTexto(lblCSV, "lblCSV");
        setTexto(lblTabla, "lblTabla");
        setTexto(lblCastellano, "lblCastellano");
        setTexto(lblIngles, "lblIngles");
        setTexto(btnLimpiar, "btnLimpiar");
        setTexto(btnProcesar, "btnProcesar");
        setTexto(lblAyuda, "lblAyuda");
        setTexto(btnPersonalizar, "btnPersonalizar");
        setTexto(btnUtilizarGenerico, "btnUtilizarGenerico");
        setTexto(btnGenerar, "btnGenerar");
        setTexto(btnCancelar, "btnCancelar");
    }

    @Override
    protected void initModels() {
        Cabecera cabecera = new TablaComentarioReentranteCabecera();
        ComentarioReentranteTableModel tableModel= new ComentarioReentranteTableModel(cabecera);
        MDSQLUIHelper.setTableModelRenderer(tblComentario, tableModel, new ComentarioReentranteTableCellRenderer());
    }

    @Override
    protected void initialState() {
        btnPersonalizar.setEnabled(false);
        btnUtilizarGenerico.setEnabled(false);
        btnGenerar.setEnabled(false);
    }

    public JButton getBtnCSV() {
        return btnCSV;
    }

    public JButton getBtnCancelar() {
        return btnCancelar;
    }

    public JButton getBtnGenerar() {
        return btnGenerar;
    }

    public JButton getBtnPersonalizar() {
        return btnPersonalizar;
    }

    public JButton getBtnProcesar() {
        return btnProcesar;
    }

    public JButton getBtnUtilizarGenerico() {
        return btnUtilizarGenerico;
    }

    public JTable getTblComentario() {
        return tblComentario;
    }

    public JTextField getTxtCSV() {
        return txtCSV;
    }

    public JTextField getTxtCastellano() {
        return txtCastellano;
    }

    public JTextField getTxtIngles() {
        return txtIngles;
    }

    public JTextField getTxtTabla() {
        return txtTabla;
    }

    public JButton getBtnLimpiar() {
        return btnLimpiar;
    }
    
}
