package com.mdsql.ui;

import com.mdsql.bussiness.entities.ScriptPeticion;
import com.mdsql.ui.listener.PantallaVerScriptsPeticionListener;
import com.mdsql.ui.model.ScriptsPeticionTableModel;
import com.mdsql.ui.model.cabeceras.TablaScriptsPeticionCabecera;
import com.mdsql.ui.utils.MDSQLUIHelper;
import com.mdval.ui.model.cabeceras.Cabecera;
import com.mdval.ui.utils.DialogSupport;
import com.mdval.ui.utils.FrameSupport;
import java.util.Map;
import javax.swing.JButton;
import javax.swing.JTable;
import javax.swing.JTextField;
import lombok.Getter;
import lombok.Setter;

/**
 *
 * @author LVARONA
 */
public class PantallaVerScriptsPeticion extends DialogSupport {
    
    @Getter
    @Setter
    private ScriptPeticion seleccionado;

    // End of variables declaration                   
    public PantallaVerScriptsPeticion(FrameSupport parent, Boolean modal) {
        super(parent, modal);
    }

    public PantallaVerScriptsPeticion(FrameSupport parent, Boolean modal, Map<String, Object> params) {
        super(parent, modal, params);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblPeticion = new javax.swing.JLabel();
        txtPeticion = new javax.swing.JTextField();
        scpScripts = new javax.swing.JScrollPane();
        tblScripts = new javax.swing.JTable();
        btnCambiarNombre = new javax.swing.JButton();
        btnDetalleScript = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lblPeticion.setText("Petición");

        txtPeticion.setEditable(false);
        txtPeticion.setToolTipText("");

        tblScripts.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Tabla/Procesado", "Nombre Script", "Estado", "Fecha", "Usuario"
            }
        ));
        scpScripts.setViewportView(tblScripts);

        btnCambiarNombre.setText("Cambiar Nombre");

        btnDetalleScript.setText("Detalle Script");

        btnCancelar.setText("CANCELAR");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(scpScripts, javax.swing.GroupLayout.DEFAULT_SIZE, 972, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblPeticion)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtPeticion, javax.swing.GroupLayout.DEFAULT_SIZE, 305, Short.MAX_VALUE)
                        .addGap(618, 618, 618))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 421, Short.MAX_VALUE)
                        .addComponent(btnCambiarNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(54, 54, 54)
                        .addComponent(btnDetalleScript, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(47, 47, 47)
                        .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPeticion, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPeticion, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(scpScripts, javax.swing.GroupLayout.DEFAULT_SIZE, 357, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCambiarNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDetalleScript, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCambiarNombre;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnDetalleScript;
    private javax.swing.JLabel lblPeticion;
    private javax.swing.JScrollPane scpScripts;
    private javax.swing.JTable tblScripts;
    private javax.swing.JTextField txtPeticion;
    // End of variables declaration//GEN-END:variables

    @Override
    protected void setupComponents() {
        initComponents();
    }

    @Override
    protected void initEvents() {
        PantallaVerScriptsPeticionListener actionListener = new PantallaVerScriptsPeticionListener(this);
        btnCambiarNombre.addActionListener(actionListener);
        btnDetalleScript.addActionListener(actionListener);
        btnCancelar.addActionListener(actionListener);
        // Al seleccionar un elemento de la tabla se deben habilitar los botones
        tblScripts.getSelectionModel().addListSelectionListener(actionListener);
        addOnLoadListener(actionListener);
    }

    @Override
    protected void setupLiterals() {
        setTitulo();
        setTexto(btnCambiarNombre, "btnCambiarNombre");
        setTexto(btnCancelar, "btnCancelar");
        setTexto(btnDetalleScript, "btnDetalleScript");
        setTexto(lblPeticion, "lblPeticion");
    }

    @Override
    protected void initModels() {
        Cabecera cabecera = new TablaScriptsPeticionCabecera();
        MDSQLUIHelper.setTableModelRenderer(tblScripts, new ScriptsPeticionTableModel(cabecera), null);        
    }

    @Override
    protected void initialState() {
        btnCambiarNombre.setEnabled(false);
        btnDetalleScript.setEnabled(false);
    }

    public JButton getBtnCambiarNombre() {
        return btnCambiarNombre;
    }

    public JButton getBtnCancelar() {
        return btnCancelar;
    }

    public JButton getBtnDetalleScript() {
        return btnDetalleScript;
    }

    public JTable getTblScripts() {
        return tblScripts;
    }

    public JTextField getTxtPeticion() {
        return txtPeticion;
    }
    
    
}
