package com.mdsql.ui;

import com.mdsql.ui.listener.PantallaConsultaMovimientosProcesadoListener;
import com.mdsql.ui.model.MovimientosProcesadoTableModel;
import com.mdsql.ui.model.cabeceras.TablaMovimientosProcesadoCabecera;
import com.mdsql.ui.utils.MDSQLUIHelper;
import com.mdval.ui.model.cabeceras.Cabecera;
import com.mdval.ui.utils.DialogSupport;
import com.mdval.ui.utils.FrameSupport;
import java.util.Map;
import javax.swing.JButton;
import javax.swing.JTable;
import javax.swing.JTextArea;
import javax.swing.ListSelectionModel;

/**
 *
 * @author LVARONA
 */
public class PantallaConsultaMovimientosProcesado extends DialogSupport {

    public PantallaConsultaMovimientosProcesado(FrameSupport parent, Boolean modal) {
        super(parent, modal);
    }

    public PantallaConsultaMovimientosProcesado(FrameSupport parent, Boolean modal, Map<String, Object> params) {
        super(parent, modal, params);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scpMovimiento = new javax.swing.JScrollPane();
        tblMovimiento = new javax.swing.JTable();
        lblDescripcion = new javax.swing.JLabel();
        scpDescripcion = new javax.swing.JScrollPane();
        txtDescripcion = new javax.swing.JTextArea();
        btnCerrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        tblMovimiento.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Fecha", "Cambio", "Valor", "Usuario"
            }
        ));
        scpMovimiento.setViewportView(tblMovimiento);

        lblDescripcion.setText("Descripcion");

        txtDescripcion.setColumns(20);
        txtDescripcion.setRows(5);
        scpDescripcion.setViewportView(txtDescripcion);

        btnCerrar.setText("Cerrar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(scpMovimiento)
                    .addComponent(scpDescripcion)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(375, Short.MAX_VALUE)
                .addComponent(btnCerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(416, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scpMovimiento, javax.swing.GroupLayout.DEFAULT_SIZE, 162, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scpDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnCerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCerrar;
    private javax.swing.JLabel lblDescripcion;
    private javax.swing.JScrollPane scpDescripcion;
    private javax.swing.JScrollPane scpMovimiento;
    private javax.swing.JTable tblMovimiento;
    private javax.swing.JTextArea txtDescripcion;
    // End of variables declaration//GEN-END:variables

    @Override
    protected void setupComponents() {
        initComponents();
    }

    @Override
    protected void initEvents() {
        PantallaConsultaMovimientosProcesadoListener listener = new PantallaConsultaMovimientosProcesadoListener(this);
        ListSelectionModel scriptsRowSM = tblMovimiento.getSelectionModel();
        scriptsRowSM.addListSelectionListener(listener);
        btnCerrar.addActionListener(listener);
        this.addOnLoadListener(listener);        
    }

    @Override
    protected void setupLiterals() {
        setTitulo();
        setTexto(lblDescripcion, "lblDescripcion");
        setTexto(btnCerrar, "btnCerrar");
    }

    @Override
    protected void initModels() {
        Cabecera cabecera = new TablaMovimientosProcesadoCabecera();
        MDSQLUIHelper.setTableModelRenderer(tblMovimiento, new MovimientosProcesadoTableModel(cabecera), null);
    }

    @Override
    protected void initialState() {
        MDSQLUIHelper.setReadOnlyText(txtDescripcion);
    }

    public JTable getTblMovimiento() {
        return tblMovimiento;
    }

    public JTextArea getTxtDescripcion() {
        return txtDescripcion;
    }

    public JButton getBtnCerrar() {
        return btnCerrar;
    }
    
}
