/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mdsql.ui;

import com.mdsql.bussiness.entities.CodigoDescripcion;
import com.mdsql.bussiness.entities.ValidacionProgramada;
import com.mdsql.ui.listener.PantallaMantenimientoValidacionesProgramadasListener;
import com.mdsql.ui.listener.window.PantallaMantenimientoValidacionesProgramadasWindowListener;
import com.mdsql.ui.model.CodigoDescripcionComboBoxModel;
import com.mdsql.ui.model.ValidacionesProgramadasTableModel;
import com.mdsql.ui.model.cabeceras.TablaValidacionesProgramadasCabecera;
import com.mdsql.ui.renderer.CmbCodigoDescripcionRenderer;
import com.mdsql.ui.utils.DialogSupportModelo;
import com.mdsql.ui.utils.MDSQLUIHelper;
import com.mdval.ui.model.cabeceras.Cabecera;
import com.mdval.ui.utils.FrameSupport;
import java.util.Map;
import javax.swing.JButton;
import javax.swing.JCheckBox;
import javax.swing.JComboBox;
import javax.swing.JTable;
import javax.swing.JTextArea;
import javax.swing.JTextField;
import lombok.Getter;
import lombok.Setter;

/**
 *
 * @author Luis-Enrique.Varona FASE III - 3.3-Mantenimiento validaciones
 * programadas
 */
public class PantallaMantenimientoValidacionesProgramadas extends DialogSupportModelo {

    @Getter
    @Setter
    private boolean cambiosPendientes = false;

    /**
     *
     * @param parent
     * @param modal
     */
    public PantallaMantenimientoValidacionesProgramadas(FrameSupport parent, Boolean modal) {
        super(parent, modal);
    }

    public PantallaMantenimientoValidacionesProgramadas(FrameSupport parent, Boolean modal, Map<String, Object> params) {
        super(parent, modal, params);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblProcedimiento = new javax.swing.JLabel();
        cmbProcedimiento = new javax.swing.JComboBox<>();
        lblDescripcion = new javax.swing.JLabel();
        scpDescripcion = new javax.swing.JScrollPane();
        txtDescripcion = new javax.swing.JTextArea();
        chkHabilitada = new javax.swing.JCheckBox();
        lblModeloProyecto = new javax.swing.JLabel();
        txtModeloProyecto = new javax.swing.JTextField();
        btnModeloProyecto = new javax.swing.JButton();
        txtModeloProyectoDescrip = new javax.swing.JTextField();
        lblAccion = new javax.swing.JLabel();
        cmbAccion = new javax.swing.JComboBox<>();
        btnIncluirModificar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        scpValidacion = new javax.swing.JScrollPane();
        tblValidacion = new javax.swing.JTable();
        btnGuardar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);

        lblProcedimiento.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblProcedimiento.setText("Procedimiento");

        lblDescripcion.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblDescripcion.setText("Descripción");

        txtDescripcion.setColumns(20);
        txtDescripcion.setRows(5);
        scpDescripcion.setViewportView(txtDescripcion);

        chkHabilitada.setText("Habilitada   ");
        chkHabilitada.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        chkHabilitada.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        lblModeloProyecto.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblModeloProyecto.setText("Modelo o Proyecto");

        txtModeloProyecto.setMinimumSize(new java.awt.Dimension(150, 24));
        txtModeloProyecto.setName(""); // NOI18N
        txtModeloProyecto.setPreferredSize(new java.awt.Dimension(150, 24));

        btnModeloProyecto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/loupe.png"))); // NOI18N

        txtModeloProyectoDescrip.setEditable(false);
        txtModeloProyectoDescrip.setMinimumSize(new java.awt.Dimension(470, 24));
        txtModeloProyectoDescrip.setName(""); // NOI18N
        txtModeloProyectoDescrip.setPreferredSize(new java.awt.Dimension(470, 24));

        lblAccion.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblAccion.setText("Acción");
        lblAccion.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        cmbAccion.setModel(new CodigoDescripcionComboBoxModel());
        cmbAccion.setMinimumSize(new java.awt.Dimension(170, 24));
        cmbAccion.setName(""); // NOI18N
        cmbAccion.setPreferredSize(new java.awt.Dimension(170, 24));

        btnIncluirModificar.setText("Incluir/Modificar");

        btnEliminar.setText("Eliminar");

        tblValidacion.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Modelo", "Descripción", "Acción", "Habilitada", "Fecha", "Usuario"
            }
        ));
        scpValidacion.setViewportView(tblValidacion);

        btnGuardar.setText("Modificación");

        btnCancelar.setText("CANCELAR");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblProcedimiento, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(scpDescripcion)
                                .addGap(54, 54, 54)
                                .addComponent(chkHabilitada, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cmbProcedimiento, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(527, 527, 527)))
                        .addGap(8, 8, 8))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(scpValidacion, javax.swing.GroupLayout.DEFAULT_SIZE, 1147, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblModeloProyecto, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtModeloProyecto, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnModeloProyecto, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtModeloProyectoDescrip, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblAccion, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cmbAccion, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(10, 10, 10))))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnIncluirModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(46, 46, 46)
                        .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbProcedimiento, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblProcedimiento, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chkHabilitada, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(scpDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnModeloProyecto, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblModeloProyecto, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtModeloProyecto, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtModeloProyectoDescrip, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblAccion, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cmbAccion, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnIncluirModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(scpValidacion, javax.swing.GroupLayout.DEFAULT_SIZE, 389, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        btnEliminar.getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnIncluirModificar;
    private javax.swing.JButton btnModeloProyecto;
    private javax.swing.JCheckBox chkHabilitada;
    private javax.swing.JComboBox<CodigoDescripcion> cmbAccion;
    private javax.swing.JComboBox<ValidacionProgramada> cmbProcedimiento;
    private javax.swing.JLabel lblAccion;
    private javax.swing.JLabel lblDescripcion;
    private javax.swing.JLabel lblModeloProyecto;
    private javax.swing.JLabel lblProcedimiento;
    private javax.swing.JScrollPane scpDescripcion;
    private javax.swing.JScrollPane scpValidacion;
    private javax.swing.JTable tblValidacion;
    private javax.swing.JTextArea txtDescripcion;
    private javax.swing.JTextField txtModeloProyecto;
    private javax.swing.JTextField txtModeloProyectoDescrip;
    // End of variables declaration//GEN-END:variables
    @Override
    protected void setupComponents() {
        initComponents();
    }

    @Override
    protected void initEvents() {
        PantallaMantenimientoValidacionesProgramadasListener localFormListener = new PantallaMantenimientoValidacionesProgramadasListener(this);
        btnModeloProyecto.addActionListener(localFormListener);
        btnIncluirModificar.addActionListener(localFormListener);
        btnEliminar.addActionListener(localFormListener);
        btnGuardar.addActionListener(localFormListener);
        btnCancelar.addActionListener(localFormListener);

        tblValidacion.getSelectionModel().addListSelectionListener(localFormListener);

        cmbProcedimiento.addItemListener(localFormListener);

        //Tratar el evento al salir de la pantalla
        addWindowListener(new PantallaMantenimientoValidacionesProgramadasWindowListener(this));

        formListener = localFormListener;
        addOnLoadListener(formListener);
    }

    @Override
    protected void setupLiterals() {
        setTitulo();
        setTexto(lblProcedimiento, "lblProcedimiento");
        setTexto(lblDescripcion, "lblDescripcion");
        setTexto(chkHabilitada, "chkHabilitada");
        setTexto(lblModeloProyecto, "lblModeloProyecto");
        setTexto(lblAccion, "lblAccion");
        setTexto(btnIncluirModificar, "btnIncluirModificar");
        setTexto(btnEliminar, "btnEliminar");
        setTexto(btnGuardar, "btnGuardar");
        setTexto(btnCancelar, "btnCancelar");
    }

    @Override
    protected void initModels() {
        Cabecera cabecera = new TablaValidacionesProgramadasCabecera();
        MDSQLUIHelper.setTableModelRenderer(tblValidacion, new ValidacionesProgramadasTableModel(cabecera), null);

        cmbAccion.setRenderer(new CmbCodigoDescripcionRenderer());
    }

    @Override
    protected void initialState() {
        MDSQLUIHelper.setReadOnlyText(txtDescripcion);
        MDSQLUIHelper.setReadOnlyText(txtModeloProyectoDescrip);

        // Trataremos el cierre de la pantalla en el WindowListener
        setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);
    }

    public JButton getBtnIncluirModificar() {
        return btnIncluirModificar;
    }

    @Override
    public JButton getBtnCancelar() {
        return btnCancelar;
    }

    public JButton getBtnGuardar() {
        return btnGuardar;
    }

    @Override
    public JButton getBtnModeloProyecto() {
        return btnModeloProyecto;
    }

    public JTable getTblValidacion() {
        return tblValidacion;
    }

    @Override
    public JTextField getTxtModeloProyecto() {
        return txtModeloProyecto;
    }

    public JComboBox<CodigoDescripcion> getCmbAccion() {
        return cmbAccion;
    }

    @Override
    public JButton getBtnLimpiar() {
        return btnEliminar;
    }

    public JCheckBox getChkHabilitada() {
        return chkHabilitada;
    }

    @Override
    public JTextField getTxtModeloProyectoDescrip() {
        return txtModeloProyectoDescrip;
    }

    public JButton getBtnEliminar() {
        return btnEliminar;
    }

    public JComboBox<ValidacionProgramada> getCmbProcedimiento() {
        return cmbProcedimiento;
    }

    public JTextArea getTxtDescripcion() {
        return txtDescripcion;
    }

    /**
     * Se ejecuta al salir por la X (WindowsListener) o al presionar cancelar
     */
    public void cerrarVentana() {
        if (cambiosPendientes && !MDSQLUIHelper.confirmAction(this, "confirmacion.salir.validaciones.programadas")) {
            return;
        }
        dispose();
    }
}
