/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mdsql.ui;

import com.mdsql.bussiness.entities.Aviso;
import com.mdsql.bussiness.entities.Modelo;
import com.mdsql.bussiness.entities.Proceso;
import com.mdsql.bussiness.entities.SubProyecto;
import com.mdsql.ui.listener.PantallaProcesadoEnCursoActionListener;
import com.mdsql.ui.listener.tables.UltimasPeticionesTableListener;
import com.mdsql.ui.model.ProcesarScriptNotaTableModel;
import com.mdsql.ui.model.ProcesarScriptUltimasPeticionesTableModel;
import com.mdsql.ui.model.cabeceras.TablaNotasCabecera;
import com.mdsql.ui.model.cabeceras.TablaUltimasPeticionesCabecera;
import com.mdsql.ui.renderer.NivelAvisosTableCellRenderer;
import com.mdsql.ui.utils.DialogSupportModelo;
import com.mdsql.ui.utils.MDSQLUIHelper;
import com.mdsql.utils.MDSQLConstants.Procesado;
import com.mdval.ui.model.cabeceras.Cabecera;
import com.mdval.ui.utils.FrameSupport;
import java.util.Map;
import java.util.Objects;
import javax.swing.JButton;
import javax.swing.JCheckBox;
import javax.swing.JTable;
import javax.swing.JTextArea;
import javax.swing.JTextField;
import javax.swing.ListSelectionModel;
import javax.swing.event.ListSelectionListener;
import lombok.Getter;
import lombok.Setter;

/**
 *
 * @author LVARONA
 */
public class PantallaProcesadoEnCurso extends DialogSupportModelo implements PantallaProcesar {

    @Getter
    @Setter
    private Modelo modeloSeleccionado;

    @Getter
    @Setter
    private SubProyecto subproyectoSeleccionado;

    @Getter
    @Setter
    private Aviso avisoSeleccionado;

    @Getter
    @Setter
    private Proceso procesoSeleccionado;

    @Getter
    @Setter
    private Procesado procesado;

    /**
     * @param parent
     * @param modal
     */
    public PantallaProcesadoEnCurso(FrameSupport parent, Boolean modal) {
        super(parent, modal);
    }

    /**
     * Creates new form
     *
     * @param parent
     * @param modal
     * @param params
     */
    public PantallaProcesadoEnCurso(FrameSupport parent, Boolean modal, Map<String, Object> params) {
        super(parent, modal, params);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblModeloProyecto = new javax.swing.JLabel();
        txtModeloProyecto = new javax.swing.JTextField();
        btnModeloProyecto = new javax.swing.JButton();
        lblSubModelo = new javax.swing.JLabel();
        txtSubModelo = new javax.swing.JTextField();
        lblPeticion = new javax.swing.JLabel();
        txtPeticion = new javax.swing.JTextField();
        lblSolicitadaPor = new javax.swing.JLabel();
        txtSolicitadaPor = new javax.swing.JTextField();
        lblEsquema = new javax.swing.JLabel();
        txtEsquema = new javax.swing.JTextField();
        lblBBDD = new javax.swing.JLabel();
        txtBBDD = new javax.swing.JTextField();
        lblGenerarHistorico = new javax.swing.JLabel();
        chkGenerarHistorico = new javax.swing.JCheckBox();
        lblBBDDHistorico = new javax.swing.JLabel();
        txtBBDDHistorico = new javax.swing.JTextField();
        lblEsquemaHistorico = new javax.swing.JLabel();
        txtEsquemaHistorico = new javax.swing.JTextField();
        lblDemanda = new javax.swing.JLabel();
        txtDemanda = new javax.swing.JTextField();
        lblDescripcion = new javax.swing.JLabel();
        scpDescripcion = new javax.swing.JScrollPane();
        txtDescripcion = new javax.swing.JTextArea();
        btnLimpiar = new javax.swing.JButton();
        lblNotasAvisos = new javax.swing.JLabel();
        scpNotas = new javax.swing.JScrollPane();
        tblNotas = new javax.swing.JTable();
        lblUltimasPeticiones = new javax.swing.JLabel();
        scpUltimasPeticiones = new javax.swing.JScrollPane();
        tblUltimasPeticiones = new javax.swing.JTable();
        btnVerProcesado = new javax.swing.JButton();
        btnProcesar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1700, 700));

        lblModeloProyecto.setText("Modelo o proyecto");

        btnModeloProyecto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/loupe.png"))); // NOI18N

        lblSubModelo.setText("Submodelo");

        lblPeticion.setText("Petición");

        lblSolicitadaPor.setText("Solicitada por");

        lblEsquema.setText("Esquema");

        txtEsquema.setEditable(false);

        lblBBDD.setText("BBDD");

        txtBBDD.setEditable(false);

        lblGenerarHistorico.setText("Generar histórico");

        chkGenerarHistorico.setEnabled(false);

        lblBBDDHistorico.setText("BBDD histórico");

        txtBBDDHistorico.setEditable(false);

        lblEsquemaHistorico.setText("Esquema histórico");

        txtEsquemaHistorico.setEditable(false);

        lblDemanda.setText("Demanda");

        txtDemanda.setEditable(false);

        lblDescripcion.setText("Descripción");

        txtDescripcion.setColumns(20);
        txtDescripcion.setRows(5);
        scpDescripcion.setViewportView(txtDescripcion);

        btnLimpiar.setText("Limpiar");

        lblNotasAvisos.setText("Notas / avisos");

        tblNotas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Nivel", "Título", "Descripción", "Petición"
            }
        ));
        scpNotas.setViewportView(tblNotas);
        if (tblNotas.getColumnModel().getColumnCount() > 0) {
            tblNotas.getColumnModel().getColumn(0).setPreferredWidth(75);
            tblNotas.getColumnModel().getColumn(1).setPreferredWidth(500);
            tblNotas.getColumnModel().getColumn(2).setPreferredWidth(500);
            tblNotas.getColumnModel().getColumn(3).setPreferredWidth(500);
        }

        lblUltimasPeticiones.setText("Últimas peticiones");

        tblUltimasPeticiones.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Peticíon", "Solicitado", "Estado", "Fecha", "Usuario", "Descripción", "Comentario Entrega"
            }
        ));
        scpUltimasPeticiones.setViewportView(tblUltimasPeticiones);
        if (tblUltimasPeticiones.getColumnModel().getColumnCount() > 0) {
            tblUltimasPeticiones.getColumnModel().getColumn(0).setPreferredWidth(200);
            tblUltimasPeticiones.getColumnModel().getColumn(1).setPreferredWidth(100);
            tblUltimasPeticiones.getColumnModel().getColumn(2).setPreferredWidth(100);
            tblUltimasPeticiones.getColumnModel().getColumn(3).setPreferredWidth(100);
            tblUltimasPeticiones.getColumnModel().getColumn(4).setPreferredWidth(100);
            tblUltimasPeticiones.getColumnModel().getColumn(5).setPreferredWidth(300);
            tblUltimasPeticiones.getColumnModel().getColumn(6).setPreferredWidth(300);
        }

        btnVerProcesado.setText("Ver procesado");

        btnProcesar.setText("Procesar");

        btnCancelar.setText("Cancelar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(192, 192, 192)
                        .addComponent(btnLimpiar))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(13, 13, 13)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(lblBBDD)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblModeloProyecto)
                                            .addComponent(lblSubModelo, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(lblPeticion, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(lblSolicitadaPor, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(lblEsquema, javax.swing.GroupLayout.Alignment.TRAILING))))
                                .addComponent(lblEsquemaHistorico, javax.swing.GroupLayout.Alignment.TRAILING))
                            .addComponent(lblGenerarHistorico, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblBBDDHistorico, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblDescripcion, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblDemanda, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(chkGenerarHistorico)
                            .addComponent(txtPeticion)
                            .addComponent(txtSolicitadaPor)
                            .addComponent(txtEsquema)
                            .addComponent(txtBBDDHistorico)
                            .addComponent(txtEsquemaHistorico)
                            .addComponent(scpDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtModeloProyecto, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnModeloProyecto, javax.swing.GroupLayout.DEFAULT_SIZE, 67, Short.MAX_VALUE))
                            .addComponent(txtDemanda)
                            .addComponent(txtSubModelo)
                            .addComponent(txtBBDD))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(scpNotas, javax.swing.GroupLayout.DEFAULT_SIZE, 1271, Short.MAX_VALUE)
                            .addComponent(lblNotasAvisos)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblUltimasPeticiones)
                            .addComponent(scpUltimasPeticiones)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(btnVerProcesado)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnProcesar, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnModeloProyecto)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtModeloProyecto, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblModeloProyecto))
                    .addComponent(lblNotasAvisos))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblSubModelo)
                            .addComponent(txtSubModelo, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtPeticion, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblPeticion))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtSolicitadaPor, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblSolicitadaPor))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblEsquema)
                            .addComponent(txtEsquema, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblBBDD)
                            .addComponent(txtBBDD, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(chkGenerarHistorico)
                            .addComponent(lblGenerarHistorico))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtBBDDHistorico, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblBBDDHistorico))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtEsquemaHistorico, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblEsquemaHistorico))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtDemanda, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblDemanda))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(scpDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblDescripcion))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnLimpiar))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(scpNotas, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(47, 47, 47)
                        .addComponent(lblUltimasPeticiones)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(scpUltimasPeticiones, javax.swing.GroupLayout.DEFAULT_SIZE, 249, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnCancelar)
                            .addComponent(btnProcesar)
                            .addComponent(btnVerProcesado))))
                .addGap(12, 12, 12))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnModeloProyecto;
    private javax.swing.JButton btnProcesar;
    private javax.swing.JButton btnVerProcesado;
    private javax.swing.JCheckBox chkGenerarHistorico;
    private javax.swing.JLabel lblBBDD;
    private javax.swing.JLabel lblBBDDHistorico;
    private javax.swing.JLabel lblDemanda;
    private javax.swing.JLabel lblDescripcion;
    private javax.swing.JLabel lblEsquema;
    private javax.swing.JLabel lblEsquemaHistorico;
    private javax.swing.JLabel lblGenerarHistorico;
    private javax.swing.JLabel lblModeloProyecto;
    private javax.swing.JLabel lblNotasAvisos;
    private javax.swing.JLabel lblPeticion;
    private javax.swing.JLabel lblSolicitadaPor;
    private javax.swing.JLabel lblSubModelo;
    private javax.swing.JLabel lblUltimasPeticiones;
    private javax.swing.JScrollPane scpDescripcion;
    private javax.swing.JScrollPane scpNotas;
    private javax.swing.JScrollPane scpUltimasPeticiones;
    private javax.swing.JTable tblNotas;
    private javax.swing.JTable tblUltimasPeticiones;
    private javax.swing.JTextField txtBBDD;
    private javax.swing.JTextField txtBBDDHistorico;
    private javax.swing.JTextField txtDemanda;
    private javax.swing.JTextArea txtDescripcion;
    private javax.swing.JTextField txtEsquema;
    private javax.swing.JTextField txtEsquemaHistorico;
    private javax.swing.JTextField txtModeloProyecto;
    private javax.swing.JTextField txtPeticion;
    private javax.swing.JTextField txtSolicitadaPor;
    private javax.swing.JTextField txtSubModelo;
    // End of variables declaration//GEN-END:variables

    @Override
    protected void setupComponents() {
        initComponents();
    }

    @Override
    protected void initEvents() {
        PantallaProcesadoEnCursoActionListener actionListener = new PantallaProcesadoEnCursoActionListener(this);
        ListSelectionListener ultimasPeticionesSelectionListener = new UltimasPeticionesTableListener(this);

        btnCancelar.addActionListener(actionListener);
        btnVerProcesado.addActionListener(actionListener);

        ListSelectionModel ultimasPeticionesRowSM = tblUltimasPeticiones.getSelectionModel();
        ultimasPeticionesRowSM.addListSelectionListener(ultimasPeticionesSelectionListener);

        addOnLoadListener(actionListener);
    }

    @Override
    protected void setupLiterals() {
        setTitulo();
        setTexto(btnCancelar, "btnCancelar");
        setTexto(btnLimpiar, "btnLimpiar");
        setTexto(btnProcesar, "btnProcesar");
        setTexto(btnVerProcesado, "btnVerProcesado");
        setTexto(lblBBDD, "lblBBDD");
        setTexto(lblBBDDHistorico, "lblBBDDHistorico");
        setTexto(lblDemanda, "lblDemanda");
        setTexto(lblDescripcion, "lblDescripcion");
        setTexto(lblEsquema, "lblEsquema");
        setTexto(lblEsquemaHistorico, "lblEsquemaHistorico");
        setTexto(lblGenerarHistorico, "lblGenerarHistorico");
        setTexto(lblModeloProyecto, "lblModeloProyecto");
        setTexto(lblNotasAvisos, "lblNotasAvisos");
        setTexto(lblPeticion, "lblPeticion");
        setTexto(lblSolicitadaPor, "lblSolicitadaPor");
        setTexto(lblSubModelo, "lblSubModelo");
        setTexto(lblSubModelo, "lblSubModelo");
    }

    @Override
    protected void initModels() {
        Cabecera cabeceraNotas = new TablaNotasCabecera();
        MDSQLUIHelper.setTableModelRenderer(tblNotas, new ProcesarScriptNotaTableModel(cabeceraNotas), null);
        tblNotas.setDefaultRenderer(String.class, new NivelAvisosTableCellRenderer());

        Cabecera cabeceraUltimasPeticiones = new TablaUltimasPeticionesCabecera();
        MDSQLUIHelper.setTableModelRenderer(tblUltimasPeticiones, new ProcesarScriptUltimasPeticionesTableModel(cabeceraUltimasPeticiones), null);
    }

    @Override
    protected void initialState() {
        txtEsquema.setEditable(false);
        chkGenerarHistorico.setEnabled(false);
        txtBBDDHistorico.setEditable(false);
        txtEsquemaHistorico.setEditable(false);
        btnLimpiar.setEnabled(Boolean.FALSE);
        btnVerProcesado.setEnabled(Boolean.FALSE);

        Proceso proceso = (Proceso) params.get("proceso");
        if (!Objects.isNull(proceso)) {
            txtModeloProyecto.setEditable(false);
            txtSubModelo.setEditable(false);
            txtPeticion.setEditable(false);
            txtSolicitadaPor.setEditable(false);
            txtBBDD.setEditable(false);
            txtDemanda.setEditable(false);
            txtDescripcion.setEditable(false);

            txtModeloProyecto.setText(proceso.getModelo().getCodigoProyecto());
            txtSubModelo.setText(proceso.getSubproyecto().getDescripcionSubProyecto());
            txtPeticion.setText(proceso.getCodigoPeticion());
            txtSolicitadaPor.setText(proceso.getCodigoUsrPeticion());

            if (!Objects.isNull(proceso.getBbdd())) {
                txtBBDD.setText(proceso.getBbdd().getNombreBBDD());
                txtEsquema.setText(proceso.getBbdd().getNombreEsquema());
                txtBBDDHistorico.setText(proceso.getBbdd().getNombreBBDDHis());
                txtEsquemaHistorico.setText(proceso.getBbdd().getNombreEsquemaHis());
            }

            txtDemanda.setText(proceso.getCodigoDemanda());
            txtDescripcion.setText(proceso.getTxtDescripcion());

            btnModeloProyecto.setEnabled(false);
            btnProcesar.setEnabled(false);
        }
    }

    @Override
    public JTable getTblUltimasPeticiones() {
        return tblUltimasPeticiones;
    }

    @Override
    public JButton getBtnVerProcesado() {
        return btnVerProcesado;
    }

    public JButton getBtnCancelar() {
        return btnCancelar;
    }

    public JButton getBtnLimpiar() {
        return btnLimpiar;
    }

    public JButton getBtnModeloProyecto() {
        return btnModeloProyecto;
    }

    public JButton getBtnProcesar() {
        return btnProcesar;
    }

    public JCheckBox getChkGenerarHistorico() {
        return chkGenerarHistorico;
    }

    public JTable getTblNotas() {
        return tblNotas;
    }

    public JTextField getTxtBBDD() {
        return txtBBDD;
    }

    public JTextField getTxtBBDDHistorico() {
        return txtBBDDHistorico;
    }

    public JTextField getTxtDemanda() {
        return txtDemanda;
    }

    public JTextArea getTxtDescripcion() {
        return txtDescripcion;
    }

    public JTextField getTxtEsquema() {
        return txtEsquema;
    }

    public JTextField getTxtEsquemaHistorico() {
        return txtEsquemaHistorico;
    }

    public JTextField getTxtModeloProyecto() {
        return txtModeloProyecto;
    }

    public JTextField getTxtPeticion() {
        return txtPeticion;
    }

    public JTextField getTxtSolicitadaPor() {
        return txtSolicitadaPor;
    }

    public JTextField getTxtSubModelo() {
        return txtSubModelo;
    }
    
    
}
