/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mdsql.ui;

import com.mdsql.bussiness.entities.BBDD;
import com.mdsql.bussiness.entities.Proceso;
import com.mdsql.bussiness.entities.Script;
import com.mdsql.bussiness.entities.Session;
import com.mdsql.ui.listener.PantallaEjecutarScriptsListener;
import com.mdsql.ui.listener.combo.EjecutarScriptBBDDItemListener;
import com.mdsql.ui.listener.tables.HistoricoScriptsTableListener;
import com.mdsql.ui.listener.tables.HistoricoScriptsTableModelListener;
import com.mdsql.ui.listener.tables.VigenteScriptsTableListener;
import com.mdsql.ui.listener.tables.VigenteScriptsTableModelListener;
import com.mdsql.ui.model.BBDDComboBoxModel;
import com.mdsql.ui.model.ScriptsTableModel;
import com.mdsql.ui.model.cabeceras.TablaScriptsCabecera;
import com.mdsql.ui.renderer.CmbBBDDRenderer;
import com.mdsql.ui.renderer.ScriptTableCellRenderer;
import com.mdsql.ui.utils.MDSQLUIHelper;
import com.mdsql.utils.MDSQLAppHelper;
import com.mdsql.utils.MDSQLConstants;
import com.mdsql.utils.MDSQLConstants.Procesado;
import com.mdval.ui.model.cabeceras.Cabecera;
import com.mdval.ui.utils.DialogSupport;
import com.mdval.ui.utils.FrameSupport;
import java.awt.event.ItemListener;
import java.util.Map;
import java.util.Objects;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.ListSelectionModel;
import lombok.Getter;
import lombok.Setter;

/**
 *
 * @author federico
 */
public class PantallaEjecutarScripts extends DialogSupport {

    @Getter
    @Setter
    private Script seleccionado;

    @Getter
    @Setter
    private Proceso proceso;

    public PantallaEjecutarScripts(FrameSupport parent, Boolean modal) {
        super(parent, modal);
    }

    public PantallaEjecutarScripts(FrameSupport parent, Boolean modal, Map<String, Object> params) {
        super(parent, modal, params);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblIdProcesado = new javax.swing.JLabel();
        txtIdProcesado = new javax.swing.JTextField();
        lblEstadoEjecucion = new javax.swing.JLabel();
        txtEstadoEjecucion = new javax.swing.JTextField();
        lblModeloProyecto = new javax.swing.JLabel();
        txtModelo = new javax.swing.JTextField();
        lblSubModelo = new javax.swing.JLabel();
        txtSubmodelo = new javax.swing.JTextField();
        lblPeticion = new javax.swing.JLabel();
        txtPeticion = new javax.swing.JTextField();
        lblSolicitadaPor = new javax.swing.JLabel();
        txtSolicitadaPor = new javax.swing.JTextField();
        lblEsquema = new javax.swing.JLabel();
        txtEsquema = new javax.swing.JTextField();
        lblBBDD = new javax.swing.JLabel();
        cmbBBDD = new javax.swing.JComboBox<>();
        lblBBDDHistorico = new javax.swing.JLabel();
        txtBBDDHistorico = new javax.swing.JTextField();
        lblEsquemaHistorico = new javax.swing.JLabel();
        txtEsquemaHistorico = new javax.swing.JTextField();
        lblDemanda = new javax.swing.JLabel();
        txtDemanda = new javax.swing.JTextField();
        btnRechazar = new javax.swing.JButton();
        lblVigente = new javax.swing.JLabel();
        scpVigente = new javax.swing.JScrollPane();
        tblVigente = new javax.swing.JTable();
        lblHistorico = new javax.swing.JLabel();
        scpHistorico = new javax.swing.JScrollPane();
        tblHistorico = new javax.swing.JTable();
        btnVerLog = new javax.swing.JButton();
        btnDetalleScript = new javax.swing.JButton();
        btnDescartar = new javax.swing.JButton();
        btnReparar = new javax.swing.JButton();
        btnVerCuadres = new javax.swing.JButton();
        btnVerErrores = new javax.swing.JButton();
        btnExcepcion = new javax.swing.JButton();
        btnAceptar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1236, 732));

        lblIdProcesado.setText("Id procesado");

        txtIdProcesado.setEditable(false);

        lblEstadoEjecucion.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblEstadoEjecucion.setText("Estado ejecución");

        lblModeloProyecto.setText("Modelo o proyecto");

        lblSubModelo.setText("Submodelo");

        lblPeticion.setText("Petición");

        lblSolicitadaPor.setText("Solicitada por");

        lblEsquema.setText("Esquema");

        lblBBDD.setText("BBDD");

        lblBBDDHistorico.setText("BBDD histórico");

        lblEsquemaHistorico.setText("Esquema histórico");

        lblDemanda.setText("Demanda");

        btnRechazar.setText("Rechazar");

        lblVigente.setText("Vigente");

        tblVigente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "", "Orden", "Estado", "Fecha", "Ejecución", "Operaciones", "Objetos", "Script"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Boolean.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        scpVigente.setViewportView(tblVigente);

        lblHistorico.setText("Histórico");

        tblHistorico.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "", "Orden", "Estado", "Fecha", "Ejecución", "Operaciones", "Objetos", "Script"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Boolean.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        scpHistorico.setViewportView(tblHistorico);

        btnVerLog.setText("Ver log");

        btnDetalleScript.setText("Detalle script");

        btnDescartar.setText("Descartar");

        btnReparar.setText("Reparar");

        btnVerCuadres.setText("Ver cuadres");

        btnVerErrores.setText("Ver errores");

        btnExcepcion.setText("Excepción");

        btnAceptar.setText("ACEPTAR");

        btnCancelar.setText("CANCELAR");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblIdProcesado)
                            .addComponent(lblEstadoEjecucion, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblSubModelo)
                            .addComponent(lblModeloProyecto)
                            .addComponent(lblPeticion)
                            .addComponent(lblSolicitadaPor)
                            .addComponent(lblEsquema)
                            .addComponent(lblBBDD)
                            .addComponent(lblBBDDHistorico)
                            .addComponent(lblEsquemaHistorico)
                            .addComponent(lblDemanda))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtIdProcesado)
                            .addComponent(txtEstadoEjecucion)
                            .addComponent(txtModelo)
                            .addComponent(txtSubmodelo)
                            .addComponent(txtPeticion)
                            .addComponent(txtSolicitadaPor)
                            .addComponent(txtEsquema)
                            .addComponent(cmbBBDD, javax.swing.GroupLayout.Alignment.TRAILING, 0, 166, Short.MAX_VALUE)
                            .addComponent(txtBBDDHistorico, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtEsquemaHistorico, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtDemanda, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnRechazar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(22, 22, 22)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(lblVigente))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(scpVigente, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(scpHistorico, javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(lblHistorico)
                                    .addGap(427, 427, 427))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(btnAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(btnVerLog, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(btnDetalleScript, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(btnDescartar, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(btnReparar, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(btnVerCuadres, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(btnVerErrores, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(btnExcepcion, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblVigente)
                    .addComponent(lblIdProcesado)
                    .addComponent(txtIdProcesado, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(scpVigente, javax.swing.GroupLayout.DEFAULT_SIZE, 350, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblHistorico)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(scpHistorico, javax.swing.GroupLayout.DEFAULT_SIZE, 223, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtEstadoEjecucion, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblEstadoEjecucion))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtModelo, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblModeloProyecto))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtSubmodelo, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblSubModelo))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtPeticion, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblPeticion))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtSolicitadaPor, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblSolicitadaPor))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtEsquema, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblEsquema))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cmbBBDD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblBBDD))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtBBDDHistorico, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblBBDDHistorico))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtEsquemaHistorico, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblEsquemaHistorico))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtDemanda, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblDemanda))
                        .addGap(18, 18, 18)
                        .addComponent(btnRechazar)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnVerLog)
                    .addComponent(btnDetalleScript)
                    .addComponent(btnDescartar)
                    .addComponent(btnReparar)
                    .addComponent(btnVerCuadres)
                    .addComponent(btnVerErrores)
                    .addComponent(btnExcepcion))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCancelar)
                    .addComponent(btnAceptar))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnDescartar;
    private javax.swing.JButton btnDetalleScript;
    private javax.swing.JButton btnExcepcion;
    private javax.swing.JButton btnRechazar;
    private javax.swing.JButton btnReparar;
    private javax.swing.JButton btnVerCuadres;
    private javax.swing.JButton btnVerErrores;
    private javax.swing.JButton btnVerLog;
    private javax.swing.JComboBox<BBDD> cmbBBDD;
    private javax.swing.JLabel lblBBDD;
    private javax.swing.JLabel lblBBDDHistorico;
    private javax.swing.JLabel lblDemanda;
    private javax.swing.JLabel lblEsquema;
    private javax.swing.JLabel lblEsquemaHistorico;
    private javax.swing.JLabel lblEstadoEjecucion;
    private javax.swing.JLabel lblHistorico;
    private javax.swing.JLabel lblIdProcesado;
    private javax.swing.JLabel lblModeloProyecto;
    private javax.swing.JLabel lblPeticion;
    private javax.swing.JLabel lblSolicitadaPor;
    private javax.swing.JLabel lblSubModelo;
    private javax.swing.JLabel lblVigente;
    private javax.swing.JScrollPane scpHistorico;
    private javax.swing.JScrollPane scpVigente;
    private javax.swing.JTable tblHistorico;
    private javax.swing.JTable tblVigente;
    private javax.swing.JTextField txtBBDDHistorico;
    private javax.swing.JTextField txtDemanda;
    private javax.swing.JTextField txtEsquema;
    private javax.swing.JTextField txtEsquemaHistorico;
    private javax.swing.JTextField txtEstadoEjecucion;
    private javax.swing.JTextField txtIdProcesado;
    private javax.swing.JTextField txtModelo;
    private javax.swing.JTextField txtPeticion;
    private javax.swing.JTextField txtSolicitadaPor;
    private javax.swing.JTextField txtSubmodelo;
    // End of variables declaration//GEN-END:variables

    @Override
    protected void initEvents() {
        PantallaEjecutarScriptsListener actionListener = new PantallaEjecutarScriptsListener(this);
        VigenteScriptsTableListener vigenteSelectionListener = new VigenteScriptsTableListener(this);
        HistoricoScriptsTableListener historicoSelectionListener = new HistoricoScriptsTableListener(this);
        ItemListener bbddItemListener = new EjecutarScriptBBDDItemListener(this);

        btnRechazar.setActionCommand(MDSQLConstants.PANTALLA_EJECUTAR_SCRIPTS_BTN_RECHAZAR);
        btnVerLog.setActionCommand(MDSQLConstants.PANTALLA_EJECUTAR_SCRIPTS_BTN_VER_LOG);
        btnDetalleScript.setActionCommand(MDSQLConstants.PANTALLA_EJECUTAR_SCRIPTS_BTN_DETALLE_SCRIPT);
        btnDescartar.setActionCommand(MDSQLConstants.PANTALLA_EJECUTAR_SCRIPTS_BTN_DESCARTAR);
        btnReparar.setActionCommand(MDSQLConstants.PANTALLA_EJECUTAR_SCRIPTS_BTN_REPARAR);
        btnVerCuadres.setActionCommand(MDSQLConstants.PANTALLA_EJECUTAR_SCRIPTS_BTN_VER_CUADRES);
        btnVerErrores.setActionCommand(MDSQLConstants.PANTALLA_EJECUTAR_SCRIPTS_BTN_VER_ERRORES);
        btnExcepcion.setActionCommand(MDSQLConstants.PANTALLA_EJECUTAR_SCRIPTS_BTN_EXCEPCION);
        btnAceptar.setActionCommand(MDSQLConstants.PANTALLA_EJECUTAR_SCRIPTS_BTN_ACEPTAR);
        btnCancelar.setActionCommand(MDSQLConstants.PANTALLA_EJECUTAR_SCRIPTS_BTN_CANCELAR);

        btnRechazar.addActionListener(actionListener);
        btnVerLog.addActionListener(actionListener);
        btnDetalleScript.addActionListener(actionListener);
        btnDescartar.addActionListener(actionListener);
        btnReparar.addActionListener(actionListener);
        btnVerCuadres.addActionListener(actionListener);
        btnVerErrores.addActionListener(actionListener);
        btnExcepcion.addActionListener(actionListener);
        btnAceptar.addActionListener(actionListener);
        btnCancelar.addActionListener(actionListener);

        ListSelectionModel vigenteRowSM = tblVigente.getSelectionModel();
        vigenteRowSM.addListSelectionListener(vigenteSelectionListener);

        ListSelectionModel historicoRowSM = tblHistorico.getSelectionModel();
        historicoRowSM.addListSelectionListener(historicoSelectionListener);

        cmbBBDD.addItemListener(bbddItemListener);
        this.addOnLoadListener(actionListener);
    }

    @SuppressWarnings("unchecked")
    @Override
    protected void initModels() {
        BBDDComboBoxModel bbddModel = new BBDDComboBoxModel();
        cmbBBDD.setModel(bbddModel);
        cmbBBDD.setRenderer(new CmbBBDDRenderer());

        Cabecera cabecera = new TablaScriptsCabecera();

        // Hay que escuchar por cambios en el modelo, ya que se van a marcar / desmarcar los checks
        tblVigente.getModel().addTableModelListener(new VigenteScriptsTableModelListener(this));
        
        //Si es reentrante, bloqueamos la seleccion de ficheros y los marcamos todos
        ScriptsTableModel scriptsTableModel = new ScriptsTableModel(cabecera);
        Session session = (Session) MDSQLAppHelper.getGlobalProperty(MDSQLConstants.SESSION);
        boolean isReentrante = session.getProcesado().equals(Procesado.REENTRANTE);
        scriptsTableModel.setSeleccionBloqueada(isReentrante);
        MDSQLUIHelper.setTableModelRenderer(tblVigente, scriptsTableModel, new ScriptTableCellRenderer());
        
        tblHistorico.getModel().addTableModelListener(new HistoricoScriptsTableModelListener(this));
        MDSQLUIHelper.setTableModelRenderer(tblHistorico, new ScriptsTableModel(cabecera), new ScriptTableCellRenderer());
    }

    @Override
    protected void initialState() {
        txtIdProcesado.setEditable(Boolean.FALSE);
        txtEstadoEjecucion.setEditable(Boolean.FALSE);
        txtModelo.setEditable(Boolean.FALSE);
        txtSubmodelo.setEditable(Boolean.FALSE);
        txtPeticion.setEditable(Boolean.FALSE);
        txtSolicitadaPor.setEditable(Boolean.FALSE);
        txtEsquema.setEditable(Boolean.FALSE);
        txtBBDDHistorico.setEditable(Boolean.FALSE);
        txtEsquemaHistorico.setEditable(Boolean.FALSE);
        txtDemanda.setEditable(Boolean.FALSE);

        txtIdProcesado.setHorizontalAlignment(JTextField.LEFT);
        txtEstadoEjecucion.setHorizontalAlignment(JTextField.LEFT);
        txtModelo.setHorizontalAlignment(JTextField.LEFT);
        txtSubmodelo.setHorizontalAlignment(JTextField.LEFT);
        txtPeticion.setHorizontalAlignment(JTextField.LEFT);
        txtSolicitadaPor.setHorizontalAlignment(JTextField.LEFT);
        txtEsquema.setHorizontalAlignment(JTextField.LEFT);
        txtBBDDHistorico.setHorizontalAlignment(JTextField.LEFT);
        txtEsquemaHistorico.setHorizontalAlignment(JTextField.LEFT);
        txtDemanda.setHorizontalAlignment(JTextField.LEFT);

        enableButtons(Boolean.FALSE);

        if (!Objects.isNull(proceso)) {
            txtEstadoEjecucion.setText(proceso.getDescripcionEstadoProceso());

            MDSQLUIHelper.resetText(txtModelo, proceso.getModelo().getCodigoProyecto(), 20);
            MDSQLUIHelper.resetText(txtSubmodelo, proceso.getSubproyecto().getDescripcionSubProyecto(), 20);

            txtPeticion.setText(proceso.getCodigoPeticion());
            txtSolicitadaPor.setText(proceso.getCodigoUsrPeticion());

            if (!Objects.isNull(proceso.getBbdd())) {
                txtEsquema.setText(proceso.getBbdd().getNombreEsquema());
                cmbBBDD.setSelectedItem(proceso.getBbdd());
                txtBBDDHistorico.setText(proceso.getBbdd().getNombreBBDDHis());
                txtEsquemaHistorico.setText(proceso.getBbdd().getNombreEsquemaHis());
            }

            txtDemanda.setText(proceso.getCodigoDemanda());
        }
    }

    @Override
    protected void setupLiterals() {
        setTitulo();
        setTexto(lblEstadoEjecucion, "lblEstadoEjecucion"); 
        setTexto(lblModeloProyecto,"lblModeloProyecto");
        setTexto(lblSubModelo,"lblSubModelo");
        setTexto(lblSolicitadaPor,"lblSolicitadaPor");
        setTexto(lblDemanda,"lblDemanda");
        setTexto(lblIdProcesado,"lblIdProcesado");
        setTexto(lblBBDDHistorico,"lblBBDDHistorico");
        setTexto(lblBBDD,"lblBBDD");
        setTexto(lblEsquemaHistorico,"lblEsquemaHistorico");
        setTexto(btnRechazar,"btnRechazar");
        setTexto(lblVigente,"lblVigente");
        setTexto(lblHistorico,"lblHistorico");
        setTexto(lblPeticion,"lblPeticion");
        setTexto(lblEsquema,"lblEsquema");
        setTexto(btnVerLog,"btnVerLog");
        setTexto(btnDetalleScript,"btnDetalleScript");
        setTexto(btnDescartar,"btnDescartar");
        setTexto(btnReparar,"btnReparar");
        setTexto(btnVerCuadres,"btnVerCuadres");
        setTexto(btnVerErrores,"btnVerErrores");
        setTexto(btnExcepcion,"btnExcepcion");
        setTexto(btnAceptar,"btnAceptar");
        setTexto(btnCancelar,"btnCancelar");
    }

    /**
     *
     * @param val */
    public void enableButtons(Boolean val) {
        btnVerLog.setEnabled(val);
        btnDetalleScript.setEnabled(val);
        btnDescartar.setEnabled(val);
        btnReparar.setEnabled(val);
        btnVerErrores.setEnabled(val);
        btnVerCuadres.setEnabled(val);
        btnExcepcion.setEnabled(val);
    }

    @Override
    protected void setupComponents() {
        initComponents();
    }

    public JButton getBtnAceptar() {
        return btnAceptar;
    }

    public JButton getBtnCancelar() {
        return btnCancelar;
    }

    public JButton getBtnDescartar() {
        return btnDescartar;
    }

    public JButton getBtnDetalleScript() {
        return btnDetalleScript;
    }

    public JButton getBtnExcepcion() {
        return btnExcepcion;
    }

    public JButton getBtnRechazar() {
        return btnRechazar;
    }

    public JButton getBtnReparar() {
        return btnReparar;
    }

    public JButton getBtnVerCuadres() {
        return btnVerCuadres;
    }

    public JButton getBtnVerErrores() {
        return btnVerErrores;
    }

    public JButton getBtnVerLog() {
        return btnVerLog;
    }

    public JComboBox<BBDD> getCmbBBDD() {
        return cmbBBDD;
    }

    public JTable getTblHistorico() {
        return tblHistorico;
    }

    public JTable getTblVigente() {
        return tblVigente;
    }

    public JTextField getTxtBBDDHistorico() {
        return txtBBDDHistorico;
    }

    public JTextField getTxtDemanda() {
        return txtDemanda;
    }

    public JTextField getTxtEsquema() {
        return txtEsquema;
    }

    public JTextField getTxtEsquemaHistorico() {
        return txtEsquemaHistorico;
    }

    public JTextField getTxtEstadoEjecucion() {
        return txtEstadoEjecucion;
    }

    public JTextField getTxtIdProcesado() {
        return txtIdProcesado;
    }

    public JTextField getTxtModelo() {
        return txtModelo;
    }

    public JTextField getTxtPeticion() {
        return txtPeticion;
    }

    public JTextField getTxtSolicitadaPor() {
        return txtSolicitadaPor;
    }

    public JTextField getTxtSubmodelo() {
        return txtSubmodelo;
    }
}
