/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mdsql.ui;

import com.mdsql.bussiness.entities.NivelImportancia;
import com.mdsql.ui.adapter.DoubleClickMouseAdapter;
import com.mdsql.ui.listener.PantallaDetalleAvisosPorModeloListener;
import com.mdsql.ui.model.AvisosModeloTableModel;
import com.mdsql.ui.model.NivelesImportanciaComboBoxModel;
import com.mdsql.ui.model.cabeceras.TablaAvisosModeloCabecera;
import com.mdsql.ui.renderer.CmbNivelImportanciaRenderer;
import com.mdsql.ui.utils.DialogSupportModeloPermiso;
import com.mdsql.ui.utils.MDSQLUIHelper;
import com.mdval.ui.model.cabeceras.Cabecera;
import com.mdval.ui.utils.FrameSupport;
import java.util.Map;
import javax.swing.JButton;
import javax.swing.JCheckBox;
import javax.swing.JComboBox;
import javax.swing.JTable;
import javax.swing.JTextField;

/**
 *
 * @author Luis-Enrique.Varona FASE 3 - 3.2 Mantenimiento Avisos por modelo
 * objeto y/o modelo
 */
public class PantallaDetalleAvisosPorModelo extends DialogSupportModeloPermiso {

    /**
     * Creates new form FormMantenimientoAvisosPorModeloObjeto fase III
     * 3.2-Mantenimiento Avisos por modelo objeto y/o modelo
     *
     * @param parent
     * @param modal
     */
    public PantallaDetalleAvisosPorModelo(FrameSupport parent, Boolean modal) {
        super(parent, modal);
    }

    public PantallaDetalleAvisosPorModelo(FrameSupport parent, Boolean modal, Map<String, Object> params) {
        super(parent, modal, params);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblModeloProyecto = new javax.swing.JLabel();
        txtModeloProyecto = new javax.swing.JTextField();
        btnModeloProyecto = new javax.swing.JButton();
        txtModeloProyectoDescrip = new javax.swing.JTextField();
        lblPeticion = new javax.swing.JLabel();
        txtPeticion = new javax.swing.JTextField();
        lblImportancia = new javax.swing.JLabel();
        cmbImportancia = new javax.swing.JComboBox<>();
        lblNombreObjeto = new javax.swing.JLabel();
        txtNombreObjeto = new javax.swing.JTextField();
        chkHabilitada = new javax.swing.JCheckBox();
        btnBuscar = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        scpAvisos = new javax.swing.JScrollPane();
        tblAvisos = new javax.swing.JTable();
        btnAlta = new javax.swing.JButton();
        btnModificacion = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lblModeloProyecto.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblModeloProyecto.setText("Modelo o Proyecto");

        txtModeloProyecto.setMinimumSize(new java.awt.Dimension(160, 24));
        txtModeloProyecto.setName(""); // NOI18N
        txtModeloProyecto.setPreferredSize(new java.awt.Dimension(160, 24));

        btnModeloProyecto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/loupe.png"))); // NOI18N

        txtModeloProyectoDescrip.setEditable(false);

        lblPeticion.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblPeticion.setText("Petición");

        txtPeticion.setMinimumSize(new java.awt.Dimension(160, 24));
        txtPeticion.setPreferredSize(new java.awt.Dimension(160, 24));

        lblImportancia.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblImportancia.setText("Importancia");
        lblImportancia.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        cmbImportancia.setModel(new NivelesImportanciaComboBoxModel());
        cmbImportancia.setMinimumSize(new java.awt.Dimension(182, 24));
        cmbImportancia.setPreferredSize(new java.awt.Dimension(182, 24));

        lblNombreObjeto.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblNombreObjeto.setText("Nombre Objeto");

        txtNombreObjeto.setToolTipText("");
        txtNombreObjeto.setMinimumSize(new java.awt.Dimension(289, 24));
        txtNombreObjeto.setPreferredSize(new java.awt.Dimension(289, 24));

        chkHabilitada.setText("Habilitada   ");
        chkHabilitada.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        chkHabilitada.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        btnBuscar.setText("Buscar");

        btnLimpiar.setText("Limpiar");

        tblAvisos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Importancia", "NombreObjeto", "Titulo", "Habilitada", "Petición", "Descripción"
            }
        ));
        scpAvisos.setViewportView(tblAvisos);

        btnAlta.setText("Alta");

        btnModificacion.setText("Modificación");

        btnCancelar.setText("CANCELAR");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(scpAvisos)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(lblModeloProyecto, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtModeloProyecto, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(lblPeticion, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtPeticion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblImportancia, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cmbImportancia, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(56, 56, 56)
                                .addComponent(lblNombreObjeto, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtNombreObjeto, javax.swing.GroupLayout.DEFAULT_SIZE, 619, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(chkHabilitada, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnModeloProyecto, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtModeloProyectoDescrip))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnAlta, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnModificacion, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnModeloProyecto, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblModeloProyecto, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtModeloProyecto, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtModeloProyectoDescrip, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblImportancia, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cmbImportancia, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtPeticion, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblPeticion, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblNombreObjeto, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtNombreObjeto, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(chkHabilitada, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(scpAvisos, javax.swing.GroupLayout.DEFAULT_SIZE, 346, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAlta, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnModificacion, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlta;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnModeloProyecto;
    private javax.swing.JButton btnModificacion;
    private javax.swing.JCheckBox chkHabilitada;
    private javax.swing.JComboBox<NivelImportancia> cmbImportancia;
    private javax.swing.JLabel lblImportancia;
    private javax.swing.JLabel lblModeloProyecto;
    private javax.swing.JLabel lblNombreObjeto;
    private javax.swing.JLabel lblPeticion;
    private javax.swing.JScrollPane scpAvisos;
    private javax.swing.JTable tblAvisos;
    private javax.swing.JTextField txtModeloProyecto;
    private javax.swing.JTextField txtModeloProyectoDescrip;
    private javax.swing.JTextField txtNombreObjeto;
    private javax.swing.JTextField txtPeticion;
    // End of variables declaration//GEN-END:variables
    @Override
    protected void setupComponents() {
        initComponents();
    }

    @Override
    protected void initEvents() {
        PantallaDetalleAvisosPorModeloListener localFormListener = new PantallaDetalleAvisosPorModeloListener(this);
        btnBuscar.addActionListener(localFormListener);
        btnLimpiar.addActionListener(localFormListener);
        btnModificacion.addActionListener(localFormListener);
        btnAlta.addActionListener(localFormListener);

        tblAvisos.getSelectionModel().addListSelectionListener(localFormListener);

        // Tratamiendo doble click
        DoubleClickMouseAdapter doubleClickMouseAdapter = new DoubleClickMouseAdapter();
        doubleClickMouseAdapter.setListener(localFormListener);
        tblAvisos.addMouseListener(doubleClickMouseAdapter);

        formListener = localFormListener;
        addOnLoadListener(formListener);
    }

    @Override
    protected void setupLiterals() {
        setTitulo();
        setTexto(lblModeloProyecto, "lblModeloProyecto");
        setTexto(lblPeticion, "lblPeticion");
        setTexto(lblImportancia, "lblImportancia");
        setTexto(lblNombreObjeto, "lblNombreObjeto");
        setTexto(chkHabilitada, "chkHabilitada");
        setTexto(btnBuscar, "btnBuscar");
        setTexto(btnLimpiar, "btnLimpiar");
        setTexto(btnAlta, "btnAlta");
        setTexto(btnModificacion, "btnModificacion");
        setTexto(btnCancelar, "btnCancelar");
    }

    @Override
    protected void initModels() {
        Cabecera cabecera = new TablaAvisosModeloCabecera();
        MDSQLUIHelper.setTableModelRenderer(tblAvisos, new AvisosModeloTableModel(cabecera), null);

        cmbImportancia.setRenderer(new CmbNivelImportanciaRenderer());
    }

    @Override
    protected void initialState() {
    }

    public JButton getBtnBuscar() {
        return btnBuscar;
    }

    @Override
    public JButton getBtnCancelar() {
        return btnCancelar;
    }

    public JButton getBtnGenerar() {
        return btnModificacion;
    }

    @Override
    public JButton getBtnModeloProyecto() {
        return btnModeloProyecto;
    }

    public JTable getTblAvisos() {
        return tblAvisos;
    }

    @Override
    public JTextField getTxtModeloProyecto() {
        return txtModeloProyecto;
    }

    public JTextField getTxtNombreObjeto() {
        return txtNombreObjeto;
    }

    @Override
    public JTextField getTxtPeticion() {
        return txtPeticion;
    }

    public JComboBox<NivelImportancia> getCmbImportancia() {
        return cmbImportancia;
    }

    @Override
    public JButton getBtnLimpiar() {
        return btnLimpiar;
    }

    public JButton getBtnAlta() {
        return btnAlta;
    }

    public JButton getBtnModificacion() {
        return btnModificacion;
    }

    @Override
    public JCheckBox getChkHabilitada() {
        return chkHabilitada;
    }

    @Override
    public JTextField getTxtModeloProyectoDescrip() {
        return txtModeloProyectoDescrip;
    }

}
