/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mdsql.ui;

import com.mdsql.bussiness.entities.CodigoDescripcion;
import com.mdsql.ui.listener.PantallaConsultaHistoricoCambiosModeloListener;
import com.mdsql.ui.model.HistoricoCambiosModeloTableModel;
import com.mdsql.ui.model.cabeceras.TablaHistoricoCambiosModeloCabecera;
import com.mdsql.ui.renderer.CmbCodigoDescripcionRenderer;
import com.mdsql.ui.utils.DialogSupportModelo;
import com.mdsql.ui.utils.MDSQLUIHelper;
import com.mdval.ui.model.cabeceras.Cabecera;
import com.mdval.ui.utils.FrameSupport;
import java.util.Map;
import javax.swing.JButton;
import javax.swing.JCheckBox;
import javax.swing.JComboBox;
import javax.swing.JTable;
import javax.swing.JTextField;

/**
 *
 * @author Luis-Enrique.Varona FASE III - 3.3-Mantenimiento validaciones
 * programadas
 */
public class PantallaConsultaHistoricoCambiosModelo extends DialogSupportModelo {

     /**
     *
     * @param parent
     * @param modal
     */
    public PantallaConsultaHistoricoCambiosModelo(FrameSupport parent, Boolean modal) {
        super(parent, modal);
    }

    public PantallaConsultaHistoricoCambiosModelo(FrameSupport parent, Boolean modal, Map<String, Object> params) {
        super(parent, modal, params);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblModeloProyecto = new javax.swing.JLabel();
        txtModeloProyecto = new javax.swing.JTextField();
        btnModeloProyecto = new javax.swing.JButton();
        txtModeloProyectoDescrip = new javax.swing.JTextField();
        lblDesde = new javax.swing.JLabel();
        txtDesde = new javax.swing.JTextField();
        lblHasta = new javax.swing.JLabel();
        txtHasta = new javax.swing.JTextField();
        lblElemento = new javax.swing.JLabel();
        txtElemento = new javax.swing.JTextField();
        lblInforme = new javax.swing.JLabel();
        cmbInforme = new javax.swing.JComboBox<>();
        chkIncluirPermisosSinonimos = new javax.swing.JCheckBox();
        btnBuscar = new javax.swing.JButton();
        scpHistoricoCambiosModelo = new javax.swing.JScrollPane();
        tblHistoricoCambiosModelo = new javax.swing.JTable();
        btnInforme = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lblModeloProyecto.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblModeloProyecto.setText("Modelo o Proyecto");

        txtModeloProyecto.setMinimumSize(new java.awt.Dimension(122, 24));
        txtModeloProyecto.setName(""); // NOI18N
        txtModeloProyecto.setPreferredSize(new java.awt.Dimension(122, 24));

        btnModeloProyecto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/loupe.png"))); // NOI18N

        txtModeloProyectoDescrip.setEditable(false);

        lblDesde.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblDesde.setText("Desde");

        txtDesde.setToolTipText("");
        txtDesde.setMinimumSize(new java.awt.Dimension(122, 24));
        txtDesde.setPreferredSize(new java.awt.Dimension(122, 24));

        lblHasta.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblHasta.setText("Hasta");

        txtHasta.setToolTipText("");
        txtHasta.setMinimumSize(new java.awt.Dimension(122, 24));
        txtHasta.setName(""); // NOI18N
        txtHasta.setPreferredSize(new java.awt.Dimension(122, 24));

        lblElemento.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblElemento.setText("Objeto/Elemento");
        lblElemento.setToolTipText("");

        txtElemento.setToolTipText("");
        txtElemento.setMinimumSize(new java.awt.Dimension(250, 24));
        txtElemento.setName(""); // NOI18N
        txtElemento.setPreferredSize(new java.awt.Dimension(250, 24));

        lblInforme.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblInforme.setText("Informe");
        lblInforme.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        cmbInforme.setMinimumSize(new java.awt.Dimension(195, 24));
        cmbInforme.setName(""); // NOI18N
        cmbInforme.setPreferredSize(new java.awt.Dimension(195, 24));

        chkIncluirPermisosSinonimos.setText("Incluir Permisos/Sinónimos");
        chkIncluirPermisosSinonimos.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        chkIncluirPermisosSinonimos.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        btnBuscar.setText("Buscar");

        tblHistoricoCambiosModelo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Fecha", "Objeto", "Tipo", "Elemento", "Tipo", "Cambio", "Detalle Cambio", "Petición", "Solicitante", "Script"
            }
        ));
        scpHistoricoCambiosModelo.setViewportView(tblHistoricoCambiosModelo);

        btnInforme.setText("Informe");

        btnCancelar.setText("CANCELAR");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(567, Short.MAX_VALUE)
                .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 559, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(scpHistoricoCambiosModelo)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(lblModeloProyecto, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtModeloProyecto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(lblDesde, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtDesde, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblHasta, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtHasta, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblElemento, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtElemento, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblInforme, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cmbInforme, 0, 160, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(chkIncluirPermisosSinonimos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnModeloProyecto, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtModeloProyectoDescrip))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnInforme, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(45, 45, 45)
                        .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnModeloProyecto, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblModeloProyecto, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtModeloProyecto, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtModeloProyectoDescrip, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(chkIncluirPermisosSinonimos, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblInforme, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cmbInforme, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblDesde, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtDesde, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblHasta, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtHasta, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblElemento, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtElemento, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(scpHistoricoCambiosModelo, javax.swing.GroupLayout.DEFAULT_SIZE, 374, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnInforme, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        txtModeloProyecto.getAccessibleContext().setAccessibleName("");

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnInforme;
    private javax.swing.JButton btnModeloProyecto;
    private javax.swing.JCheckBox chkIncluirPermisosSinonimos;
    private javax.swing.JComboBox<CodigoDescripcion> cmbInforme;
    private javax.swing.JLabel lblDesde;
    private javax.swing.JLabel lblElemento;
    private javax.swing.JLabel lblHasta;
    private javax.swing.JLabel lblInforme;
    private javax.swing.JLabel lblModeloProyecto;
    private javax.swing.JScrollPane scpHistoricoCambiosModelo;
    private javax.swing.JTable tblHistoricoCambiosModelo;
    private javax.swing.JTextField txtDesde;
    private javax.swing.JTextField txtElemento;
    private javax.swing.JTextField txtHasta;
    private javax.swing.JTextField txtModeloProyecto;
    private javax.swing.JTextField txtModeloProyectoDescrip;
    // End of variables declaration//GEN-END:variables
   @Override
    protected void setupComponents() {
        initComponents();
    }

    @Override
    protected void initEvents() {
        formListener = new PantallaConsultaHistoricoCambiosModeloListener(this);
        btnModeloProyecto.addActionListener(formListener);
        btnBuscar.addActionListener(formListener);
        btnInforme.addActionListener(formListener);
        btnCancelar.addActionListener(formListener);
        addOnLoadListener(formListener);
    }

    @Override
    protected void setupLiterals() {
        setTitulo();
        setTexto(lblModeloProyecto, "lblModeloProyecto");
        setTexto(lblDesde, "lblDesde");
        setTexto(lblHasta, "lblHasta");
        setTexto(lblElemento, "lblObjetoElemento");
        setTexto(lblInforme, "lblInforme");
        setTexto(chkIncluirPermisosSinonimos, "chkIncluirPermisosSinonimos");
        setTexto(btnBuscar, "btnBuscar");
        setTexto(btnInforme, "btnInforme");
        setTexto(btnCancelar, "btnCancelar");
    }

    @Override
    protected void initModels() {
        Cabecera cabecera = new TablaHistoricoCambiosModeloCabecera();
        MDSQLUIHelper.setTableModelRenderer(tblHistoricoCambiosModelo, new HistoricoCambiosModeloTableModel(cabecera), null);
        cmbInforme.setRenderer(new CmbCodigoDescripcionRenderer());
    }

    @Override
    protected void initialState() {
    }

    @Override
    public JTextField getTxtModeloProyectoDescrip() {
        return txtModeloProyectoDescrip;
    }

    public JButton getBtnBuscar() {
        return btnBuscar;
    }

    @Override
    public JButton getBtnCancelar() {
        return btnCancelar;
    }

    public JButton getBtnInforme() {
        return btnInforme;
    }

    @Override
    public JButton getBtnModeloProyecto() {
        return btnModeloProyecto;
    }

    public JCheckBox getChkIncluirPermisosSinonimos() {
        return chkIncluirPermisosSinonimos;
    }

    public JComboBox<CodigoDescripcion> getCmbInforme() {
        return cmbInforme;
    }

    public JTable getTblHistoricoCambiosModelo() {
        return tblHistoricoCambiosModelo;
    }

    public JTextField getTxtDesde() {
        return txtDesde;
    }

    public JTextField getTxtElemento() {
        return txtElemento;
    }

    public JTextField getTxtHasta() {
        return txtHasta;
    }

    @Override
    public JTextField getTxtModeloProyecto() {
        return txtModeloProyecto;
    }
}
