/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mdsql.ui;

import java.util.Map;
import javax.swing.JButton;
import com.mdsql.ui.listener.PantallaVerErroresScriptListener;
import com.mdsql.ui.model.VerErroresScriptTableModel;
import com.mdsql.ui.model.VerParchesScriptTableModel;
import com.mdsql.ui.model.cabeceras.TablaErroresCabecera;
import com.mdsql.ui.model.cabeceras.TablaParchesCabecera;
import com.mdsql.ui.utils.MDSQLUIHelper;
import com.mdval.ui.model.cabeceras.Cabecera;
import com.mdval.ui.utils.DialogSupport;
import com.mdval.ui.utils.FrameSupport;
import javax.swing.JTable;
import javax.swing.JTextArea;

/**
 *
 * @author USUARIO1
 */
public class PantallaVerErroresScript extends DialogSupport {

    public PantallaVerErroresScript(FrameSupport parent, Boolean modal) {
        super(parent, modal);
    }

    public PantallaVerErroresScript(FrameSupport parent, Boolean modal, Map<String, Object> params) {
        super(parent, modal, params);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scpErroresScript = new javax.swing.JScrollPane();
        tblErroresScript = new javax.swing.JTable();
        lblError = new javax.swing.JLabel();
        scpError = new javax.swing.JScrollPane();
        txtError = new javax.swing.JTextArea();
        lblParchesAsociados = new javax.swing.JLabel();
        scpParches = new javax.swing.JScrollPane();
        tblParches = new javax.swing.JTable();
        btnCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1500, 600));

        tblErroresScript.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Orden", "Fecha", "Procesado", "Ejecución", "Iteración", "Script"
            }
        ));
        scpErroresScript.setViewportView(tblErroresScript);

        lblError.setText("Error");

        txtError.setColumns(20);
        txtError.setRows(5);
        scpError.setViewportView(txtError);

        lblParchesAsociados.setText("Parches asociados");

        tblParches.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Orden", "Estado", "Fecha", "Procesado", "Ejecucion", "Iteracion", "Script", "Comentario"
            }
        ));
        scpParches.setViewportView(tblParches);
        if (tblParches.getColumnModel().getColumnCount() > 0) {
            tblParches.getColumnModel().getColumn(0).setPreferredWidth(100);
            tblParches.getColumnModel().getColumn(1).setPreferredWidth(120);
            tblParches.getColumnModel().getColumn(2).setPreferredWidth(120);
            tblParches.getColumnModel().getColumn(3).setPreferredWidth(120);
            tblParches.getColumnModel().getColumn(4).setPreferredWidth(120);
            tblParches.getColumnModel().getColumn(5).setPreferredWidth(120);
            tblParches.getColumnModel().getColumn(6).setPreferredWidth(350);
            tblParches.getColumnModel().getColumn(7).setPreferredWidth(600);
        }

        btnCancelar.setText("CANCELAR");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnCancelar))
                    .addComponent(scpParches, javax.swing.GroupLayout.DEFAULT_SIZE, 1288, Short.MAX_VALUE)
                    .addComponent(scpErroresScript)
                    .addComponent(scpError)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblParchesAsociados)
                            .addComponent(lblError))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scpErroresScript, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblError)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scpError, javax.swing.GroupLayout.DEFAULT_SIZE, 146, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblParchesAsociados)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scpParches, javax.swing.GroupLayout.DEFAULT_SIZE, 245, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnCancelar)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JLabel lblError;
    private javax.swing.JLabel lblParchesAsociados;
    private javax.swing.JScrollPane scpError;
    private javax.swing.JScrollPane scpErroresScript;
    private javax.swing.JScrollPane scpParches;
    private javax.swing.JTable tblErroresScript;
    private javax.swing.JTable tblParches;
    private javax.swing.JTextArea txtError;
    // End of variables declaration//GEN-END:variables

    @Override
    protected void setupComponents() {
        initComponents();
    }

    @Override
    protected void initEvents() {
        PantallaVerErroresScriptListener actionListener = new PantallaVerErroresScriptListener(this);
        btnCancelar.addActionListener(actionListener);

        tblErroresScript.getSelectionModel().addListSelectionListener(actionListener);
        this.addOnLoadListener(actionListener);
    }

    @Override
    protected void initModels() {
        Cabecera cabeceraErrores = new TablaErroresCabecera();
        MDSQLUIHelper.setTableModelRenderer(tblErroresScript, new VerErroresScriptTableModel(cabeceraErrores), null);

        Cabecera cabeceraParches = new TablaParchesCabecera();
        MDSQLUIHelper.setTableModelRenderer(tblParches, new VerParchesScriptTableModel(cabeceraParches), null);
    }

    @Override
    protected void initialState() {
        MDSQLUIHelper.setReadOnlyText(txtError);
    }

    @Override
    protected void setupLiterals() {
        setTitulo();
        setTexto(lblError, "lblError");        
        setTexto(lblParchesAsociados, "lblParchesAsociados");
        setTexto(btnCancelar, "btnCancelar");
    }

    public JButton getBtnCancelar() {
        return btnCancelar;
    }

    public JTable getTblErroresScript() {
        return tblErroresScript;
    }

    public JTable getTblParches() {
        return tblParches;
    }

    public JTextArea getTxtError() {
        return txtError;
    }
  
}
