/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mdsql.ui.form;

import com.mdsql.bussiness.entities.Grant;
import com.mdsql.bussiness.entities.Permiso;
import com.mdsql.bussiness.entities.Propietario;
import com.mdsql.bussiness.entities.Sinonimo;
import com.mdsql.ui.form.listener.FormDetallePermisosPorObjetoListener;
import com.mdsql.ui.adapter.DoubleClickMouseAdapter;
import com.mdsql.ui.model.PermisosObjetoTableModel;
import com.mdsql.ui.model.SinonimosObjetoTableModel;
import com.mdsql.ui.model.cabeceras.TablaPermisosObjetoCabecera;
import com.mdsql.ui.model.cabeceras.TablaSinonimosObjetoCabecera;
import com.mdsql.ui.renderer.TableSelectionRenderer;
import com.mdsql.ui.utils.DialogSupportModeloPermiso;
import com.mdsql.ui.utils.MDSQLUIHelper;
import com.mdval.ui.model.cabeceras.Cabecera;
import com.mdval.ui.utils.FrameSupport;
import java.util.Map;
import javax.swing.JButton;
import javax.swing.JCheckBox;
import javax.swing.JComboBox;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.ListSelectionModel;
import lombok.Getter;
import lombok.Setter;

/**
 *
 * @author Luis-Enrique.Varona
 */
public class FormDetallePermisosPorObjeto extends DialogSupportModeloPermiso {

    /**
     * Creates new form FormDetallePermisosPorObjeto 2.1.2.1-Pantalla Detalle
     * Permisos por Objeto.
     *
     * @param parent
     * @param modal
     */
    public FormDetallePermisosPorObjeto(FrameSupport parent, Boolean modal) {
        super(parent, modal);
    }

    public FormDetallePermisosPorObjeto(FrameSupport parent, Boolean modal, Map<String, Object> params) {
        super(parent, modal, params);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblModeloProyecto = new javax.swing.JLabel();
        txtModeloProyecto = new javax.swing.JTextField();
        txtModeloProyectoDescrip = new javax.swing.JTextField();
        lblNombreObjeto = new javax.swing.JLabel();
        txtNombreObjeto = new javax.swing.JTextField();
        lblTipoObjeto = new javax.swing.JLabel();
        cmbTipoObjeto = new javax.swing.JComboBox<>();
        lblPermisoSinonimo = new javax.swing.JLabel();
        cmbPermisoSinonimo = new javax.swing.JComboBox<>();
        lblPropietarioSinonimo = new javax.swing.JLabel();
        cmbPropietarioSinonimo = new javax.swing.JComboBox<>();
        lblIncluirPDC = new javax.swing.JLabel();
        cmbIncluirPDC = new javax.swing.JComboBox<>();
        lblEntorno = new javax.swing.JLabel();
        cmbEntorno = new javax.swing.JComboBox<>();
        lblFuncionNombre = new javax.swing.JLabel();
        txtFuncionNombre = new javax.swing.JTextField();
        lblPermiso = new javax.swing.JLabel();
        cmbPermiso = new javax.swing.JComboBox<>();
        lblWithGrantOption = new javax.swing.JLabel();
        cmbWithGrantOption = new javax.swing.JComboBox<>();
        lblReceptorPermisos = new javax.swing.JLabel();
        cmbReceptorPermisos = new javax.swing.JComboBox<>();
        chkHabilitada = new javax.swing.JCheckBox();
        btnBuscar = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        lblPermisos = new javax.swing.JLabel();
        jScrollPanePermisos = new javax.swing.JScrollPane();
        tblPermisos = new javax.swing.JTable();
        lblSinonimos = new javax.swing.JLabel();
        jScrollPaneSinonimos = new javax.swing.JScrollPane();
        tblSinonimos = new javax.swing.JTable();
        btnAlta = new javax.swing.JButton();
        btnModificacion = new javax.swing.JButton();
        btnInforme = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lblModeloProyecto.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblModeloProyecto.setText("Modelo o Proyecto");
        lblModeloProyecto.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        txtModeloProyecto.setEditable(false);
        txtModeloProyecto.setToolTipText("");

        txtModeloProyectoDescrip.setEditable(false);
        txtModeloProyectoDescrip.setToolTipText("");

        lblNombreObjeto.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblNombreObjeto.setText("Nombre Objeto");
        lblNombreObjeto.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        lblTipoObjeto.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblTipoObjeto.setText("Tipo de Objeto");
        lblTipoObjeto.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        lblPermisoSinonimo.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblPermisoSinonimo.setText("Permiso/Sinónimo");
        lblPermisoSinonimo.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        lblPropietarioSinonimo.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblPropietarioSinonimo.setText("Propietario sinónimo");
        lblPropietarioSinonimo.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        lblIncluirPDC.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblIncluirPDC.setText("Incluir en PDC");
        lblIncluirPDC.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        lblEntorno.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblEntorno.setText("Entorno");
        lblEntorno.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        lblFuncionNombre.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblFuncionNombre.setText("Función Nombre");
        lblFuncionNombre.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        lblPermiso.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblPermiso.setText("Permiso");
        lblPermiso.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        lblWithGrantOption.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblWithGrantOption.setText("WITH GRANT OPTION");
        lblWithGrantOption.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        lblReceptorPermisos.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblReceptorPermisos.setText("Receptor Permisos");
        lblReceptorPermisos.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        chkHabilitada.setText("Habilitada");
        chkHabilitada.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        chkHabilitada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkHabilitadaActionPerformed(evt);
            }
        });

        btnBuscar.setText("Buscar");

        btnLimpiar.setText("Limpiar");

        lblPermisos.setText("Permisos");

        tblPermisos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Receptor", "Tipo Objeto", "Permiso", "Entorno", "Grant Option", "Incluir en PDC", "Habilitada", "Petición", "Usuario Alta", "Fecha Alta", "Usuario Modificacion", "Fecha Modificacion"
            }
        ));
        tblPermisos.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        tblPermisos.setCellSelectionEnabled(true);
        jScrollPanePermisos.setViewportView(tblPermisos);

        lblSinonimos.setText("Sinónimos");

        tblSinonimos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Receptor", "Tipo Objeto", "Entorno", "Propietario", "Incluir en PDC", "Habilitada", "Petición", "Función Nombre", "Usuario Alta", "Fecha Alta", "Usuario Modificacion", "Fecha Modificacion"
            }
        ));
        tblSinonimos.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        tblSinonimos.setCellSelectionEnabled(true);
        jScrollPaneSinonimos.setViewportView(tblSinonimos);

        btnAlta.setText("Alta");

        btnModificacion.setText("Modificación");
        btnModificacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificacionActionPerformed(evt);
            }
        });

        btnInforme.setText("Informe");

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblSinonimos)
                            .addComponent(lblPermisos, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jScrollPaneSinonimos)
                                .addComponent(jScrollPanePermisos)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lblWithGrantOption, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lblEntorno, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lblPermisoSinonimo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lblNombreObjeto, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lblModeloProyecto, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(1, 1, 1)
                                            .addComponent(txtModeloProyecto, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(txtModeloProyectoDescrip))
                                        .addGroup(layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addComponent(txtNombreObjeto, javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(layout.createSequentialGroup()
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGroup(layout.createSequentialGroup()
                                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                .addComponent(cmbPermisoSinonimo, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addComponent(cmbEntorno, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addComponent(cmbWithGrantOption, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                            .addGap(295, 295, 295)
                                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                .addComponent(lblPropietarioSinonimo, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addComponent(lblFuncionNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addComponent(lblReceptorPermisos, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                            .addComponent(txtFuncionNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addComponent(cmbPropietarioSinonimo, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addComponent(cmbReceptorPermisos, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addComponent(btnLimpiar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                            .addGap(360, 360, 360)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addComponent(lblTipoObjeto, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(cmbTipoObjeto, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addComponent(lblIncluirPDC, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(cmbIncluirPDC, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                    .addComponent(lblPermiso, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(cmbPermiso, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addComponent(chkHabilitada, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(478, 478, 478)
                        .addComponent(btnAlta, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnModificacion, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addComponent(btnInforme, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38)
                        .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(19, 19, 19))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblModeloProyecto, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtModeloProyectoDescrip, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtModeloProyecto, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombreObjeto, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNombreObjeto, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTipoObjeto, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbTipoObjeto, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPermisoSinonimo, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbPermisoSinonimo, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblIncluirPDC, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbIncluirPDC, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPropietarioSinonimo, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbPropietarioSinonimo, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEntorno, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbEntorno, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPermiso, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbPermiso, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblFuncionNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFuncionNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblWithGrantOption, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbWithGrantOption, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblReceptorPermisos, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chkHabilitada, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbReceptorPermisos, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addComponent(lblPermisos, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(jScrollPanePermisos, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblSinonimos)
                .addGap(6, 6, 6)
                .addComponent(jScrollPaneSinonimos, javax.swing.GroupLayout.DEFAULT_SIZE, 156, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnInforme, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnModificacion, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAlta, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void chkHabilitadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkHabilitadaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkHabilitadaActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnModificacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificacionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnModificacionActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlta;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnInforme;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnModificacion;
    private javax.swing.JCheckBox chkHabilitada;
    private javax.swing.JComboBox<String> cmbEntorno;
    private javax.swing.JComboBox<String> cmbIncluirPDC;
    private javax.swing.JComboBox<String> cmbPermiso;
    private javax.swing.JComboBox<String> cmbPermisoSinonimo;
    private javax.swing.JComboBox<Propietario> cmbPropietarioSinonimo;
    private javax.swing.JComboBox<Grant> cmbReceptorPermisos;
    private javax.swing.JComboBox<String> cmbTipoObjeto;
    private javax.swing.JComboBox<String> cmbWithGrantOption;
    private javax.swing.JScrollPane jScrollPanePermisos;
    private javax.swing.JScrollPane jScrollPaneSinonimos;
    private javax.swing.JLabel lblEntorno;
    private javax.swing.JLabel lblFuncionNombre;
    private javax.swing.JLabel lblIncluirPDC;
    private javax.swing.JLabel lblModeloProyecto;
    private javax.swing.JLabel lblNombreObjeto;
    private javax.swing.JLabel lblPermiso;
    private javax.swing.JLabel lblPermisoSinonimo;
    private javax.swing.JLabel lblPermisos;
    private javax.swing.JLabel lblPropietarioSinonimo;
    private javax.swing.JLabel lblReceptorPermisos;
    private javax.swing.JLabel lblSinonimos;
    private javax.swing.JLabel lblTipoObjeto;
    private javax.swing.JLabel lblWithGrantOption;
    private javax.swing.JTable tblPermisos;
    private javax.swing.JTable tblSinonimos;
    private javax.swing.JTextField txtFuncionNombre;
    private javax.swing.JTextField txtModeloProyecto;
    private javax.swing.JTextField txtModeloProyectoDescrip;
    private javax.swing.JTextField txtNombreObjeto;
    // End of variables declaration//GEN-END:variables

    @Getter
    @Setter
    private Permiso permiso;

    @Getter
    @Setter
    private Sinonimo sinonimo;

    @Override
    protected void setupComponents() {
        initComponents();
    }

    @Override
    protected void initEvents() {
        FormDetallePermisosPorObjetoListener localFormListener = new FormDetallePermisosPorObjetoListener(this);
        //
        btnBuscar.addActionListener(localFormListener);
        btnLimpiar.addActionListener(localFormListener);
        btnAlta.addActionListener(localFormListener);
        btnModificacion.addActionListener(localFormListener);
        btnInforme.addActionListener(localFormListener);
        btnCancelar.addActionListener(localFormListener);
        tblPermisos.getSelectionModel().addListSelectionListener(localFormListener);
        tblSinonimos.getSelectionModel().addListSelectionListener(localFormListener);
        
        // Tratamiendo doble click
        DoubleClickMouseAdapter doubleClickMouseAdapter = new DoubleClickMouseAdapter();
        doubleClickMouseAdapter.setListener(localFormListener);
        tblPermisos.addMouseListener(doubleClickMouseAdapter);
        tblSinonimos.addMouseListener(doubleClickMouseAdapter);
        //
        formListener = localFormListener;
        addOnLoadListener(localFormListener);
    }

    @Override
    protected void setupLiterals() {
        setTitle(literales.getLiteral("FormDetallePermisosPorObjeto.title"));
        lblModeloProyecto.setText(literales.getLiteral("FormDetallePermisosPorObjeto.lblModeloProyecto"));
        lblNombreObjeto.setText(literales.getLiteral("FormDetallePermisosPorObjeto.lblNombreObjeto"));
        lblTipoObjeto.setText(literales.getLiteral("FormDetallePermisosPorObjeto.lblTipoObjeto"));
        lblPermisoSinonimo.setText(literales.getLiteral("FormDetallePermisosPorObjeto.lblPermisoSinonimo"));
        lblPropietarioSinonimo.setText(literales.getLiteral("FormDetallePermisosPorObjeto.lblPropietarioSinonimo"));
        lblIncluirPDC.setText(literales.getLiteral("FormDetallePermisosPorObjeto.lblIncluirPDC"));
        lblEntorno.setText(literales.getLiteral("FormDetallePermisosPorObjeto.lblEntorno"));
        lblFuncionNombre.setText(literales.getLiteral("FormDetallePermisosPorObjeto.lblFuncionNombre"));
        lblPermiso.setText(literales.getLiteral("FormDetallePermisosPorObjeto.lblPermiso"));
        lblWithGrantOption.setText(literales.getLiteral("FormDetallePermisosPorObjeto.lblWithGrantOption"));
        lblReceptorPermisos.setText(literales.getLiteral("FormDetallePermisosPorObjeto.lblReceptorPermisos"));
        chkHabilitada.setText(literales.getLiteral("FormDetallePermisosPorObjeto.chkHabilitada"));
        lblPermisos.setText(literales.getLiteral("FormDetallePermisosPorObjeto.lblPermisos"));
        lblSinonimos.setText(literales.getLiteral("FormDetallePermisosPorObjeto.lblSinonimos"));
        btnBuscar.setText(literales.getLiteral("FormDetallePermisosPorObjeto.btnBuscar"));
        btnLimpiar.setText(literales.getLiteral("FormDetallePermisosPorObjeto.btnLimpiar"));
        btnAlta.setText(literales.getLiteral("FormDetallePermisosPorObjeto.btnAlta"));
        btnInforme.setText(literales.getLiteral("FormDetallePermisosPorObjeto.btnInforme"));
        btnModificacion.setText(literales.getLiteral("FormDetallePermisosPorObjeto.btnModificacion"));
        btnCancelar.setText(literales.getLiteral("FormDetallePermisosPorObjeto.btnCancelar"));
    }

    @Override
    protected void initialState() {
    }

    @Override
    protected void initModels() {
        Cabecera cabeceraPermisos = new TablaPermisosObjetoCabecera();
        MDSQLUIHelper.setTableModel(tblPermisos, new PermisosObjetoTableModel(cabeceraPermisos));
        Cabecera cabeceraSinonimos = new TablaSinonimosObjetoCabecera();
        MDSQLUIHelper.setTableModel(tblSinonimos, new SinonimosObjetoTableModel(cabeceraSinonimos));
        //
        tblPermisos.setDefaultRenderer(String.class, new TableSelectionRenderer());
        tblPermisos.setCellSelectionEnabled(true);
        tblPermisos.setRowSelectionAllowed(true);
        tblPermisos.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        //
        tblSinonimos.setDefaultRenderer(String.class, new TableSelectionRenderer());
        tblSinonimos.setCellSelectionEnabled(true);
        tblSinonimos.setRowSelectionAllowed(true);
        tblSinonimos.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
    }

    public JButton getBtnAlta() {
        return btnAlta;
    }

    public JButton getBtnBuscar() {
        return btnBuscar;
    }

    @Override
    public JButton getBtnCancelar() {
        return btnCancelar;
    }

    public JButton getBtnInforme() {
        return btnInforme;
    }

    public JButton getBtnModificacion() {
        return btnModificacion;
    }

    @Override
    public JComboBox<String> getCmbEntorno() {
        return cmbEntorno;
    }

    @Override
    public JComboBox<String> getCmbIncluirPDC() {
        return cmbIncluirPDC;
    }

    @Override
    public JComboBox<String> getCmbPermiso() {
        return cmbPermiso;
    }

    @Override
    public JComboBox<String> getCmbPermisoSinonimo() {
        return cmbPermisoSinonimo;
    }

    @Override
    public JComboBox<String> getCmbTipoObjeto() {
        return cmbTipoObjeto;
    }

    @Override
    public JComboBox<String> getCmbWithGrantOption() {
        return cmbWithGrantOption;
    }

    @Override
    public JComboBox<Propietario> getCmbPropietarioSinonimo() {
        return cmbPropietarioSinonimo;
    }

    @Override
    public JComboBox<Grant> getCmbReceptorPermisos() {
        return cmbReceptorPermisos;
    }

    public JTable getTblPermisos() {
        return tblPermisos;
    }

    public JTable getTblSinonimos() {
        return tblSinonimos;
    }

    @Override
    public JTextField getTxtModeloProyecto() {
        return txtModeloProyecto;
    }

    @Override
    public JTextField getTxtFuncionNombre() {
        return txtFuncionNombre;
    }

    public void setTxtFuncionNombre(JTextField txtFuncionNombre) {
        this.txtFuncionNombre = txtFuncionNombre;
    }

    @Override
    public JTextField getTxtModeloProyectoDescrip() {
        return txtModeloProyectoDescrip;
    }

    public void setTxtModeloProyectoDescrip(JTextField txtModeloProyectoDescrip) {
        this.txtModeloProyectoDescrip = txtModeloProyectoDescrip;
    }

    public JTextField getTxtNombreObjeto() {
        return txtNombreObjeto;
    }

    public void setTxtNombreObjeto(JTextField txtNombreObjeto) {
        this.txtNombreObjeto = txtNombreObjeto;
    }

    @Override
    public JCheckBox getChkHabilitada() {
        return chkHabilitada;
    }

    @Override
    public JButton getBtnLimpiar() {
        return btnLimpiar;
    }

}
