/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mdsql.ui.form;

import com.mdsql.bussiness.entities.Grant;
import com.mdsql.bussiness.entities.Permiso;
import com.mdsql.bussiness.entities.Sinonimo;
import com.mdsql.ui.adapter.DoubleClickMouseAdapter;
import com.mdsql.ui.form.listener.FormDetallePermisosPorColumnaListener;
import com.mdsql.ui.model.PermisosColumnaTableModel;
import com.mdsql.ui.model.cabeceras.TablaPermisosColumnaCabecera;
import com.mdsql.ui.renderer.TableSelectionRenderer;
import com.mdsql.ui.utils.DialogSupportModeloPermiso;
import com.mdsql.ui.utils.MDSQLUIHelper;
import com.mdval.ui.model.cabeceras.Cabecera;
import com.mdval.ui.utils.FrameSupport;
import java.util.Map;
import javax.swing.JButton;
import javax.swing.JCheckBox;
import javax.swing.JComboBox;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.ListSelectionModel;
import lombok.Getter;
import lombok.Setter;

/**
 *
 * @author Luis-Enrique.Varona
 */
public class FormDetallePermisosPorColumna extends DialogSupportModeloPermiso {

  /**
     * Creates new form FormDetallePermisosPorColumna 
     * 2.1.2.3	Pantalla Detalle Permisos por Columna.
     *
     * @param parent
     * @param modal
     */
    public FormDetallePermisosPorColumna(FrameSupport parent, Boolean modal) {
        super(parent, modal);
    }

    public FormDetallePermisosPorColumna(FrameSupport parent, Boolean modal, Map<String, Object> params) {
        super(parent, modal, params);
    }

 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        lblModeloProyecto = new javax.swing.JLabel();
        txtModeloProyecto = new javax.swing.JTextField();
        txtModeloProyectoDescrip = new javax.swing.JTextField();
        lblTabla = new javax.swing.JLabel();
        txtTabla = new javax.swing.JTextField();
        lblColumna = new javax.swing.JLabel();
        txtColumna = new javax.swing.JTextField();
        lblEntorno = new javax.swing.JLabel();
        cmbEntorno = new javax.swing.JComboBox<>();
        lblPermiso = new javax.swing.JLabel();
        cmbPermiso = new javax.swing.JComboBox<>();
        lblReceptorPermisos = new javax.swing.JLabel();
        cmbReceptorPermisos = new javax.swing.JComboBox<>();
        chkHabilitada = new javax.swing.JCheckBox();
        lblIncluirPDC = new javax.swing.JLabel();
        cmbIncluirPDC = new javax.swing.JComboBox<>();
        lblWithGrantOption = new javax.swing.JLabel();
        cmbWithGrantOption = new javax.swing.JComboBox<>();
        btnBuscar = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        lblTablaPermisos = new javax.swing.JLabel();
        scrollPanePermisos = new javax.swing.JScrollPane();
        tblPermisos = new javax.swing.JTable();
        btnAlta = new javax.swing.JButton();
        btnModificacion = new javax.swing.JButton();
        btnInforme = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lblModeloProyecto.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblModeloProyecto.setText("Modelo o Proyecto");

        txtModeloProyecto.setEditable(false);

        txtModeloProyectoDescrip.setEditable(false);

        lblTabla.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblTabla.setText("Tabla");

        lblColumna.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblColumna.setText("Columna");

        lblEntorno.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblEntorno.setText("Entorno");

        lblPermiso.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblPermiso.setText("Permiso");

        lblReceptorPermisos.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblReceptorPermisos.setText("Receptor Permisos");

        chkHabilitada.setText("Habilitada");
        chkHabilitada.setToolTipText("");
        chkHabilitada.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);

        lblIncluirPDC.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblIncluirPDC.setText("Incluir en PDC");

        lblWithGrantOption.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblWithGrantOption.setText("WITH GRANT OPTION");

        btnBuscar.setText("Buscar");

        btnLimpiar.setText("Limpiar");

        lblTablaPermisos.setText("Permisos");

        tblPermisos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Receptor", "Tabla", "Columna", "Permiso", "Entorno", "Grant Option", "Incluir en PDC", "Habilitada", "Petición", "Usuario Alta", "Fecha Alta", "Usuario Modificación", "Fecha Modificación"
            }
        ));
        tblPermisos.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        scrollPanePermisos.setViewportView(tblPermisos);

        btnAlta.setText("Alta");

        btnModificacion.setText("Modificación");

        btnInforme.setText("Informe");

        btnCancelar.setText("CANCELAR");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scrollPanePermisos)
                .addGap(8, 8, 8))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblModeloProyecto, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblTabla, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblPermiso, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblIncluirPDC, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(txtModeloProyecto, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(7, 7, 7)
                                        .addComponent(txtModeloProyectoDescrip))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(cmbPermiso, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(cmbIncluirPDC, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(txtTabla, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(330, 330, 330)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(lblColumna, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(lblReceptorPermisos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addComponent(lblWithGrantOption, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(8, 8, 8)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(cmbWithGrantOption, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(txtColumna, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(cmbReceptorPermisos, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addGap(235, 235, 235)
                                                        .addComponent(lblEntorno, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(cmbEntorno, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addGap(297, 297, 297)
                                                        .addComponent(chkHabilitada, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(40, 40, 40)
                                                .addComponent(btnLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                            .addComponent(lblTablaPermisos)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(551, 551, 551)
                        .addComponent(btnAlta, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(btnModificacion, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addComponent(btnInforme, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)
                        .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnAlta, btnCancelar, btnInforme, btnModificacion});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblModeloProyecto, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtModeloProyecto, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtModeloProyectoDescrip, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblTabla, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblEntorno, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cmbEntorno, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(chkHabilitada, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblPermiso, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblIncluirPDC, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(txtColumna, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lblColumna, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(cmbReceptorPermisos, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lblReceptorPermisos, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(35, 35, 35))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblWithGrantOption, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cmbWithGrantOption, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtTabla, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cmbPermiso, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cmbIncluirPDC, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addComponent(lblTablaPermisos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scrollPanePermisos, javax.swing.GroupLayout.DEFAULT_SIZE, 318, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAlta, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnModificacion, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnInforme, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlta;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnInforme;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnModificacion;
    private javax.swing.JCheckBox chkHabilitada;
    private javax.swing.JComboBox<String> cmbEntorno;
    private javax.swing.JComboBox<String> cmbIncluirPDC;
    private javax.swing.JComboBox<String> cmbPermiso;
    private javax.swing.JComboBox<Grant> cmbReceptorPermisos;
    private javax.swing.JComboBox<String> cmbWithGrantOption;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel lblColumna;
    private javax.swing.JLabel lblEntorno;
    private javax.swing.JLabel lblIncluirPDC;
    private javax.swing.JLabel lblModeloProyecto;
    private javax.swing.JLabel lblPermiso;
    private javax.swing.JLabel lblReceptorPermisos;
    private javax.swing.JLabel lblTabla;
    private javax.swing.JLabel lblTablaPermisos;
    private javax.swing.JLabel lblWithGrantOption;
    private javax.swing.JScrollPane scrollPanePermisos;
    private javax.swing.JTable tblPermisos;
    private javax.swing.JTextField txtColumna;
    private javax.swing.JTextField txtModeloProyecto;
    private javax.swing.JTextField txtModeloProyectoDescrip;
    private javax.swing.JTextField txtTabla;
    // End of variables declaration//GEN-END:variables

    @Getter
    @Setter
    private Permiso permisoSeleccionado;

    @Getter
    @Setter
    private Sinonimo sinonimoSeleccionado;

    @Override
    protected void setupComponents() {
        initComponents();
    }

    @Override
    protected void initEvents() {
        FormDetallePermisosPorColumnaListener localFormListener = new FormDetallePermisosPorColumnaListener(this);
        btnBuscar.addActionListener(localFormListener);
        btnLimpiar.addActionListener(localFormListener);
        btnAlta.addActionListener(localFormListener);    
        btnModificacion.addActionListener(localFormListener);    
        btnInforme.addActionListener(localFormListener);
        tblPermisos.getSelectionModel().addListSelectionListener(localFormListener);

        // Tratamiendo doble click
        DoubleClickMouseAdapter doubleClickMouseAdapter = new DoubleClickMouseAdapter();
        doubleClickMouseAdapter.setListener(localFormListener);
        tblPermisos.addMouseListener(doubleClickMouseAdapter);
        addOnLoadListener(localFormListener);

        formListener = localFormListener;
        addOnLoadListener(formListener);
    }

    @Override
    protected void setupLiterals() {
        setTitle(literales.getLiteral("FormDetallePermisosPorColumna.title"));
        lblModeloProyecto.setText(literales.getLiteral("FormDetallePermisosPorColumna.lblModeloProyecto"));
        lblTabla.setText(literales.getLiteral("FormDetallePermisosPorColumna.lblTabla"));
        lblColumna.setText(literales.getLiteral("FormDetallePermisosPorColumna.lblColumna"));
        lblEntorno.setText(literales.getLiteral("FormDetallePermisosPorColumna.lblEntorno"));
        lblPermiso.setText(literales.getLiteral("FormDetallePermisosPorColumna.lblPermiso"));
        lblReceptorPermisos.setText(literales.getLiteral("FormDetallePermisosPorColumna.lblReceptorPermisos"));
        chkHabilitada.setText(literales.getLiteral("FormDetallePermisosPorColumna.chkHabilitada"));
        lblIncluirPDC.setText(literales.getLiteral("FormDetallePermisosPorColumna.lblIncluirPDC"));
        lblWithGrantOption.setText(literales.getLiteral("FormDetallePermisosPorColumna.lblWithGrantOption"));
        lblTablaPermisos.setText(literales.getLiteral("FormDetallePermisosPorColumna.lblTablaPermisos"));
        btnBuscar.setText(literales.getLiteral("FormDetallePermisosPorColumna.btnBuscar"));
        btnAlta.setText(literales.getLiteral("FormDetallePermisosPorColumna.btnAlta"));
        btnInforme.setText(literales.getLiteral("FormDetallePermisosPorColumna.btnInforme"));
        btnModificacion.setText(literales.getLiteral("FormDetallePermisosPorColumna.btnModificacion"));
        btnCancelar.setText(literales.getLiteral("FormDetallePermisosPorColumna.btnCancelar"));
    }

    @Override
    protected void initModels() {
        Cabecera cabeceraColumnas = new TablaPermisosColumnaCabecera();
        MDSQLUIHelper.setTableModel(tblPermisos, new PermisosColumnaTableModel(cabeceraColumnas));
        tblPermisos.setDefaultRenderer(String.class, new TableSelectionRenderer());
        tblPermisos.setCellSelectionEnabled(true);
        tblPermisos.setRowSelectionAllowed(true);        
        tblPermisos.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        
    }

    @Override
    protected void initialState() {}

    public JButton getBtnAlta() {
        return btnAlta;
    }

    public JButton getBtnBuscar() {
        return btnBuscar;
    }

    @Override
    public JButton getBtnCancelar() {
        return btnCancelar;
    }

    public JButton getBtnInforme() {
        return btnInforme;
    }

    public JButton getBtnModificacion() {
        return btnModificacion;
    }

    @Override
    public JComboBox<String> getCmbEntorno() {
        return cmbEntorno;
    }

    @Override
    public JComboBox<String> getCmbIncluirPDC() {
        return cmbIncluirPDC;
    }

    @Override
    public JComboBox<String> getCmbPermiso() {
        return cmbPermiso;
    }

    @Override
    public JComboBox<Grant> getCmbReceptorPermisos() {
        return cmbReceptorPermisos;
    }

    @Override
    public JComboBox<String> getCmbWithGrantOption() {
        return cmbWithGrantOption;
    }

    public JTable getTblPermisos() {
        return tblPermisos;
    }

    @Override
    public JTextField getTxtModeloProyecto() {
        return txtModeloProyecto;
    }

    @Override
    public JTextField getTxtModeloProyectoDescrip() {
        return txtModeloProyectoDescrip;
    }  

    @Override
    public JCheckBox getChkHabilitada() {
        return chkHabilitada;
    }

    public JTextField getTxtColumna() {
        return txtColumna;
    }

    public JTextField getTxtTabla() {
        return txtTabla;
    }

    public JButton getBtnLimpiar() {
        return btnLimpiar;
    }
   
}

