/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mdsql.ui.form;

import com.mdsql.bussiness.entities.Grant;
import com.mdsql.ui.form.listener.FormPermisosGeneralesPorModeloPorTipoObjetoListener;
import com.mdsql.bussiness.entities.Propietario;
import com.mdsql.ui.model.PermisosTableModel;
import com.mdsql.ui.model.SinonimosTableModel;
import com.mdsql.ui.model.cabeceras.TablaPermisosCabecera;
import com.mdsql.ui.model.cabeceras.TablaSinonimosCabecera;
import com.mdsql.ui.renderer.TableSelectionRenderer;
import com.mdsql.ui.utils.DialogSupportModeloPermiso;
import com.mdsql.ui.utils.MDSQLUIHelper;
import com.mdval.ui.model.cabeceras.Cabecera;
import com.mdval.ui.utils.FrameSupport;
import java.util.Map;
import javax.swing.JButton;
import javax.swing.JCheckBox;
import javax.swing.JComboBox;
import javax.swing.JTable;
import javax.swing.JTextField;

/**
 *
 * @author Luis-Enrique.Varona
 */
public class FormPermisosGeneralesPorModeloPorTipoObjeto extends DialogSupportModeloPermiso {

    /**
     * Creates new form FormPermisosGeneralesPorModeloPorTipoObjeto 2.1.1
     * Pantalla Permisos Generales por Modelo por tipo de Objeto.
     *
     * @param parent
     * @param modal
     */
    public FormPermisosGeneralesPorModeloPorTipoObjeto(FrameSupport parent, Boolean modal) {
        super(parent, modal);
    }

    public FormPermisosGeneralesPorModeloPorTipoObjeto(FrameSupport parent, Boolean modal, Map<String, Object> params) {
        super(parent, modal, params);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        lblModeloProyecto = new javax.swing.JLabel();
        txtModeloProyecto = new javax.swing.JTextField();
        txtModeloProyectoDescrip = new javax.swing.JTextField();
        lblPermisoSinonimo = new javax.swing.JLabel();
        cmbPermisoSinonimo = new javax.swing.JComboBox<>();
        lblPropietarioSinonimo = new javax.swing.JLabel();
        cmbPropietarioSinonimo = new javax.swing.JComboBox<>();
        lblWithGrantOption = new javax.swing.JLabel();
        cmbWithGrantOption = new javax.swing.JComboBox<>();
        lblPeticion = new javax.swing.JLabel();
        txtPeticion = new javax.swing.JTextField();
        lblFuncionNombre = new javax.swing.JLabel();
        txtFuncionNombre = new javax.swing.JTextField();
        lblUsuarioAlta = new javax.swing.JLabel();
        txtUsuarioAlta = new javax.swing.JTextField();
        lblTipoObjeto = new javax.swing.JLabel();
        cmbTipoObjeto = new javax.swing.JComboBox<>();
        lblReceptorPermisos = new javax.swing.JLabel();
        cmbReceptorPermisos = new javax.swing.JComboBox<>();
        lblFechaAlta = new javax.swing.JLabel();
        txtFechaAlta = new javax.swing.JTextField();
        lblPermiso = new javax.swing.JLabel();
        cmbPermiso = new javax.swing.JComboBox<>();
        lblIncluirPDC = new javax.swing.JLabel();
        cmbIncluirPDC = new javax.swing.JComboBox<>();
        lblUsuarioModificacion = new javax.swing.JLabel();
        txtUsuarioModificacion = new javax.swing.JTextField();
        lblEntorno = new javax.swing.JLabel();
        cmbEntorno = new javax.swing.JComboBox<>();
        chkHabilitada = new javax.swing.JCheckBox();
        btnGuardar = new javax.swing.JButton();
        lblFechaModificacion = new javax.swing.JLabel();
        txtFechaModificacion = new javax.swing.JTextField();
        lblPermisos = new javax.swing.JLabel();
        jScrollPanePermisos = new javax.swing.JScrollPane();
        tblPermisos = new javax.swing.JTable();
        lblSinonimos = new javax.swing.JLabel();
        jScrollPaneSinonimos = new javax.swing.JScrollPane();
        tblSinonimos = new javax.swing.JTable();
        btnInforme = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lblModeloProyecto.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblModeloProyecto.setText("Modelo o Proyecto");
        lblModeloProyecto.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        txtModeloProyecto.setEditable(false);
        txtModeloProyecto.setToolTipText("");

        txtModeloProyectoDescrip.setEditable(false);
        txtModeloProyectoDescrip.setToolTipText("");

        lblPermisoSinonimo.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblPermisoSinonimo.setText("Permiso/Sinónimo");
        lblPermisoSinonimo.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        lblPropietarioSinonimo.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblPropietarioSinonimo.setText("Propietario/Sinónimo");
        lblPropietarioSinonimo.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        lblWithGrantOption.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblWithGrantOption.setText("WITH GRANT OPTION");
        lblWithGrantOption.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        lblPeticion.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblPeticion.setText("Petición");
        lblPeticion.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        lblFuncionNombre.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblFuncionNombre.setText("Función Nombre");
        lblFuncionNombre.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        lblUsuarioAlta.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblUsuarioAlta.setText("Usuario alta");
        lblUsuarioAlta.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        txtUsuarioAlta.setEditable(false);
        txtUsuarioAlta.setToolTipText("");

        lblTipoObjeto.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblTipoObjeto.setText("Tipo de Objeto");
        lblTipoObjeto.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        lblReceptorPermisos.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblReceptorPermisos.setText("Receptor Permisos");
        lblReceptorPermisos.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        lblFechaAlta.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblFechaAlta.setText("Fecha alta");
        lblFechaAlta.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        txtFechaAlta.setEditable(false);
        txtFechaAlta.setToolTipText("");

        lblPermiso.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblPermiso.setText("Permiso");
        lblPermiso.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        lblIncluirPDC.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblIncluirPDC.setText("Incluir en PDC");
        lblIncluirPDC.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        lblUsuarioModificacion.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblUsuarioModificacion.setText("Usuario modificación");
        lblUsuarioModificacion.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        txtUsuarioModificacion.setEditable(false);
        txtUsuarioModificacion.setToolTipText("");

        lblEntorno.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblEntorno.setText("Entorno");
        lblEntorno.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        chkHabilitada.setText("Habilitada   ");
        chkHabilitada.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        chkHabilitada.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        chkHabilitada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkHabilitadaActionPerformed(evt);
            }
        });

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        lblFechaModificacion.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblFechaModificacion.setText("Fecha modificación");
        lblFechaModificacion.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        txtFechaModificacion.setEditable(false);
        txtFechaModificacion.setToolTipText("");

        lblPermisos.setText("Permisos");

        tblPermisos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Receptor", "Tipo Objeto", "Permiso", "Entorno", "Grant Option", "Incluir en PDC", "Habilitada", "Petición", "Usuario Alta", "Fecha Alta", "Usuario Modificacion", "Fecha Modificacion"
            }
        ));
        tblPermisos.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        tblPermisos.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPanePermisos.setViewportView(tblPermisos);

        lblSinonimos.setText("Sinónimos");

        tblSinonimos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Receptor", "Tipo Objeto", "Entorno", "Propietario", "Incluir en PDC", "Habilitada", "Petición", "Función Nombre", "Usuario Alta", "Fecha Alta", "Usuario Modificación", "Fecha Modificacion"
            }
        ));
        tblSinonimos.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        tblSinonimos.setCellSelectionEnabled(true);
        tblSinonimos.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPaneSinonimos.setViewportView(tblSinonimos);

        btnInforme.setText("Informe");

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(478, 478, 478)
                        .addComponent(btnInforme, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(72, 72, 72)
                        .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(396, 396, 396))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblPermisos)
                        .addGap(1100, 1100, 1100))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPaneSinonimos)
                            .addComponent(jScrollPanePermisos)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblSinonimos)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(lblModeloProyecto, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE)
                                            .addComponent(lblPermisoSinonimo, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE)
                                            .addComponent(lblPeticion, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE)
                                            .addComponent(lblTipoObjeto, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE)
                                            .addComponent(lblPermiso, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE)
                                            .addComponent(lblEntorno, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(txtModeloProyecto, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(txtModeloProyectoDescrip, javax.swing.GroupLayout.PREFERRED_SIZE, 899, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(cmbPermisoSinonimo, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(txtPeticion, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(cmbTipoObjeto, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(cmbPermiso, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(cmbEntorno, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addGap(146, 146, 146)
                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                            .addComponent(lblReceptorPermisos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                            .addComponent(lblFuncionNombre, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                            .addComponent(lblPropietarioSinonimo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                            .addComponent(lblIncluirPDC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                            .addComponent(cmbPropietarioSinonimo, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addComponent(txtFuncionNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addComponent(cmbReceptorPermisos, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addComponent(cmbIncluirPDC, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addGap(177, 177, 177))
                                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(chkHabilitada, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGap(324, 324, 324)))
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                            .addComponent(lblFechaAlta, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE)
                                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                            .addComponent(txtFechaAlta, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                            .addComponent(lblUsuarioModificacion, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE)
                                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                            .addComponent(txtUsuarioModificacion, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addComponent(lblUsuarioAlta, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                            .addComponent(lblFechaModificacion, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addComponent(lblWithGrantOption, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                            .addComponent(cmbWithGrantOption, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                                .addComponent(txtUsuarioAlta)
                                                                .addComponent(txtFechaModificacion, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)))))))))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtModeloProyecto, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblModeloProyecto, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtModeloProyectoDescrip, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblPermisoSinonimo, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmbPermisoSinonimo, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblPeticion, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtPeticion, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addComponent(lblTipoObjeto, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cmbTipoObjeto, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(cmbPermiso, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblPermiso, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lblEntorno, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(cmbEntorno, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lblFechaModificacion, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtFechaModificacion, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cmbWithGrantOption, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblWithGrantOption, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtUsuarioAlta, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblUsuarioAlta, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(7, 7, 7)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtFechaAlta, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblFechaAlta, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtUsuarioModificacion, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblUsuarioModificacion, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblPropietarioSinonimo, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmbPropietarioSinonimo, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblFuncionNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtFuncionNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cmbReceptorPermisos, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblReceptorPermisos, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cmbIncluirPDC, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblIncluirPDC, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(chkHabilitada, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(12, 12, 12)
                .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(lblPermisos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPanePermisos, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(lblSinonimos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPaneSinonimos, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnInforme, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void chkHabilitadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkHabilitadaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkHabilitadaActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCancelarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnInforme;
    private javax.swing.JCheckBox chkHabilitada;
    private javax.swing.JComboBox<String> cmbEntorno;
    private javax.swing.JComboBox<String> cmbIncluirPDC;
    private javax.swing.JComboBox<String> cmbPermiso;
    private javax.swing.JComboBox<String> cmbPermisoSinonimo;
    private javax.swing.JComboBox<Propietario> cmbPropietarioSinonimo;
    private javax.swing.JComboBox<Grant> cmbReceptorPermisos;
    private javax.swing.JComboBox<String> cmbTipoObjeto;
    private javax.swing.JComboBox<String> cmbWithGrantOption;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPanePermisos;
    private javax.swing.JScrollPane jScrollPaneSinonimos;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblEntorno;
    private javax.swing.JLabel lblFechaAlta;
    private javax.swing.JLabel lblFechaModificacion;
    private javax.swing.JLabel lblFuncionNombre;
    private javax.swing.JLabel lblIncluirPDC;
    private javax.swing.JLabel lblModeloProyecto;
    private javax.swing.JLabel lblPermiso;
    private javax.swing.JLabel lblPermisoSinonimo;
    private javax.swing.JLabel lblPermisos;
    private javax.swing.JLabel lblPeticion;
    private javax.swing.JLabel lblPropietarioSinonimo;
    private javax.swing.JLabel lblReceptorPermisos;
    private javax.swing.JLabel lblSinonimos;
    private javax.swing.JLabel lblTipoObjeto;
    private javax.swing.JLabel lblUsuarioAlta;
    private javax.swing.JLabel lblUsuarioModificacion;
    private javax.swing.JLabel lblWithGrantOption;
    private javax.swing.JTable tblPermisos;
    private javax.swing.JTable tblSinonimos;
    private javax.swing.JTextField txtFechaAlta;
    private javax.swing.JTextField txtFechaModificacion;
    private javax.swing.JTextField txtFuncionNombre;
    private javax.swing.JTextField txtModeloProyecto;
    private javax.swing.JTextField txtModeloProyectoDescrip;
    private javax.swing.JTextField txtPeticion;
    private javax.swing.JTextField txtUsuarioAlta;
    private javax.swing.JTextField txtUsuarioModificacion;
    // End of variables declaration//GEN-END:variables

    @Override
    protected void setupComponents() {
        initComponents();
    }

    @Override
    protected void initEvents() {
        formListener = new FormPermisosGeneralesPorModeloPorTipoObjetoListener(this);
        btnGuardar.addActionListener(formListener);
        btnInforme.addActionListener(formListener);
        btnCancelar.addActionListener(formListener);
        tblPermisos.getSelectionModel().addListSelectionListener((FormPermisosGeneralesPorModeloPorTipoObjetoListener) formListener);
        tblSinonimos.getSelectionModel().addListSelectionListener((FormPermisosGeneralesPorModeloPorTipoObjetoListener) formListener);
        addOnLoadListener(formListener);
    }

    @Override
    protected void setupLiterals() {
        setTitle(literales.getLiteral("FormPermisosGeneralesPorModeloPorTipoObjeto.title"));
        lblModeloProyecto.setText(literales.getLiteral("FormPermisosGeneralesPorModeloPorTipoObjeto.lblModeloProyecto"));
        lblPermisoSinonimo.setText(literales.getLiteral("FormPermisosGeneralesPorModeloPorTipoObjeto.lblPermisoSinonimo"));
        lblPropietarioSinonimo.setText(literales.getLiteral("FormPermisosGeneralesPorModeloPorTipoObjeto.lblPropietarioSinonimo"));
        lblWithGrantOption.setText(literales.getLiteral("FormPermisosGeneralesPorModeloPorTipoObjeto.lblWithGrantOption"));
        lblPeticion.setText(literales.getLiteral("FormPermisosGeneralesPorModeloPorTipoObjeto.lblPeticion"));
        lblFuncionNombre.setText(literales.getLiteral("FormPermisosGeneralesPorModeloPorTipoObjeto.lblFuncionNombre"));
        lblUsuarioAlta.setText(literales.getLiteral("FormPermisosGeneralesPorModeloPorTipoObjeto.lblUsuarioAlta"));
        lblTipoObjeto.setText(literales.getLiteral("FormPermisosGeneralesPorModeloPorTipoObjeto.lblTipoObjeto"));
        lblReceptorPermisos.setText(literales.getLiteral("FormPermisosGeneralesPorModeloPorTipoObjeto.lblReceptorPermisos"));
        lblFechaAlta.setText(literales.getLiteral("FormPermisosGeneralesPorModeloPorTipoObjeto.lblFechaAlta"));
        lblPermiso.setText(literales.getLiteral("FormPermisosGeneralesPorModeloPorTipoObjeto.lblPermiso"));
        lblIncluirPDC.setText(literales.getLiteral("FormPermisosGeneralesPorModeloPorTipoObjeto.lblIncluirPDC"));
        lblUsuarioModificacion.setText(literales.getLiteral("FormPermisosGeneralesPorModeloPorTipoObjeto.lblUsuarioModificacion"));
        lblEntorno.setText(literales.getLiteral("FormPermisosGeneralesPorModeloPorTipoObjeto.lblEntorno"));
        chkHabilitada.setText(literales.getLiteral("FormPermisosGeneralesPorModeloPorTipoObjeto.chkHabilitada"));
        lblFechaModificacion.setText(literales.getLiteral("FormPermisosGeneralesPorModeloPorTipoObjeto.lblFechaModificacion"));
        lblPermisos.setText(literales.getLiteral("FormPermisosGeneralesPorModeloPorTipoObjeto.lblPermisos"));
        lblSinonimos.setText(literales.getLiteral("FormPermisosGeneralesPorModeloPorTipoObjeto.lblSinonimos"));
        btnGuardar.setText(literales.getLiteral("FormPermisosGeneralesPorModeloPorTipoObjeto.btnGuardar"));
        btnInforme.setText(literales.getLiteral("FormPermisosGeneralesPorModeloPorTipoObjeto.btnInforme"));
        btnCancelar.setText(literales.getLiteral("FormPermisosGeneralesPorModeloPorTipoObjeto.btnCancelar"));
    }

    @Override
    protected void initModels() {
        Cabecera cabeceraPermisos = new TablaPermisosCabecera();
        MDSQLUIHelper.setTableModel(tblPermisos, new PermisosTableModel(cabeceraPermisos));

        Cabecera cabeceraSinonimos = new TablaSinonimosCabecera();
        MDSQLUIHelper.setTableModel(tblSinonimos, new SinonimosTableModel(cabeceraSinonimos));
        //
        tblPermisos.setDefaultRenderer(String.class, new TableSelectionRenderer());
        tblPermisos.setCellSelectionEnabled(true);
        tblPermisos.setRowSelectionAllowed(true);
        //
        tblSinonimos.setDefaultRenderer(String.class, new TableSelectionRenderer());
        tblSinonimos.setCellSelectionEnabled(true);
        tblSinonimos.setRowSelectionAllowed(true);
    }

    @Override
    protected void initialState() {
        formListener.clearForm();
    }

    @Override
    public JButton getBtnCancelar() {
        return btnCancelar;
    }

    public JButton getBtnGuardar() {
        return btnGuardar;
    }

    public JButton getBtnInforme() {
        return btnInforme;
    }

    @Override
    public JComboBox<String> getCmbTipoObjeto() {
        return cmbTipoObjeto;
    }

    @Override
    public JComboBox<Propietario> getCmbPropietarioSinonimo() {
        return cmbPropietarioSinonimo;
    }

    @Override
    public JComboBox<Grant> getCmbReceptorPermisos() {
        return cmbReceptorPermisos;
    }

    public JTable getTblPermisos() {
        return tblPermisos;
    }

    public JTable getTblSinonimos() {
        return tblSinonimos;
    }

    @Override
    public JTextField getTxtModeloProyecto() {
        return txtModeloProyecto;
    }

    @Override
    public JTextField getTxtModeloProyectoDescrip() {
        return txtModeloProyectoDescrip;
    }

    @Override
    public JCheckBox getChkHabilitada() {
        return chkHabilitada;
    }

    @Override
    public JComboBox<String> getCmbEntorno() {
        return cmbEntorno;
    }

    @Override
    public JComboBox<String> getCmbIncluirPDC() {
        return cmbIncluirPDC;
    }

    @Override
    public JComboBox<String> getCmbPermiso() {
        return cmbPermiso;
    }

    @Override
    public JComboBox<String> getCmbPermisoSinonimo() {
        return cmbPermisoSinonimo;
    }

    @Override
    public JComboBox<String> getCmbWithGrantOption() {
        return cmbWithGrantOption;
    }

    @Override
    public JTextField getTxtFuncionNombre() {
        return txtFuncionNombre;
    }

    @Override
    public JTextField getTxtPeticion() {
        return txtPeticion;
    }

    public JTextField getTxtFechaModificacion() {
        return txtFechaModificacion;
    }

    public JTextField getTxtUsuarioAlta() {
        return txtUsuarioAlta;
    }

    public JTextField getTxtUsuarioModificacion() {
        return txtUsuarioModificacion;
    }

    public JTextField getTxtFechaAlta() {
        return txtFechaAlta;
    }

}
