/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mdsql.ui.form;

import com.mdsql.bussiness.entities.SubProyecto;
import com.mdsql.ui.adapter.DoubleClickMouseAdapter;
import com.mdsql.ui.adapter.FormGenerarPermisosPersonalizadosMouseAdapter;
import com.mdsql.ui.form.listener.FormGenerarPermisosPersonalizadosListener;
import com.mdsql.ui.model.PermisosColumnaTableModel;
import com.mdsql.ui.model.SinonimosObjetoTableModel;
import com.mdsql.ui.model.cabeceras.TablaPermisosColumnaCabecera;
import com.mdsql.ui.model.cabeceras.TablaSinonimosObjetoCabecera;
import com.mdsql.ui.renderer.TableSelectionRenderer;
import com.mdsql.ui.utils.DialogSupportModeloPermiso;
import com.mdsql.ui.utils.MDSQLUIHelper;
import com.mdval.ui.model.cabeceras.Cabecera;
import com.mdval.ui.utils.FrameSupport;
import java.util.Map;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JTable;
import javax.swing.JTextArea;
import javax.swing.JTextField;
import javax.swing.ListSelectionModel;

/**
 *
 * @author Luis-Enrique.Varona
 */
public class FormGenerarPermisosPersonalizados extends DialogSupportModeloPermiso {

    /**
     * Creates new form FormGenerarPermisosPersonalizados 2.1.2.6-Pantalla
     * Generar Permisos Personalizados.
     *
     * @param parent
     * @param modal
     */
    public FormGenerarPermisosPersonalizados(FrameSupport parent, Boolean modal) {
        super(parent, modal);
    }

    public FormGenerarPermisosPersonalizados(FrameSupport parent, Boolean modal, Map<String, Object> params) {
        super(parent, modal, params);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblModeloProyecto = new javax.swing.JLabel();
        txtModeloProyecto = new javax.swing.JTextField();
        btnModeloProyecto = new javax.swing.JButton();
        lblSubModelo = new javax.swing.JLabel();
        cmbSubModelo = new javax.swing.JComboBox<>();
        lblTipoObjeto = new javax.swing.JLabel();
        cmbTipoObjeto = new javax.swing.JComboBox<>();
        jScrollPaneNombreObjeto = new javax.swing.JScrollPane();
        txtNombreObjeto = new javax.swing.JTextArea();
        lblNombreObjeto = new javax.swing.JLabel();
        lblPeticion = new javax.swing.JLabel();
        txtPeticion = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        lblTablaPermisos = new javax.swing.JLabel();
        scrollPanePermisos = new javax.swing.JScrollPane();
        tblPermisos = new javax.swing.JTable();
        lblTablaSinonimos = new javax.swing.JLabel();
        scrollPaneSinonimos = new javax.swing.JScrollPane();
        tblSinonimos = new javax.swing.JTable();
        btnGenerar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lblModeloProyecto.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblModeloProyecto.setText("Modelo o Proyecto");

        btnModeloProyecto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/loupe.png"))); // NOI18N

        lblSubModelo.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblSubModelo.setText("Submodelo");

        lblTipoObjeto.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblTipoObjeto.setText("Tipo de Objeto");
        lblTipoObjeto.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        txtNombreObjeto.setColumns(20);
        txtNombreObjeto.setRows(5);
        jScrollPaneNombreObjeto.setViewportView(txtNombreObjeto);

        lblNombreObjeto.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblNombreObjeto.setText("Nombre Objeto");

        lblPeticion.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblPeticion.setText("Petición");

        btnBuscar.setText("Buscar");

        btnLimpiar.setText("Limpiar");

        lblTablaPermisos.setText("Permisos");

        tblPermisos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Receptor", "Modelo", "Objeto", "Columna", "Tipo Objeto", "Permiso", "Entorno", "Grant Option", "Incluir en PDC", "Habilitada", "Petición"
            }
        ));
        tblPermisos.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        scrollPanePermisos.setViewportView(tblPermisos);

        lblTablaSinonimos.setText("Sinónimos");

        tblSinonimos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Receptor", "Modelo", "Objeto", "Tipo Objeto", "Entorno", "Propietario", "Incluir en PDC", "Habilitada", "Petición", "Función Nombre"
            }
        ));
        tblSinonimos.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        scrollPaneSinonimos.setViewportView(tblSinonimos);

        btnGenerar.setText("Generar");

        btnCancelar.setText("CANCELAR");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(scrollPanePermisos)
                    .addComponent(scrollPaneSinonimos)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblTablaPermisos)
                            .addComponent(lblTablaSinonimos)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblModeloProyecto, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblTipoObjeto, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblPeticion, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtPeticion, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(txtModeloProyecto, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(cmbTipoObjeto, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnModeloProyecto)))
                                .addGap(715, 715, 715)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblSubModelo, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(cmbSubModelo, javax.swing.GroupLayout.PREFERRED_SIZE, 351, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblNombreObjeto, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jScrollPaneNombreObjeto, javax.swing.GroupLayout.PREFERRED_SIZE, 351, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(550, 550, 550)
                        .addComponent(btnGenerar, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50)
                        .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(550, 550, 550)
                        .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50)
                        .addComponent(btnLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, 0))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnBuscar, btnCancelar, btnGenerar});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cmbSubModelo, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblSubModelo, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnModeloProyecto, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblModeloProyecto, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtModeloProyecto, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lblTipoObjeto, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(cmbTipoObjeto, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lblNombreObjeto, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblPeticion, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtPeticion, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPaneNombreObjeto, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblTablaPermisos, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scrollPanePermisos, javax.swing.GroupLayout.DEFAULT_SIZE, 177, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblTablaSinonimos, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(scrollPaneSinonimos, javax.swing.GroupLayout.DEFAULT_SIZE, 177, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGenerar, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20))
        );

        btnLimpiar.getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnGenerar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnModeloProyecto;
    private javax.swing.JComboBox<SubProyecto> cmbSubModelo;
    private javax.swing.JComboBox<String> cmbTipoObjeto;
    private javax.swing.JScrollPane jScrollPaneNombreObjeto;
    private javax.swing.JLabel lblModeloProyecto;
    private javax.swing.JLabel lblNombreObjeto;
    private javax.swing.JLabel lblPeticion;
    private javax.swing.JLabel lblSubModelo;
    private javax.swing.JLabel lblTablaPermisos;
    private javax.swing.JLabel lblTablaSinonimos;
    private javax.swing.JLabel lblTipoObjeto;
    private javax.swing.JScrollPane scrollPanePermisos;
    private javax.swing.JScrollPane scrollPaneSinonimos;
    private javax.swing.JTable tblPermisos;
    private javax.swing.JTable tblSinonimos;
    private javax.swing.JTextField txtModeloProyecto;
    private javax.swing.JTextArea txtNombreObjeto;
    private javax.swing.JTextField txtPeticion;
    // End of variables declaration//GEN-END:variables
   @Override
    protected void setupComponents() {
        initComponents();
    }

    @Override
    protected void initEvents() {
        FormGenerarPermisosPersonalizadosListener localFormListener = new FormGenerarPermisosPersonalizadosListener(this);
        btnBuscar.addActionListener(localFormListener);
        btnLimpiar.addActionListener(localFormListener);
        btnGenerar.addActionListener(localFormListener);

        tblPermisos.getSelectionModel().addListSelectionListener(localFormListener);
        tblSinonimos.getSelectionModel().addListSelectionListener(localFormListener);

        formListener = localFormListener;
        addOnLoadListener(formListener);
    }

    @Override
    protected void setupLiterals() {
        setTitle(literales.getLiteral("FormGenerarPermisosPersonalizados.title"));
        lblModeloProyecto.setText(literales.getLiteral("FormGenerarPermisosPersonalizados.lblModeloProyecto"));
        lblSubModelo.setText(literales.getLiteral("FormGenerarPermisosPersonalizados.lblSubModelo"));
        lblNombreObjeto.setText(literales.getLiteral("FormGenerarPermisosPersonalizados.lblNombreObjeto"));
        lblPeticion.setText(literales.getLiteral("FormGenerarPermisosPersonalizados.lblPeticion"));
        lblTablaPermisos.setText(literales.getLiteral("FormGenerarPermisosPersonalizados.lblTablaPermisos"));
        btnBuscar.setText(literales.getLiteral("FormGenerarPermisosPersonalizados.btnBuscar"));
        btnLimpiar.setText(literales.getLiteral("FormGenerarPermisosPersonalizados.btnLimpiar"));
        lblTablaSinonimos.setText(literales.getLiteral("FormGenerarPermisosPersonalizados.lblTablaSinonimos"));
        btnGenerar.setText(literales.getLiteral("FormGenerarPermisosPersonalizados.btnGenerar"));
        btnCancelar.setText(literales.getLiteral("FormGenerarPermisosPersonalizados.btnCancelar"));
    }

    @Override
    protected void initModels() {
        Cabecera cabeceraPermisos = new TablaPermisosColumnaCabecera();
        MDSQLUIHelper.setTableModel(tblPermisos, new PermisosColumnaTableModel(cabeceraPermisos));
        //
        Cabecera cabeceraSinonimo = new TablaSinonimosObjetoCabecera();
        MDSQLUIHelper.setTableModel(tblSinonimos, new SinonimosObjetoTableModel(cabeceraSinonimo));
        //
        tblPermisos.setDefaultRenderer(String.class, new TableSelectionRenderer());
        tblPermisos.setCellSelectionEnabled(true);
        tblPermisos.setRowSelectionAllowed(true);
        tblPermisos.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        //
        tblSinonimos.setDefaultRenderer(String.class, new TableSelectionRenderer());
        tblSinonimos.setCellSelectionEnabled(true);
        tblSinonimos.setRowSelectionAllowed(true);
        tblSinonimos.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);

        // Tratamiento doble click
        FormGenerarPermisosPersonalizadosMouseAdapter doubleClickMouseAdapter = new FormGenerarPermisosPersonalizadosMouseAdapter();
        doubleClickMouseAdapter.setPantalla(this);
        tblPermisos.addMouseListener(doubleClickMouseAdapter);
        tblSinonimos.addMouseListener(doubleClickMouseAdapter);
    }

    @Override
    protected void initialState() {
        btnGenerar.setEnabled(false);
    }

    public JButton getBtnBuscar() {
        return btnBuscar;
    }

    @Override
    public JButton getBtnCancelar() {
        return btnCancelar;
    }

    public JButton getBtnGenerar() {
        return btnGenerar;
    }

    @Override
    public JButton getBtnModeloProyecto() {
        return btnModeloProyecto;
    }

    @Override
    public JComboBox<SubProyecto> getCmbSubModelo() {
        return cmbSubModelo;
    }

    public JTable getTblPermisos() {
        return tblPermisos;
    }

    public JTable getTblSinonimos() {
        return tblSinonimos;
    }

    @Override
    public JTextField getTxtModeloProyecto() {
        return txtModeloProyecto;
    }

    public JTextArea getTxtNombreObjeto() {
        return txtNombreObjeto;
    }

    @Override
    public JTextField getTxtPeticion() {
        return txtPeticion;
    }

    @Override
    public JComboBox<String> getCmbTipoObjeto() {
        return cmbTipoObjeto;
    }

    @Override
    public JButton getBtnLimpiar() {
        return btnLimpiar;
    }
}
